// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_api/bilibili/im/interfaces/inner-interface/v1/api.proto

package bilibili_im_interface_inner_interface_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
type BanUser struct {
	// 用户mid
	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// 封禁业务
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// 封禁时间
	Time int32 `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	// 模式
	// 1:add 2:remove
	Mode                 int32    `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BanUser) Reset()         { *m = BanUser{} }
func (m *BanUser) String() string { return proto.CompactTextString(m) }
func (*BanUser) ProtoMessage()    {}
func (*BanUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f933e59a0f7f4b0, []int{0}
}

func (m *BanUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BanUser.Unmarshal(m, b)
}
func (m *BanUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BanUser.Marshal(b, m, deterministic)
}
func (m *BanUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BanUser.Merge(m, src)
}
func (m *BanUser) XXX_Size() int {
	return xxx_messageInfo_BanUser.Size(m)
}
func (m *BanUser) XXX_DiscardUnknown() {
	xxx_messageInfo_BanUser.DiscardUnknown(m)
}

var xxx_messageInfo_BanUser proto.InternalMessageInfo

func (m *BanUser) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *BanUser) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *BanUser) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *BanUser) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

//
type ReqOpBlacklist struct {
	// 需要封禁/解封的用户信息
	BanUsers             []*BanUser `protobuf:"bytes,1,rep,name=ban_users,json=banUsers,proto3" json:"ban_users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReqOpBlacklist) Reset()         { *m = ReqOpBlacklist{} }
func (m *ReqOpBlacklist) String() string { return proto.CompactTextString(m) }
func (*ReqOpBlacklist) ProtoMessage()    {}
func (*ReqOpBlacklist) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f933e59a0f7f4b0, []int{1}
}

func (m *ReqOpBlacklist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqOpBlacklist.Unmarshal(m, b)
}
func (m *ReqOpBlacklist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqOpBlacklist.Marshal(b, m, deterministic)
}
func (m *ReqOpBlacklist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqOpBlacklist.Merge(m, src)
}
func (m *ReqOpBlacklist) XXX_Size() int {
	return xxx_messageInfo_ReqOpBlacklist.Size(m)
}
func (m *ReqOpBlacklist) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqOpBlacklist.DiscardUnknown(m)
}

var xxx_messageInfo_ReqOpBlacklist proto.InternalMessageInfo

func (m *ReqOpBlacklist) GetBanUsers() []*BanUser {
	if m != nil {
		return m.BanUsers
	}
	return nil
}

//
type RspOpBlacklist struct {
	//
	FailedUsers          []uint64 `protobuf:"varint,1,rep,packed,name=failed_users,json=failedUsers,proto3" json:"failed_users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspOpBlacklist) Reset()         { *m = RspOpBlacklist{} }
func (m *RspOpBlacklist) String() string { return proto.CompactTextString(m) }
func (*RspOpBlacklist) ProtoMessage()    {}
func (*RspOpBlacklist) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f933e59a0f7f4b0, []int{2}
}

func (m *RspOpBlacklist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspOpBlacklist.Unmarshal(m, b)
}
func (m *RspOpBlacklist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspOpBlacklist.Marshal(b, m, deterministic)
}
func (m *RspOpBlacklist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspOpBlacklist.Merge(m, src)
}
func (m *RspOpBlacklist) XXX_Size() int {
	return xxx_messageInfo_RspOpBlacklist.Size(m)
}
func (m *RspOpBlacklist) XXX_DiscardUnknown() {
	xxx_messageInfo_RspOpBlacklist.DiscardUnknown(m)
}

var xxx_messageInfo_RspOpBlacklist proto.InternalMessageInfo

func (m *RspOpBlacklist) GetFailedUsers() []uint64 {
	if m != nil {
		return m.FailedUsers
	}
	return nil
}

func init() {
	proto.RegisterType((*BanUser)(nil), "bilibili.im.interface.inner.interface.v1.BanUser")
	proto.RegisterType((*ReqOpBlacklist)(nil), "bilibili.im.interface.inner.interface.v1.ReqOpBlacklist")
	proto.RegisterType((*RspOpBlacklist)(nil), "bilibili.im.interface.inner.interface.v1.RspOpBlacklist")
}

func init() {
	proto.RegisterFile("grpc_api/bilibili/im/interfaces/inner-interface/v1/api.proto", fileDescriptor_0f933e59a0f7f4b0)
}

var fileDescriptor_0f933e59a0f7f4b0 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x85, 0xe5, 0xbf, 0xe9, 0x0f, 0xdc, 0x42, 0x84, 0x2c, 0x86, 0x88, 0x29, 0x64, 0xca, 0x82,
	0xad, 0xb4, 0x0b, 0x03, 0x53, 0xb7, 0x48, 0x08, 0x24, 0x4b, 0x1d, 0x98, 0x8a, 0x93, 0xb8, 0xe8,
	0x8a, 0xc4, 0x31, 0xb6, 0xdb, 0x17, 0xe0, 0x1d, 0x78, 0x5e, 0x94, 0x84, 0x56, 0xe9, 0x56, 0x06,
	0x4b, 0xe7, 0x7e, 0xf2, 0xb9, 0xe7, 0x58, 0x86, 0xc7, 0x77, 0x6b, 0xca, 0xb5, 0x34, 0xc8, 0x0b,
	0xac, 0xb1, 0x3b, 0x1c, 0x1b, 0x8e, 0xda, 0x2b, 0xbb, 0x91, 0xa5, 0x72, 0x1c, 0xb5, 0x56, 0xf6,
	0xfe, 0x00, 0xf8, 0x2e, 0xe3, 0xd2, 0x20, 0x33, 0xb6, 0xf5, 0x2d, 0x4d, 0xf7, 0x26, 0x86, 0x0d,
	0x3b, 0xdc, 0x61, 0xbd, 0x67, 0x34, 0xef, 0xb2, 0xe4, 0x15, 0xce, 0x96, 0x52, 0xaf, 0x9c, 0xb2,
	0xf4, 0x1a, 0x26, 0x5b, 0xac, 0x22, 0x12, 0x93, 0x34, 0x10, 0x9d, 0xa4, 0x37, 0x30, 0xad, 0xb1,
	0x41, 0x1f, 0xfd, 0x8b, 0x49, 0x3a, 0x15, 0xc3, 0x40, 0x29, 0x04, 0x1e, 0x1b, 0x15, 0x4d, 0x7a,
	0xd8, 0xeb, 0x8e, 0x35, 0x6d, 0xa5, 0xa2, 0x60, 0x60, 0x9d, 0x4e, 0xde, 0x20, 0x14, 0xea, 0xf3,
	0xc5, 0x2c, 0x6b, 0x59, 0x7e, 0xd4, 0xe8, 0x3c, 0x7d, 0x86, 0x8b, 0x42, 0xea, 0xf5, 0xd6, 0x29,
	0xeb, 0x22, 0x12, 0x4f, 0xd2, 0xd9, 0x3c, 0x63, 0xa7, 0x56, 0x65, 0xbf, 0x3d, 0xc5, 0x79, 0x31,
	0x08, 0x97, 0x2c, 0x20, 0x14, 0xce, 0x8c, 0x13, 0xee, 0xe0, 0x72, 0x23, 0xb1, 0x56, 0xd5, 0x28,
	0x24, 0x10, 0xb3, 0x81, 0xf5, 0xa6, 0xf9, 0x37, 0x81, 0x30, 0xef, 0xb6, 0xe7, 0xfb, 0xe5, 0xf4,
	0x8b, 0xc0, 0xd5, 0xca, 0x54, 0xd2, 0xab, 0x27, 0x74, 0x3e, 0xd7, 0x9a, 0x3e, 0x9c, 0x5e, 0xeb,
	0xf8, 0x8d, 0xb7, 0x7f, 0x71, 0x1e, 0x75, 0x2f, 0xfe, 0xf7, 0x7f, 0xb7, 0xf8, 0x09, 0x00, 0x00,
	0xff, 0xff, 0x0c, 0xdd, 0x62, 0xb6, 0xfb, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InnerInterfaceClient is the client API for InnerInterface service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InnerInterfaceClient interface {
	//
	UpdateListInn(ctx context.Context, in *ReqOpBlacklist, opts ...grpc.CallOption) (*RspOpBlacklist, error)
}

type innerInterfaceClient struct {
	cc *grpc.ClientConn
}

func NewInnerInterfaceClient(cc *grpc.ClientConn) InnerInterfaceClient {
	return &innerInterfaceClient{cc}
}

func (c *innerInterfaceClient) UpdateListInn(ctx context.Context, in *ReqOpBlacklist, opts ...grpc.CallOption) (*RspOpBlacklist, error) {
	out := new(RspOpBlacklist)
	err := c.cc.Invoke(ctx, "/bilibili.im.interface.inner.interface.v1.InnerInterface/UpdateListInn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InnerInterfaceServer is the server API for InnerInterface service.
type InnerInterfaceServer interface {
	//
	UpdateListInn(context.Context, *ReqOpBlacklist) (*RspOpBlacklist, error)
}

// UnimplementedInnerInterfaceServer can be embedded to have forward compatible implementations.
type UnimplementedInnerInterfaceServer struct {
}

func (*UnimplementedInnerInterfaceServer) UpdateListInn(ctx context.Context, req *ReqOpBlacklist) (*RspOpBlacklist, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateListInn not implemented")
}

func RegisterInnerInterfaceServer(s *grpc.Server, srv InnerInterfaceServer) {
	s.RegisterService(&_InnerInterface_serviceDesc, srv)
}

func _InnerInterface_UpdateListInn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqOpBlacklist)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InnerInterfaceServer).UpdateListInn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bilibili.im.interface.inner.interface.v1.InnerInterface/UpdateListInn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InnerInterfaceServer).UpdateListInn(ctx, req.(*ReqOpBlacklist))
	}
	return interceptor(ctx, in, info, handler)
}

var _InnerInterface_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bilibili.im.interface.inner.interface.v1.InnerInterface",
	HandlerType: (*InnerInterfaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateListInn",
			Handler:    _InnerInterface_UpdateListInn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_api/bilibili/im/interfaces/inner-interface/v1/api.proto",
}
