// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_api/bilibili/live/general/interfaces/v1/interfaces.proto

package bilibili_live_general_interfaces_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
type GetOnlineRankReq struct {
	//
	Ruid int64 `protobuf:"varint,1,opt,name=ruid,proto3" json:"ruid,omitempty"`
	//
	RoomId int64 `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	//
	Page int64 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	//
	PageSize int64 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	//
	Platform             string   `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOnlineRankReq) Reset()         { *m = GetOnlineRankReq{} }
func (m *GetOnlineRankReq) String() string { return proto.CompactTextString(m) }
func (*GetOnlineRankReq) ProtoMessage()    {}
func (*GetOnlineRankReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f01be425ba3b7357, []int{0}
}

func (m *GetOnlineRankReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOnlineRankReq.Unmarshal(m, b)
}
func (m *GetOnlineRankReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOnlineRankReq.Marshal(b, m, deterministic)
}
func (m *GetOnlineRankReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOnlineRankReq.Merge(m, src)
}
func (m *GetOnlineRankReq) XXX_Size() int {
	return xxx_messageInfo_GetOnlineRankReq.Size(m)
}
func (m *GetOnlineRankReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOnlineRankReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOnlineRankReq proto.InternalMessageInfo

func (m *GetOnlineRankReq) GetRuid() int64 {
	if m != nil {
		return m.Ruid
	}
	return 0
}

func (m *GetOnlineRankReq) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *GetOnlineRankReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetOnlineRankReq) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetOnlineRankReq) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

//
type GetOnlineRankResp struct {
	//
	Item *GetOnlineRankResp_OnlineRankItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	//
	OnlineNum            int64    `protobuf:"varint,2,opt,name=online_num,json=onlineNum,proto3" json:"online_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOnlineRankResp) Reset()         { *m = GetOnlineRankResp{} }
func (m *GetOnlineRankResp) String() string { return proto.CompactTextString(m) }
func (*GetOnlineRankResp) ProtoMessage()    {}
func (*GetOnlineRankResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f01be425ba3b7357, []int{1}
}

func (m *GetOnlineRankResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOnlineRankResp.Unmarshal(m, b)
}
func (m *GetOnlineRankResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOnlineRankResp.Marshal(b, m, deterministic)
}
func (m *GetOnlineRankResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOnlineRankResp.Merge(m, src)
}
func (m *GetOnlineRankResp) XXX_Size() int {
	return xxx_messageInfo_GetOnlineRankResp.Size(m)
}
func (m *GetOnlineRankResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOnlineRankResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetOnlineRankResp proto.InternalMessageInfo

func (m *GetOnlineRankResp) GetItem() *GetOnlineRankResp_OnlineRankItem {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *GetOnlineRankResp) GetOnlineNum() int64 {
	if m != nil {
		return m.OnlineNum
	}
	return 0
}

//
type GetOnlineRankResp_OnlineRankItem struct {
	//
	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	//
	Uname string `protobuf:"bytes,2,opt,name=uname,proto3" json:"uname,omitempty"`
	//
	Face string `protobuf:"bytes,3,opt,name=face,proto3" json:"face,omitempty"`
	//
	ContinueWatch int64 `protobuf:"varint,4,opt,name=continue_watch,json=continueWatch,proto3" json:"continue_watch,omitempty"`
	//
	MedalInfo *MedalInfo `protobuf:"bytes,5,opt,name=medal_info,json=medalInfo,proto3" json:"medal_info,omitempty"`
	//
	GuardLevel           int64    `protobuf:"varint,6,opt,name=guard_level,json=guardLevel,proto3" json:"guard_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOnlineRankResp_OnlineRankItem) Reset()         { *m = GetOnlineRankResp_OnlineRankItem{} }
func (m *GetOnlineRankResp_OnlineRankItem) String() string { return proto.CompactTextString(m) }
func (*GetOnlineRankResp_OnlineRankItem) ProtoMessage()    {}
func (*GetOnlineRankResp_OnlineRankItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_f01be425ba3b7357, []int{1, 0}
}

func (m *GetOnlineRankResp_OnlineRankItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOnlineRankResp_OnlineRankItem.Unmarshal(m, b)
}
func (m *GetOnlineRankResp_OnlineRankItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOnlineRankResp_OnlineRankItem.Marshal(b, m, deterministic)
}
func (m *GetOnlineRankResp_OnlineRankItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOnlineRankResp_OnlineRankItem.Merge(m, src)
}
func (m *GetOnlineRankResp_OnlineRankItem) XXX_Size() int {
	return xxx_messageInfo_GetOnlineRankResp_OnlineRankItem.Size(m)
}
func (m *GetOnlineRankResp_OnlineRankItem) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOnlineRankResp_OnlineRankItem.DiscardUnknown(m)
}

var xxx_messageInfo_GetOnlineRankResp_OnlineRankItem proto.InternalMessageInfo

func (m *GetOnlineRankResp_OnlineRankItem) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GetOnlineRankResp_OnlineRankItem) GetUname() string {
	if m != nil {
		return m.Uname
	}
	return ""
}

func (m *GetOnlineRankResp_OnlineRankItem) GetFace() string {
	if m != nil {
		return m.Face
	}
	return ""
}

func (m *GetOnlineRankResp_OnlineRankItem) GetContinueWatch() int64 {
	if m != nil {
		return m.ContinueWatch
	}
	return 0
}

func (m *GetOnlineRankResp_OnlineRankItem) GetMedalInfo() *MedalInfo {
	if m != nil {
		return m.MedalInfo
	}
	return nil
}

func (m *GetOnlineRankResp_OnlineRankItem) GetGuardLevel() int64 {
	if m != nil {
		return m.GuardLevel
	}
	return 0
}

//
type MedalInfo struct {
	//
	GuardLevel int64 `protobuf:"varint,1,opt,name=guard_level,json=guardLevel,proto3" json:"guard_level,omitempty"`
	//
	MedalColorStart int64 `protobuf:"varint,2,opt,name=medal_color_start,json=medalColorStart,proto3" json:"medal_color_start,omitempty"`
	//
	MedalColorEnd int64 `protobuf:"varint,3,opt,name=medal_color_end,json=medalColorEnd,proto3" json:"medal_color_end,omitempty"`
	//
	MedalColorBorder int64 `protobuf:"varint,4,opt,name=medal_color_border,json=medalColorBorder,proto3" json:"medal_color_border,omitempty"`
	//
	MedalName string `protobuf:"bytes,5,opt,name=medal_name,json=medalName,proto3" json:"medal_name,omitempty"`
	//
	Level int64 `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	//
	TargetId int64 `protobuf:"varint,7,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	//
	IsLight              int64    `protobuf:"varint,8,opt,name=is_light,json=isLight,proto3" json:"is_light,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MedalInfo) Reset()         { *m = MedalInfo{} }
func (m *MedalInfo) String() string { return proto.CompactTextString(m) }
func (*MedalInfo) ProtoMessage()    {}
func (*MedalInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f01be425ba3b7357, []int{2}
}

func (m *MedalInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MedalInfo.Unmarshal(m, b)
}
func (m *MedalInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MedalInfo.Marshal(b, m, deterministic)
}
func (m *MedalInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MedalInfo.Merge(m, src)
}
func (m *MedalInfo) XXX_Size() int {
	return xxx_messageInfo_MedalInfo.Size(m)
}
func (m *MedalInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MedalInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MedalInfo proto.InternalMessageInfo

func (m *MedalInfo) GetGuardLevel() int64 {
	if m != nil {
		return m.GuardLevel
	}
	return 0
}

func (m *MedalInfo) GetMedalColorStart() int64 {
	if m != nil {
		return m.MedalColorStart
	}
	return 0
}

func (m *MedalInfo) GetMedalColorEnd() int64 {
	if m != nil {
		return m.MedalColorEnd
	}
	return 0
}

func (m *MedalInfo) GetMedalColorBorder() int64 {
	if m != nil {
		return m.MedalColorBorder
	}
	return 0
}

func (m *MedalInfo) GetMedalName() string {
	if m != nil {
		return m.MedalName
	}
	return ""
}

func (m *MedalInfo) GetLevel() int64 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *MedalInfo) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *MedalInfo) GetIsLight() int64 {
	if m != nil {
		return m.IsLight
	}
	return 0
}

func init() {
	proto.RegisterType((*GetOnlineRankReq)(nil), "bilibili.live.general.interfaces.v1.GetOnlineRankReq")
	proto.RegisterType((*GetOnlineRankResp)(nil), "bilibili.live.general.interfaces.v1.GetOnlineRankResp")
	proto.RegisterType((*GetOnlineRankResp_OnlineRankItem)(nil), "bilibili.live.general.interfaces.v1.GetOnlineRankResp.OnlineRankItem")
	proto.RegisterType((*MedalInfo)(nil), "bilibili.live.general.interfaces.v1.MedalInfo")
}

func init() {
	proto.RegisterFile("grpc_api/bilibili/live/general/interfaces/v1/interfaces.proto", fileDescriptor_f01be425ba3b7357)
}

var fileDescriptor_f01be425ba3b7357 = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xdd, 0x6a, 0xd4, 0x40,
	0x14, 0x26, 0xdd, 0xdf, 0x9c, 0xa5, 0xed, 0x76, 0x28, 0x18, 0x2b, 0x62, 0x59, 0x51, 0x8a, 0x48,
	0x96, 0xd6, 0x6b, 0x6f, 0x94, 0x22, 0x0b, 0xdd, 0x0a, 0xe9, 0x85, 0x78, 0x15, 0x66, 0x93, 0xb3,
	0xe9, 0xe0, 0x64, 0x26, 0x4e, 0x26, 0x2b, 0xf4, 0x19, 0x7c, 0x03, 0x1f, 0xcf, 0x47, 0xf0, 0x05,
	0xe4, 0xcc, 0x64, 0xdd, 0x58, 0x11, 0x7a, 0xb1, 0xec, 0xf9, 0xbe, 0xf9, 0xbe, 0xc9, 0x39, 0x5f,
	0x4e, 0xe0, 0x6d, 0x61, 0xaa, 0x2c, 0xe5, 0x95, 0x98, 0xaf, 0x84, 0x14, 0xf4, 0x9b, 0x4b, 0xb1,
	0xc1, 0x79, 0x81, 0x0a, 0x0d, 0x97, 0x73, 0xa1, 0x2c, 0x9a, 0x35, 0xcf, 0xb0, 0x9e, 0x6f, 0xce,
	0x3b, 0x28, 0xae, 0x8c, 0xb6, 0x9a, 0x3d, 0xdf, 0xba, 0x62, 0x72, 0xc5, 0xad, 0x2b, 0xee, 0xe8,
	0x36, 0xe7, 0xb3, 0xef, 0x01, 0x4c, 0x3f, 0xa0, 0xfd, 0xa8, 0xa4, 0x50, 0x98, 0x70, 0xf5, 0x25,
	0xc1, 0xaf, 0x8c, 0x41, 0xdf, 0x34, 0x22, 0x8f, 0x82, 0xd3, 0xe0, 0xac, 0x97, 0xb8, 0x9a, 0x3d,
	0x82, 0x91, 0xd1, 0xba, 0x4c, 0x45, 0x1e, 0xed, 0x39, 0x7a, 0x48, 0x70, 0x91, 0x93, 0xb8, 0xe2,
	0x05, 0x46, 0x3d, 0x2f, 0xa6, 0x9a, 0x3d, 0x81, 0x90, 0xfe, 0xd3, 0x5a, 0xdc, 0x61, 0xd4, 0x77,
	0x07, 0x63, 0x22, 0x6e, 0xc4, 0x1d, 0xb2, 0x13, 0x18, 0x57, 0x92, 0xdb, 0xb5, 0x36, 0x65, 0x34,
	0x38, 0x0d, 0xce, 0xc2, 0xe4, 0x0f, 0x9e, 0xfd, 0xda, 0x83, 0xa3, 0x7b, 0xed, 0xd4, 0x15, 0xfb,
	0x0c, 0x7d, 0x61, 0xb1, 0x74, 0xfd, 0x4c, 0x2e, 0x2e, 0xe3, 0x07, 0x0c, 0x16, 0xff, 0x73, 0x4b,
	0xbc, 0x83, 0x0b, 0x8b, 0x65, 0xe2, 0xae, 0x64, 0x4f, 0x01, 0xb4, 0xe3, 0x53, 0xd5, 0x94, 0xed,
	0x64, 0xa1, 0x67, 0xae, 0x9b, 0xf2, 0xe4, 0x67, 0x00, 0x07, 0x7f, 0xfb, 0xd8, 0x14, 0x7a, 0xbb,
	0x6c, 0xa8, 0x64, 0xc7, 0x30, 0x68, 0x14, 0x2f, 0xd1, 0xd9, 0xc3, 0xc4, 0x03, 0xca, 0x85, 0x9a,
	0x71, 0xb9, 0x84, 0x89, 0xab, 0xd9, 0x0b, 0x38, 0xc8, 0xb4, 0xb2, 0x42, 0x35, 0x98, 0x7e, 0xe3,
	0x36, 0xbb, 0x6d, 0xc3, 0xd9, 0xdf, 0xb2, 0x9f, 0x88, 0x64, 0x4b, 0x80, 0x12, 0x73, 0x2e, 0x53,
	0xa1, 0xd6, 0xda, 0x65, 0x34, 0xb9, 0x88, 0x1f, 0x34, 0xf5, 0x92, 0x6c, 0x0b, 0xb5, 0xd6, 0x49,
	0x58, 0x6e, 0x4b, 0xf6, 0x0c, 0x26, 0x45, 0xc3, 0x4d, 0x9e, 0x4a, 0xdc, 0xa0, 0x8c, 0x86, 0xee,
	0x91, 0xe0, 0xa8, 0x2b, 0x62, 0x66, 0x3f, 0xf6, 0x20, 0x5c, 0xfe, 0x4f, 0x1e, 0xdc, 0x97, 0xb3,
	0x57, 0x70, 0xe4, 0xdb, 0xcb, 0xb4, 0xd4, 0x26, 0xad, 0x2d, 0x37, 0xb6, 0x8d, 0xee, 0xd0, 0x1d,
	0xbc, 0x27, 0xfe, 0x86, 0x68, 0xf6, 0x12, 0x0e, 0xbb, 0x5a, 0x54, 0x79, 0xbb, 0x28, 0xfb, 0x3b,
	0xe5, 0xa5, 0xca, 0xd9, 0x6b, 0x60, 0x5d, 0xdd, 0x4a, 0x9b, 0x1c, 0x4d, 0x9b, 0xce, 0x74, 0x27,
	0x7d, 0xe7, 0x78, 0x7a, 0x6b, 0x5e, 0xed, 0x62, 0xf7, 0x4b, 0xe4, 0x07, 0xbe, 0xa6, 0xe8, 0x8f,
	0x61, 0xd0, 0x1d, 0xd5, 0x03, 0x5a, 0x4a, 0xcb, 0x4d, 0x81, 0x96, 0x76, 0x78, 0xe4, 0x97, 0xd2,
	0x13, 0x8b, 0x9c, 0x3d, 0x86, 0xb1, 0xa8, 0x53, 0x29, 0x8a, 0x5b, 0x1b, 0x8d, 0xdd, 0xd9, 0x48,
	0xd4, 0x57, 0x04, 0x57, 0x43, 0xf7, 0x39, 0xbd, 0xf9, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xea,
	0xdf, 0x34, 0x8f, 0x03, 0x00, 0x00,
}
