// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_api/bilibili/broadcast/message/esports/notify.proto

package bilibili_broadcast_message_esports

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Notify struct {
	// cid
	Cid                  int64    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notify) Reset()         { *m = Notify{} }
func (m *Notify) String() string { return proto.CompactTextString(m) }
func (*Notify) ProtoMessage()    {}
func (*Notify) Descriptor() ([]byte, []int) {
	return fileDescriptor_193be39d01cca9fa, []int{0}
}

func (m *Notify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notify.Unmarshal(m, b)
}
func (m *Notify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notify.Marshal(b, m, deterministic)
}
func (m *Notify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notify.Merge(m, src)
}
func (m *Notify) XXX_Size() int {
	return xxx_messageInfo_Notify.Size(m)
}
func (m *Notify) XXX_DiscardUnknown() {
	xxx_messageInfo_Notify.DiscardUnknown(m)
}

var xxx_messageInfo_Notify proto.InternalMessageInfo

func (m *Notify) GetCid() int64 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func init() {
	proto.RegisterType((*Notify)(nil), "bilibili.broadcast.message.esports.Notify")
}

func init() {
	proto.RegisterFile("grpc_api/bilibili/broadcast/message/esports/notify.proto", fileDescriptor_193be39d01cca9fa)
}

var fileDescriptor_193be39d01cca9fa = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x48, 0x2f, 0x2a, 0x48,
	0x8e, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xca, 0xcc, 0xc9, 0x04, 0x61, 0xfd, 0xa4, 0xa2, 0xfc, 0xc4,
	0x94, 0xe4, 0xc4, 0xe2, 0x12, 0xfd, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0xfd, 0xd4, 0xe2,
	0x82, 0xfc, 0xa2, 0x92, 0x62, 0xfd, 0xbc, 0xfc, 0x92, 0xcc, 0xb4, 0x4a, 0xbd, 0x82, 0xa2, 0xfc,
	0x92, 0x7c, 0x21, 0x25, 0x98, 0x06, 0x3d, 0xb8, 0x06, 0x3d, 0xa8, 0x06, 0x3d, 0xa8, 0x06, 0x25,
	0x29, 0x2e, 0x36, 0x3f, 0xb0, 0x1e, 0x21, 0x01, 0x2e, 0xe6, 0xe4, 0xcc, 0x14, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xe6, 0x20, 0x10, 0x33, 0x89, 0x0d, 0x6c, 0x8c, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0xf6, 0x4f, 0xf8, 0xcf, 0x82, 0x00, 0x00, 0x00,
}
