// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_api/bilibili/app/space/v1/space.proto

package bilibili_app_space_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//-响应
type ArchiveReply struct {
	//
	Item []*BiliSpaceVideo `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	//
	Count int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	//
	EpisodicButton *EpisodicButton `protobuf:"bytes,3,opt,name=episodic_button,json=episodicButton,proto3" json:"episodic_button,omitempty"`
	//
	Order                []*OrderConfig `protobuf:"bytes,4,rep,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ArchiveReply) Reset()         { *m = ArchiveReply{} }
func (m *ArchiveReply) String() string { return proto.CompactTextString(m) }
func (*ArchiveReply) ProtoMessage()    {}
func (*ArchiveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f526aeebb4d4a7, []int{0}
}

func (m *ArchiveReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArchiveReply.Unmarshal(m, b)
}
func (m *ArchiveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArchiveReply.Marshal(b, m, deterministic)
}
func (m *ArchiveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArchiveReply.Merge(m, src)
}
func (m *ArchiveReply) XXX_Size() int {
	return xxx_messageInfo_ArchiveReply.Size(m)
}
func (m *ArchiveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ArchiveReply.DiscardUnknown(m)
}

var xxx_messageInfo_ArchiveReply proto.InternalMessageInfo

func (m *ArchiveReply) GetItem() []*BiliSpaceVideo {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *ArchiveReply) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ArchiveReply) GetEpisodicButton() *EpisodicButton {
	if m != nil {
		return m.EpisodicButton
	}
	return nil
}

func (m *ArchiveReply) GetOrder() []*OrderConfig {
	if m != nil {
		return m.Order
	}
	return nil
}

//-请求
type ArchiveReq struct {
	//
	Vmid int64 `protobuf:"varint,1,opt,name=vmid,proto3" json:"vmid,omitempty"`
	//
	Pn int32 `protobuf:"varint,2,opt,name=pn,proto3" json:"pn,omitempty"`
	//
	Ps int32 `protobuf:"varint,3,opt,name=ps,proto3" json:"ps,omitempty"`
	//
	Order                string   `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArchiveReq) Reset()         { *m = ArchiveReq{} }
func (m *ArchiveReq) String() string { return proto.CompactTextString(m) }
func (*ArchiveReq) ProtoMessage()    {}
func (*ArchiveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f526aeebb4d4a7, []int{1}
}

func (m *ArchiveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArchiveReq.Unmarshal(m, b)
}
func (m *ArchiveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArchiveReq.Marshal(b, m, deterministic)
}
func (m *ArchiveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArchiveReq.Merge(m, src)
}
func (m *ArchiveReq) XXX_Size() int {
	return xxx_messageInfo_ArchiveReq.Size(m)
}
func (m *ArchiveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ArchiveReq.DiscardUnknown(m)
}

var xxx_messageInfo_ArchiveReq proto.InternalMessageInfo

func (m *ArchiveReq) GetVmid() int64 {
	if m != nil {
		return m.Vmid
	}
	return 0
}

func (m *ArchiveReq) GetPn() int32 {
	if m != nil {
		return m.Pn
	}
	return 0
}

func (m *ArchiveReq) GetPs() int32 {
	if m != nil {
		return m.Ps
	}
	return 0
}

func (m *ArchiveReq) GetOrder() string {
	if m != nil {
		return m.Order
	}
	return ""
}

//
type Badge struct {
	//
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	//
	TextColor string `protobuf:"bytes,2,opt,name=text_color,json=textColor,proto3" json:"text_color,omitempty"`
	//
	TextColorNight string `protobuf:"bytes,3,opt,name=text_color_night,json=textColorNight,proto3" json:"text_color_night,omitempty"`
	//
	BgColor string `protobuf:"bytes,4,opt,name=bg_color,json=bgColor,proto3" json:"bg_color,omitempty"`
	//
	BgColorNight string `protobuf:"bytes,5,opt,name=bg_color_night,json=bgColorNight,proto3" json:"bg_color_night,omitempty"`
	//
	BorderColor string `protobuf:"bytes,6,opt,name=border_color,json=borderColor,proto3" json:"border_color,omitempty"`
	//
	BorderColorNight string `protobuf:"bytes,7,opt,name=border_color_night,json=borderColorNight,proto3" json:"border_color_night,omitempty"`
	//
	BgStyle              int32    `protobuf:"varint,8,opt,name=bg_style,json=bgStyle,proto3" json:"bg_style,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Badge) Reset()         { *m = Badge{} }
func (m *Badge) String() string { return proto.CompactTextString(m) }
func (*Badge) ProtoMessage()    {}
func (*Badge) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f526aeebb4d4a7, []int{2}
}

func (m *Badge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Badge.Unmarshal(m, b)
}
func (m *Badge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Badge.Marshal(b, m, deterministic)
}
func (m *Badge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Badge.Merge(m, src)
}
func (m *Badge) XXX_Size() int {
	return xxx_messageInfo_Badge.Size(m)
}
func (m *Badge) XXX_DiscardUnknown() {
	xxx_messageInfo_Badge.DiscardUnknown(m)
}

var xxx_messageInfo_Badge proto.InternalMessageInfo

func (m *Badge) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Badge) GetTextColor() string {
	if m != nil {
		return m.TextColor
	}
	return ""
}

func (m *Badge) GetTextColorNight() string {
	if m != nil {
		return m.TextColorNight
	}
	return ""
}

func (m *Badge) GetBgColor() string {
	if m != nil {
		return m.BgColor
	}
	return ""
}

func (m *Badge) GetBgColorNight() string {
	if m != nil {
		return m.BgColorNight
	}
	return ""
}

func (m *Badge) GetBorderColor() string {
	if m != nil {
		return m.BorderColor
	}
	return ""
}

func (m *Badge) GetBorderColorNight() string {
	if m != nil {
		return m.BorderColorNight
	}
	return ""
}

func (m *Badge) GetBgStyle() int32 {
	if m != nil {
		return m.BgStyle
	}
	return 0
}

//
type BiliSpaceVideo struct {
	//
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	//
	Tname string `protobuf:"bytes,2,opt,name=tname,proto3" json:"tname,omitempty"`
	//
	Duration int64 `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	//
	Cover string `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	//
	Uri string `protobuf:"bytes,5,opt,name=uri,proto3" json:"uri,omitempty"`
	//
	Param string `protobuf:"bytes,6,opt,name=param,proto3" json:"param,omitempty"`
	//
	Danmaku string `protobuf:"bytes,7,opt,name=danmaku,proto3" json:"danmaku,omitempty"`
	//
	Play int32 `protobuf:"varint,8,opt,name=play,proto3" json:"play,omitempty"`
	//
	Ctime int64 `protobuf:"varint,9,opt,name=ctime,proto3" json:"ctime,omitempty"`
	//
	State bool `protobuf:"varint,10,opt,name=state,proto3" json:"state,omitempty"`
	//
	IsPopular bool `protobuf:"varint,11,opt,name=is_popular,json=isPopular,proto3" json:"is_popular,omitempty"`
	//
	Badges []*Badge `protobuf:"bytes,12,rep,name=badges,proto3" json:"badges,omitempty"`
	//
	CoverRight string `protobuf:"bytes,13,opt,name=cover_right,json=coverRight,proto3" json:"cover_right,omitempty"`
	//
	Bvid string `protobuf:"bytes,14,opt,name=bvid,proto3" json:"bvid,omitempty"`
	//
	IsSteins bool `protobuf:"varint,15,opt,name=is_steins,json=isSteins,proto3" json:"is_steins,omitempty"`
	//
	IsUgcpay bool `protobuf:"varint,16,opt,name=is_ugcpay,json=isUgcpay,proto3" json:"is_ugcpay,omitempty"`
	//
	IsCooperation        bool     `protobuf:"varint,17,opt,name=is_cooperation,json=isCooperation,proto3" json:"is_cooperation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BiliSpaceVideo) Reset()         { *m = BiliSpaceVideo{} }
func (m *BiliSpaceVideo) String() string { return proto.CompactTextString(m) }
func (*BiliSpaceVideo) ProtoMessage()    {}
func (*BiliSpaceVideo) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f526aeebb4d4a7, []int{3}
}

func (m *BiliSpaceVideo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BiliSpaceVideo.Unmarshal(m, b)
}
func (m *BiliSpaceVideo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BiliSpaceVideo.Marshal(b, m, deterministic)
}
func (m *BiliSpaceVideo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BiliSpaceVideo.Merge(m, src)
}
func (m *BiliSpaceVideo) XXX_Size() int {
	return xxx_messageInfo_BiliSpaceVideo.Size(m)
}
func (m *BiliSpaceVideo) XXX_DiscardUnknown() {
	xxx_messageInfo_BiliSpaceVideo.DiscardUnknown(m)
}

var xxx_messageInfo_BiliSpaceVideo proto.InternalMessageInfo

func (m *BiliSpaceVideo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BiliSpaceVideo) GetTname() string {
	if m != nil {
		return m.Tname
	}
	return ""
}

func (m *BiliSpaceVideo) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *BiliSpaceVideo) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *BiliSpaceVideo) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *BiliSpaceVideo) GetParam() string {
	if m != nil {
		return m.Param
	}
	return ""
}

func (m *BiliSpaceVideo) GetDanmaku() string {
	if m != nil {
		return m.Danmaku
	}
	return ""
}

func (m *BiliSpaceVideo) GetPlay() int32 {
	if m != nil {
		return m.Play
	}
	return 0
}

func (m *BiliSpaceVideo) GetCtime() int64 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

func (m *BiliSpaceVideo) GetState() bool {
	if m != nil {
		return m.State
	}
	return false
}

func (m *BiliSpaceVideo) GetIsPopular() bool {
	if m != nil {
		return m.IsPopular
	}
	return false
}

func (m *BiliSpaceVideo) GetBadges() []*Badge {
	if m != nil {
		return m.Badges
	}
	return nil
}

func (m *BiliSpaceVideo) GetCoverRight() string {
	if m != nil {
		return m.CoverRight
	}
	return ""
}

func (m *BiliSpaceVideo) GetBvid() string {
	if m != nil {
		return m.Bvid
	}
	return ""
}

func (m *BiliSpaceVideo) GetIsSteins() bool {
	if m != nil {
		return m.IsSteins
	}
	return false
}

func (m *BiliSpaceVideo) GetIsUgcpay() bool {
	if m != nil {
		return m.IsUgcpay
	}
	return false
}

func (m *BiliSpaceVideo) GetIsCooperation() bool {
	if m != nil {
		return m.IsCooperation
	}
	return false
}

//
type EpisodicButton struct {
	//
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	//
	Uri                  string   `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EpisodicButton) Reset()         { *m = EpisodicButton{} }
func (m *EpisodicButton) String() string { return proto.CompactTextString(m) }
func (*EpisodicButton) ProtoMessage()    {}
func (*EpisodicButton) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f526aeebb4d4a7, []int{4}
}

func (m *EpisodicButton) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpisodicButton.Unmarshal(m, b)
}
func (m *EpisodicButton) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpisodicButton.Marshal(b, m, deterministic)
}
func (m *EpisodicButton) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpisodicButton.Merge(m, src)
}
func (m *EpisodicButton) XXX_Size() int {
	return xxx_messageInfo_EpisodicButton.Size(m)
}
func (m *EpisodicButton) XXX_DiscardUnknown() {
	xxx_messageInfo_EpisodicButton.DiscardUnknown(m)
}

var xxx_messageInfo_EpisodicButton proto.InternalMessageInfo

func (m *EpisodicButton) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *EpisodicButton) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

//
type OrderConfig struct {
	//
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	//
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderConfig) Reset()         { *m = OrderConfig{} }
func (m *OrderConfig) String() string { return proto.CompactTextString(m) }
func (*OrderConfig) ProtoMessage()    {}
func (*OrderConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_02f526aeebb4d4a7, []int{5}
}

func (m *OrderConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderConfig.Unmarshal(m, b)
}
func (m *OrderConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderConfig.Marshal(b, m, deterministic)
}
func (m *OrderConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderConfig.Merge(m, src)
}
func (m *OrderConfig) XXX_Size() int {
	return xxx_messageInfo_OrderConfig.Size(m)
}
func (m *OrderConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderConfig.DiscardUnknown(m)
}

var xxx_messageInfo_OrderConfig proto.InternalMessageInfo

func (m *OrderConfig) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *OrderConfig) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*ArchiveReply)(nil), "bilibili.app.space.v1.ArchiveReply")
	proto.RegisterType((*ArchiveReq)(nil), "bilibili.app.space.v1.ArchiveReq")
	proto.RegisterType((*Badge)(nil), "bilibili.app.space.v1.Badge")
	proto.RegisterType((*BiliSpaceVideo)(nil), "bilibili.app.space.v1.BiliSpaceVideo")
	proto.RegisterType((*EpisodicButton)(nil), "bilibili.app.space.v1.EpisodicButton")
	proto.RegisterType((*OrderConfig)(nil), "bilibili.app.space.v1.OrderConfig")
}

func init() {
	proto.RegisterFile("grpc_api/bilibili/app/space/v1/space.proto", fileDescriptor_02f526aeebb4d4a7)
}

var fileDescriptor_02f526aeebb4d4a7 = []byte{
	// 649 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x5d, 0x6f, 0xd3, 0x3c,
	0x14, 0x56, 0xfa, 0xb1, 0x36, 0xa7, 0x5d, 0xd6, 0xd7, 0x7a, 0x91, 0xcc, 0x00, 0xd1, 0x15, 0x26,
	0x55, 0x08, 0xb5, 0xda, 0x40, 0x88, 0x5d, 0xb2, 0x89, 0xdb, 0x01, 0x99, 0xd8, 0x05, 0x37, 0x91,
	0x93, 0x98, 0xcc, 0x22, 0x4d, 0x4c, 0xec, 0x44, 0xf4, 0x67, 0xf0, 0xfb, 0xf8, 0x05, 0xfc, 0x0b,
	0xe4, 0x63, 0xf7, 0x4b, 0x5a, 0xe1, 0xa2, 0xea, 0x79, 0xce, 0x79, 0xfc, 0xf8, 0x7c, 0x39, 0xf0,
	0x22, 0xab, 0x64, 0x12, 0x31, 0x29, 0xe6, 0xb1, 0xc8, 0x85, 0xf9, 0xcd, 0x99, 0x94, 0x73, 0x25,
	0x59, 0xc2, 0xe7, 0xcd, 0x99, 0x35, 0x66, 0xb2, 0x2a, 0x75, 0x49, 0x1e, 0xac, 0x28, 0x33, 0x26,
	0xe5, 0xcc, 0x46, 0x9a, 0xb3, 0xc9, 0x6f, 0x0f, 0x86, 0xef, 0xaa, 0xe4, 0x4e, 0x34, 0x3c, 0xe4,
	0x32, 0x5f, 0x92, 0x0b, 0xe8, 0x08, 0xcd, 0x17, 0xd4, 0x1b, 0xb7, 0xa7, 0x83, 0xf3, 0xd3, 0xd9,
	0xbd, 0xc7, 0x66, 0x97, 0x22, 0x17, 0x37, 0x06, 0xdc, 0x8a, 0x94, 0x97, 0x21, 0x1e, 0x21, 0xff,
	0x43, 0x37, 0x29, 0xeb, 0x42, 0xd3, 0xd6, 0xd8, 0x9b, 0x76, 0x43, 0x0b, 0xc8, 0x35, 0x1c, 0x71,
	0x29, 0x54, 0x99, 0x8a, 0x24, 0x8a, 0x6b, 0xad, 0xcb, 0x82, 0xb6, 0xc7, 0xde, 0x5f, 0xb4, 0xdf,
	0x3b, 0xf6, 0x25, 0x92, 0xc3, 0x80, 0xef, 0x60, 0xf2, 0x16, 0xba, 0x65, 0x95, 0xf2, 0x8a, 0x76,
	0x30, 0xc3, 0xc9, 0x1e, 0x95, 0x0f, 0x86, 0x73, 0x55, 0x16, 0x5f, 0x45, 0x16, 0xda, 0x03, 0x93,
	0x5b, 0x80, 0x75, 0xa9, 0xdf, 0x09, 0x81, 0x4e, 0xb3, 0x10, 0x29, 0xf5, 0xc6, 0xde, 0xb4, 0x1d,
	0xa2, 0x4d, 0x02, 0x68, 0xc9, 0xc2, 0xa5, 0xdf, 0x92, 0x05, 0x62, 0x85, 0xe9, 0x1a, 0xac, 0x4c,
	0x85, 0xab, 0xbb, 0xbd, 0xa9, 0xbf, 0xd2, 0xfd, 0xd9, 0x82, 0xee, 0x25, 0x4b, 0x33, 0x6e, 0x34,
	0x35, 0xff, 0xa1, 0x51, 0xd3, 0x0f, 0xd1, 0x26, 0x4f, 0x00, 0xcc, 0x7f, 0x94, 0x94, 0x79, 0x59,
	0xa1, 0xb6, 0x1f, 0xfa, 0xc6, 0x73, 0x65, 0x1c, 0x64, 0x0a, 0xa3, 0x4d, 0x38, 0x2a, 0x44, 0x76,
	0xa7, 0xf1, 0x42, 0x3f, 0x0c, 0xd6, 0xa4, 0x6b, 0xe3, 0x25, 0x0f, 0xa1, 0x1f, 0x67, 0x4e, 0xc6,
	0xde, 0xdf, 0x8b, 0x33, 0x2b, 0xf2, 0x1c, 0x82, 0x55, 0xc8, 0x49, 0x74, 0x91, 0x30, 0x74, 0x04,
	0x2b, 0x70, 0x02, 0xc3, 0x18, 0x33, 0x76, 0x22, 0x07, 0xc8, 0x19, 0x58, 0x9f, 0x15, 0x7a, 0x09,
	0x64, 0x9b, 0xe2, 0xc4, 0x7a, 0x48, 0x1c, 0x6d, 0x11, 0xb7, 0x33, 0x52, 0x7a, 0x99, 0x73, 0xda,
	0xc7, 0x26, 0xf5, 0xe2, 0xec, 0xc6, 0xc0, 0xc9, 0xaf, 0x36, 0x04, 0xbb, 0x4b, 0x62, 0x9a, 0xa7,
	0x85, 0xce, 0xb9, 0xeb, 0x8e, 0x05, 0xe8, 0x2d, 0xd8, 0x82, 0xbb, 0xce, 0x58, 0x40, 0x8e, 0xa1,
	0x9f, 0xd6, 0x15, 0xd3, 0xc2, 0x6d, 0x4b, 0x3b, 0x5c, 0x63, 0xbb, 0x66, 0xcd, 0x66, 0x08, 0x08,
	0xc8, 0x08, 0xda, 0x75, 0x25, 0x5c, 0xdd, 0xc6, 0x34, 0x3c, 0xc9, 0x2a, 0xb6, 0x70, 0x75, 0x5a,
	0x40, 0x28, 0xf4, 0x52, 0x56, 0x2c, 0xd8, 0xb7, 0xda, 0x95, 0xb5, 0x82, 0x66, 0x78, 0x32, 0x67,
	0x4b, 0x57, 0x09, 0xda, 0x78, 0x97, 0x16, 0x0b, 0x4e, 0x7d, 0x4c, 0xc2, 0x02, 0xe3, 0x55, 0x9a,
	0x69, 0x4e, 0x61, 0xec, 0x4d, 0xfb, 0xa1, 0x05, 0x66, 0xd0, 0x42, 0x45, 0xb2, 0x94, 0x75, 0xce,
	0x2a, 0x3a, 0xc0, 0x90, 0x2f, 0xd4, 0x47, 0xeb, 0x20, 0xaf, 0xe1, 0x20, 0x36, 0x4b, 0xa2, 0xe8,
	0x10, 0x17, 0xf7, 0xf1, 0xbe, 0xa7, 0x65, 0x48, 0xa1, 0xe3, 0x92, 0xa7, 0x30, 0xc0, 0xfa, 0xa2,
	0x0a, 0x27, 0x71, 0x88, 0x29, 0x03, 0xba, 0x42, 0x9c, 0x01, 0x81, 0x4e, 0xdc, 0x88, 0x94, 0x06,
	0x76, 0xe5, 0x8c, 0x4d, 0x1e, 0x81, 0x2f, 0x54, 0xa4, 0x34, 0x17, 0x85, 0xa2, 0x47, 0x98, 0x48,
	0x5f, 0xa8, 0x1b, 0xc4, 0x2e, 0x58, 0x67, 0x89, 0x64, 0x4b, 0x3a, 0x5a, 0x05, 0x3f, 0x23, 0x26,
	0xa7, 0x10, 0x08, 0x15, 0x25, 0x65, 0x29, 0xb9, 0xeb, 0xfe, 0x7f, 0xc8, 0x38, 0x14, 0xea, 0x6a,
	0xe3, 0x9c, 0xbc, 0x81, 0x60, 0xf7, 0x95, 0xde, 0xbb, 0xf9, 0x6e, 0x24, 0xad, 0xf5, 0x48, 0x26,
	0x17, 0x30, 0xd8, 0x7a, 0x97, 0xfb, 0x37, 0xa2, 0x61, 0x79, 0xbd, 0xde, 0x08, 0x04, 0xe7, 0x5f,
	0xa0, 0x8b, 0xbb, 0x44, 0x3e, 0x41, 0xcf, 0xbd, 0x62, 0x72, 0xb2, 0xa7, 0x85, 0x9b, 0x57, 0x7e,
	0xfc, 0xec, 0x5f, 0x14, 0x99, 0x2f, 0xe3, 0x03, 0xfc, 0x44, 0xbe, 0xfa, 0x13, 0x00, 0x00, 0xff,
	0xff, 0x78, 0xa1, 0x8a, 0x17, 0x50, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SpaceClient is the client API for Space service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SpaceClient interface {
	//
	Archive(ctx context.Context, in *ArchiveReq, opts ...grpc.CallOption) (*ArchiveReply, error)
}

type spaceClient struct {
	cc *grpc.ClientConn
}

func NewSpaceClient(cc *grpc.ClientConn) SpaceClient {
	return &spaceClient{cc}
}

func (c *spaceClient) Archive(ctx context.Context, in *ArchiveReq, opts ...grpc.CallOption) (*ArchiveReply, error) {
	out := new(ArchiveReply)
	err := c.cc.Invoke(ctx, "/bilibili.app.space.v1.Space/Archive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpaceServer is the server API for Space service.
type SpaceServer interface {
	//
	Archive(context.Context, *ArchiveReq) (*ArchiveReply, error)
}

// UnimplementedSpaceServer can be embedded to have forward compatible implementations.
type UnimplementedSpaceServer struct {
}

func (*UnimplementedSpaceServer) Archive(ctx context.Context, req *ArchiveReq) (*ArchiveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Archive not implemented")
}

func RegisterSpaceServer(s *grpc.Server, srv SpaceServer) {
	s.RegisterService(&_Space_serviceDesc, srv)
}

func _Space_Archive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceServer).Archive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bilibili.app.space.v1.Space/Archive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceServer).Archive(ctx, req.(*ArchiveReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Space_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bilibili.app.space.v1.Space",
	HandlerType: (*SpaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Archive",
			Handler:    _Space_Archive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_api/bilibili/app/space/v1/space.proto",
}
