// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_api/bilibili/polymer/contract/contract.proto

package bilibili_polymer_contract

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
type AddContractReq struct {
	//
	Common *CommonReq `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	//
	Mid int64 `protobuf:"varint,2,opt,name=mid,proto3" json:"mid,omitempty"`
	//
	UpMid int64 `protobuf:"varint,3,opt,name=up_mid,json=upMid,proto3" json:"up_mid,omitempty"`
	//
	Aid                  int64    `protobuf:"varint,4,opt,name=aid,proto3" json:"aid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddContractReq) Reset()         { *m = AddContractReq{} }
func (m *AddContractReq) String() string { return proto.CompactTextString(m) }
func (*AddContractReq) ProtoMessage()    {}
func (*AddContractReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5609dea102791199, []int{0}
}

func (m *AddContractReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddContractReq.Unmarshal(m, b)
}
func (m *AddContractReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddContractReq.Marshal(b, m, deterministic)
}
func (m *AddContractReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddContractReq.Merge(m, src)
}
func (m *AddContractReq) XXX_Size() int {
	return xxx_messageInfo_AddContractReq.Size(m)
}
func (m *AddContractReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddContractReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddContractReq proto.InternalMessageInfo

func (m *AddContractReq) GetCommon() *CommonReq {
	if m != nil {
		return m.Common
	}
	return nil
}

func (m *AddContractReq) GetMid() int64 {
	if m != nil {
		return m.Mid
	}
	return 0
}

func (m *AddContractReq) GetUpMid() int64 {
	if m != nil {
		return m.UpMid
	}
	return 0
}

func (m *AddContractReq) GetAid() int64 {
	if m != nil {
		return m.Aid
	}
	return 0
}

//
type CommonReq struct {
	//
	Platform string `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	//
	Build int32 `protobuf:"varint,2,opt,name=build,proto3" json:"build,omitempty"`
	//
	Buvid string `protobuf:"bytes,3,opt,name=buvid,proto3" json:"buvid,omitempty"`
	//
	MobiApp string `protobuf:"bytes,4,opt,name=mobi_app,json=mobiApp,proto3" json:"mobi_app,omitempty"`
	//
	Device string `protobuf:"bytes,5,opt,name=device,proto3" json:"device,omitempty"`
	//
	Ip string `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`
	//
	Spmid                string   `protobuf:"bytes,7,opt,name=spmid,proto3" json:"spmid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonReq) Reset()         { *m = CommonReq{} }
func (m *CommonReq) String() string { return proto.CompactTextString(m) }
func (*CommonReq) ProtoMessage()    {}
func (*CommonReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5609dea102791199, []int{1}
}

func (m *CommonReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonReq.Unmarshal(m, b)
}
func (m *CommonReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonReq.Marshal(b, m, deterministic)
}
func (m *CommonReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonReq.Merge(m, src)
}
func (m *CommonReq) XXX_Size() int {
	return xxx_messageInfo_CommonReq.Size(m)
}
func (m *CommonReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonReq.DiscardUnknown(m)
}

var xxx_messageInfo_CommonReq proto.InternalMessageInfo

func (m *CommonReq) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *CommonReq) GetBuild() int32 {
	if m != nil {
		return m.Build
	}
	return 0
}

func (m *CommonReq) GetBuvid() string {
	if m != nil {
		return m.Buvid
	}
	return ""
}

func (m *CommonReq) GetMobiApp() string {
	if m != nil {
		return m.MobiApp
	}
	return ""
}

func (m *CommonReq) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *CommonReq) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *CommonReq) GetSpmid() string {
	if m != nil {
		return m.Spmid
	}
	return ""
}

func init() {
	proto.RegisterType((*AddContractReq)(nil), "bilibili.polymer.contract.AddContractReq")
	proto.RegisterType((*CommonReq)(nil), "bilibili.polymer.contract.CommonReq")
}

func init() {
	proto.RegisterFile("grpc_api/bilibili/polymer/contract/contract.proto", fileDescriptor_5609dea102791199)
}

var fileDescriptor_5609dea102791199 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x41, 0x6b, 0xc2, 0x40,
	0x10, 0x85, 0x89, 0x36, 0xd1, 0x8c, 0x20, 0x65, 0x69, 0x25, 0xda, 0x8b, 0x48, 0x0f, 0xf6, 0xb2,
	0xa1, 0xf6, 0xda, 0x8b, 0x48, 0x8f, 0x85, 0xb2, 0xe7, 0x82, 0x24, 0xd9, 0x55, 0x06, 0xb2, 0xee,
	0x98, 0x26, 0x82, 0x3f, 0xa1, 0xff, 0xa5, 0x3f, 0xb2, 0xec, 0x6e, 0x22, 0xed, 0xa1, 0x3d, 0x04,
	0xf6, 0xbd, 0x7c, 0xfb, 0x26, 0x79, 0x03, 0x8f, 0xfb, 0x8a, 0x8a, 0x6d, 0x46, 0x98, 0xe6, 0x58,
	0xa2, 0x7d, 0x52, 0x32, 0xe5, 0x59, 0xab, 0x2a, 0x2d, 0xcc, 0xa1, 0xae, 0xb2, 0xa2, 0xbe, 0x1c,
	0x38, 0x55, 0xa6, 0x36, 0x6c, 0xda, 0x91, 0xbc, 0x25, 0x79, 0x07, 0xcc, 0xee, 0xf6, 0xc6, 0xec,
	0x4b, 0x95, 0x3a, 0x30, 0x6f, 0x76, 0xa9, 0xd2, 0x54, 0x9f, 0xfd, 0xbd, 0xc5, 0x67, 0x00, 0xe3,
	0xb5, 0x94, 0x9b, 0x16, 0x16, 0xea, 0xc8, 0x9e, 0x21, 0x2a, 0x8c, 0xd6, 0xe6, 0x90, 0x04, 0xf3,
	0x60, 0x39, 0x5a, 0xdd, 0xf3, 0x3f, 0xb3, 0xf9, 0xc6, 0x81, 0x42, 0x1d, 0x45, 0x7b, 0x87, 0x5d,
	0x43, 0x5f, 0xa3, 0x4c, 0x7a, 0xf3, 0x60, 0xd9, 0x17, 0xf6, 0xc8, 0x6e, 0x21, 0x6a, 0x68, 0x6b,
	0xcd, 0xbe, 0x33, 0xc3, 0x86, 0x5e, 0x51, 0x5a, 0x30, 0x43, 0x99, 0x5c, 0x79, 0x30, 0x43, 0xb9,
	0xf8, 0x0a, 0x20, 0xbe, 0x04, 0xb2, 0x19, 0x0c, 0xa9, 0xcc, 0xea, 0x9d, 0xa9, 0xb4, 0xfb, 0x90,
	0x58, 0x5c, 0x34, 0xbb, 0x81, 0x30, 0x6f, 0xb0, 0xf4, 0x63, 0x42, 0xe1, 0x85, 0x77, 0x4f, 0xed,
	0x9c, 0x58, 0x78, 0xc1, 0xa6, 0x30, 0xd4, 0x26, 0xc7, 0x6d, 0x46, 0xe4, 0x86, 0xc5, 0x62, 0x60,
	0xf5, 0x9a, 0x88, 0x4d, 0x20, 0x92, 0xea, 0x84, 0x85, 0x4a, 0x42, 0xf7, 0xa2, 0x55, 0x6c, 0x0c,
	0x3d, 0xa4, 0x24, 0x72, 0x5e, 0x0f, 0xc9, 0x06, 0x7f, 0x90, 0xfd, 0x81, 0x81, 0x0f, 0x76, 0x62,
	0xf5, 0x0e, 0xc3, 0xae, 0x36, 0xf6, 0x06, 0xa3, 0x1f, 0x2d, 0xb2, 0x87, 0x7f, 0x2a, 0xfb, 0xdd,
	0xf6, 0x6c, 0xc2, 0xfd, 0x7a, 0x78, 0xb7, 0x1e, 0xfe, 0x62, 0xd7, 0x93, 0x47, 0x4e, 0x3f, 0x7d,
	0x07, 0x00, 0x00, 0xff, 0xff, 0xad, 0xfc, 0xcd, 0xd9, 0x0c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContractClient is the client API for Contract service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContractClient interface {
	//
	AddContract(ctx context.Context, in *AddContractReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type contractClient struct {
	cc *grpc.ClientConn
}

func NewContractClient(cc *grpc.ClientConn) ContractClient {
	return &contractClient{cc}
}

func (c *contractClient) AddContract(ctx context.Context, in *AddContractReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/bilibili.polymer.contract.Contract/AddContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContractServer is the server API for Contract service.
type ContractServer interface {
	//
	AddContract(context.Context, *AddContractReq) (*emptypb.Empty, error)
}

// UnimplementedContractServer can be embedded to have forward compatible implementations.
type UnimplementedContractServer struct {
}

func (*UnimplementedContractServer) AddContract(ctx context.Context, req *AddContractReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddContract not implemented")
}

func RegisterContractServer(s *grpc.Server, srv ContractServer) {
	s.RegisterService(&_Contract_serviceDesc, srv)
}

func _Contract_AddContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddContractReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServer).AddContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bilibili.polymer.contract.Contract/AddContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServer).AddContract(ctx, req.(*AddContractReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Contract_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bilibili.polymer.contract.Contract",
	HandlerType: (*ContractServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddContract",
			Handler:    _Contract_AddContract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_api/bilibili/polymer/contract/contract.proto",
}
