// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_api/bilibili/broadcast/message/im/notify.proto

package bilibili_broadcast_message_im

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
type PLType int32

const (
	//
	PLType_EN_PAYLOAD_NORMAL PLType = 0
	//
	PLType_EN_PAYLOAD_BASE64 PLType = 1
)

var PLType_name = map[int32]string{
	0: "EN_PAYLOAD_NORMAL",
	1: "EN_PAYLOAD_BASE64",
}

var PLType_value = map[string]int32{
	"EN_PAYLOAD_NORMAL": 0,
	"EN_PAYLOAD_BASE64": 1,
}

func (x PLType) String() string {
	return proto.EnumName(PLType_name, int32(x))
}

func (PLType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ac0b8777e22b375e, []int{0}
}

//
type CmdId int32

const (
	// 非法cmd
	CmdId_EN_CMD_ID_INVALID CmdId = 0
	// 服务端主动发起
	CmdId_EN_CMD_ID_MSG_NOTIFY CmdId = 1
	//
	CmdId_EN_CMD_ID_KICK_OUT CmdId = 2
)

var CmdId_name = map[int32]string{
	0: "EN_CMD_ID_INVALID",
	1: "EN_CMD_ID_MSG_NOTIFY",
	2: "EN_CMD_ID_KICK_OUT",
}

var CmdId_value = map[string]int32{
	"EN_CMD_ID_INVALID":    0,
	"EN_CMD_ID_MSG_NOTIFY": 1,
	"EN_CMD_ID_KICK_OUT":   2,
}

func (x CmdId) String() string {
	return proto.EnumName(CmdId_name, int32(x))
}

func (CmdId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ac0b8777e22b375e, []int{1}
}

//
type NotifyRsp struct {
	//
	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// 命令id
	Cmd uint64 `protobuf:"varint,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	//
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	//
	PayloadType          PLType   `protobuf:"varint,4,opt,name=payload_type,json=payloadType,proto3,enum=bilibili.broadcast.message.im.PLType" json:"payload_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyRsp) Reset()         { *m = NotifyRsp{} }
func (m *NotifyRsp) String() string { return proto.CompactTextString(m) }
func (*NotifyRsp) ProtoMessage()    {}
func (*NotifyRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac0b8777e22b375e, []int{0}
}

func (m *NotifyRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyRsp.Unmarshal(m, b)
}
func (m *NotifyRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyRsp.Marshal(b, m, deterministic)
}
func (m *NotifyRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyRsp.Merge(m, src)
}
func (m *NotifyRsp) XXX_Size() int {
	return xxx_messageInfo_NotifyRsp.Size(m)
}
func (m *NotifyRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyRsp.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyRsp proto.InternalMessageInfo

func (m *NotifyRsp) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *NotifyRsp) GetCmd() uint64 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *NotifyRsp) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *NotifyRsp) GetPayloadType() PLType {
	if m != nil {
		return m.PayloadType
	}
	return PLType_EN_PAYLOAD_NORMAL
}

//
type Msg struct {
	// 发送方uid
	SenderUid uint64 `protobuf:"varint,1,opt,name=sender_uid,json=senderUid,proto3" json:"sender_uid,omitempty"`
	// 接收方类型
	ReceiverType int32 `protobuf:"varint,2,opt,name=receiver_type,json=receiverType,proto3" json:"receiver_type,omitempty"`
	// 接收方id
	ReceiverId uint64 `protobuf:"varint,3,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	// 客户端的序列id 用于服务端去重
	CliMsgId uint64 `protobuf:"varint,4,opt,name=cli_msg_id,json=cliMsgId,proto3" json:"cli_msg_id,omitempty"`
	// 消息类型
	MsgType int32 `protobuf:"varint,5,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	// 消息内容
	Content string `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	// 服务端的序列号
	MsgSeqno uint64 `protobuf:"varint,7,opt,name=msg_seqno,json=msgSeqno,proto3" json:"msg_seqno,omitempty"`
	// 消息发送时间（服务端时间）
	Timestamp uint64 `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// at用户列表
	AtUids []uint64 `protobuf:"varint,9,rep,packed,name=at_uids,json=atUids,proto3" json:"at_uids,omitempty"`
	// 多人消息
	RecverIds []uint64 `protobuf:"varint,10,rep,packed,name=recver_ids,json=recverIds,proto3" json:"recver_ids,omitempty"`
	// 消息唯一标示
	MsgKey uint64 `protobuf:"varint,11,opt,name=msg_key,json=msgKey,proto3" json:"msg_key,omitempty"`
	// 消息状态
	MsgStatus uint32 `protobuf:"varint,12,opt,name=msg_status,json=msgStatus,proto3" json:"msg_status,omitempty"`
	// 是否为系统撤销
	SysCancel bool `protobuf:"varint,13,opt,name=sys_cancel,json=sysCancel,proto3" json:"sys_cancel,omitempty"`
	// 是否是多聊消息 目前群通知管理员的部分通知属于该类消息
	IsMultiChat uint32 `protobuf:"varint,14,opt,name=is_multi_chat,json=isMultiChat,proto3" json:"is_multi_chat,omitempty"`
	// 表示撤回的消息的session_seqno 用以后续的比较 实现未读数的正确显示
	WithdrawSeqno uint64 `protobuf:"varint,15,opt,name=withdraw_seqno,json=withdrawSeqno,proto3" json:"withdraw_seqno,omitempty"`
	// 通知码
	NotifyCode string `protobuf:"bytes,16,opt,name=notify_code,json=notifyCode,proto3" json:"notify_code,omitempty"`
	// 消息来源
	MsgSource            uint32   `protobuf:"varint,17,opt,name=msg_source,json=msgSource,proto3" json:"msg_source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac0b8777e22b375e, []int{1}
}

func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (m *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(m, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetSenderUid() uint64 {
	if m != nil {
		return m.SenderUid
	}
	return 0
}

func (m *Msg) GetReceiverType() int32 {
	if m != nil {
		return m.ReceiverType
	}
	return 0
}

func (m *Msg) GetReceiverId() uint64 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *Msg) GetCliMsgId() uint64 {
	if m != nil {
		return m.CliMsgId
	}
	return 0
}

func (m *Msg) GetMsgType() int32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *Msg) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Msg) GetMsgSeqno() uint64 {
	if m != nil {
		return m.MsgSeqno
	}
	return 0
}

func (m *Msg) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Msg) GetAtUids() []uint64 {
	if m != nil {
		return m.AtUids
	}
	return nil
}

func (m *Msg) GetRecverIds() []uint64 {
	if m != nil {
		return m.RecverIds
	}
	return nil
}

func (m *Msg) GetMsgKey() uint64 {
	if m != nil {
		return m.MsgKey
	}
	return 0
}

func (m *Msg) GetMsgStatus() uint32 {
	if m != nil {
		return m.MsgStatus
	}
	return 0
}

func (m *Msg) GetSysCancel() bool {
	if m != nil {
		return m.SysCancel
	}
	return false
}

func (m *Msg) GetIsMultiChat() uint32 {
	if m != nil {
		return m.IsMultiChat
	}
	return 0
}

func (m *Msg) GetWithdrawSeqno() uint64 {
	if m != nil {
		return m.WithdrawSeqno
	}
	return 0
}

func (m *Msg) GetNotifyCode() string {
	if m != nil {
		return m.NotifyCode
	}
	return ""
}

func (m *Msg) GetMsgSource() uint32 {
	if m != nil {
		return m.MsgSource
	}
	return 0
}

//
type NotifyInfo struct {
	//
	MsgType uint32 `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	//
	TalkerId uint64 `protobuf:"varint,2,opt,name=talker_id,json=talkerId,proto3" json:"talker_id,omitempty"`
	//
	SessionType          uint32   `protobuf:"varint,3,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyInfo) Reset()         { *m = NotifyInfo{} }
func (m *NotifyInfo) String() string { return proto.CompactTextString(m) }
func (*NotifyInfo) ProtoMessage()    {}
func (*NotifyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac0b8777e22b375e, []int{2}
}

func (m *NotifyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyInfo.Unmarshal(m, b)
}
func (m *NotifyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyInfo.Marshal(b, m, deterministic)
}
func (m *NotifyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyInfo.Merge(m, src)
}
func (m *NotifyInfo) XXX_Size() int {
	return xxx_messageInfo_NotifyInfo.Size(m)
}
func (m *NotifyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyInfo proto.InternalMessageInfo

func (m *NotifyInfo) GetMsgType() uint32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *NotifyInfo) GetTalkerId() uint64 {
	if m != nil {
		return m.TalkerId
	}
	return 0
}

func (m *NotifyInfo) GetSessionType() uint32 {
	if m != nil {
		return m.SessionType
	}
	return 0
}

//
type ReqServerNotify struct {
	// 最新序列号
	LastestSeqno uint64 `protobuf:"varint,1,opt,name=lastest_seqno,json=lastestSeqno,proto3" json:"lastest_seqno,omitempty"`
	// 即时消息 该类消息主要用于系统通知 当客户端sync msg时 不会sync到此类消息
	InstantMsg *Msg `protobuf:"bytes,2,opt,name=instant_msg,json=instantMsg,proto3" json:"instant_msg,omitempty"`
	//
	NotifyInfo           *NotifyInfo `protobuf:"bytes,3,opt,name=notify_info,json=notifyInfo,proto3" json:"notify_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReqServerNotify) Reset()         { *m = ReqServerNotify{} }
func (m *ReqServerNotify) String() string { return proto.CompactTextString(m) }
func (*ReqServerNotify) ProtoMessage()    {}
func (*ReqServerNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_ac0b8777e22b375e, []int{3}
}

func (m *ReqServerNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqServerNotify.Unmarshal(m, b)
}
func (m *ReqServerNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqServerNotify.Marshal(b, m, deterministic)
}
func (m *ReqServerNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqServerNotify.Merge(m, src)
}
func (m *ReqServerNotify) XXX_Size() int {
	return xxx_messageInfo_ReqServerNotify.Size(m)
}
func (m *ReqServerNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqServerNotify.DiscardUnknown(m)
}

var xxx_messageInfo_ReqServerNotify proto.InternalMessageInfo

func (m *ReqServerNotify) GetLastestSeqno() uint64 {
	if m != nil {
		return m.LastestSeqno
	}
	return 0
}

func (m *ReqServerNotify) GetInstantMsg() *Msg {
	if m != nil {
		return m.InstantMsg
	}
	return nil
}

func (m *ReqServerNotify) GetNotifyInfo() *NotifyInfo {
	if m != nil {
		return m.NotifyInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("bilibili.broadcast.message.im.PLType", PLType_name, PLType_value)
	proto.RegisterEnum("bilibili.broadcast.message.im.CmdId", CmdId_name, CmdId_value)
	proto.RegisterType((*NotifyRsp)(nil), "bilibili.broadcast.message.im.NotifyRsp")
	proto.RegisterType((*Msg)(nil), "bilibili.broadcast.message.im.Msg")
	proto.RegisterType((*NotifyInfo)(nil), "bilibili.broadcast.message.im.NotifyInfo")
	proto.RegisterType((*ReqServerNotify)(nil), "bilibili.broadcast.message.im.ReqServerNotify")
}

func init() {
	proto.RegisterFile("grpc_api/bilibili/broadcast/message/im/notify.proto", fileDescriptor_ac0b8777e22b375e)
}

var fileDescriptor_ac0b8777e22b375e = []byte{
	// 752 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0xc7, 0xeb, 0x26, 0x9b, 0xc4, 0xc7, 0xc9, 0x36, 0x1d, 0x41, 0x19, 0xba, 0xad, 0x1a, 0x82,
	0x2a, 0x99, 0x5e, 0x38, 0x28, 0x45, 0xbd, 0x0f, 0xc9, 0x02, 0x66, 0xf3, 0xb1, 0x38, 0xbb, 0xa0,
	0x8a, 0x0b, 0x6b, 0xe2, 0x99, 0x38, 0xa3, 0xfa, 0xab, 0x9e, 0x49, 0x2b, 0xbf, 0x06, 0x3c, 0x14,
	0xaf, 0x85, 0x66, 0xc6, 0x4e, 0x04, 0x17, 0x94, 0x8b, 0x48, 0x3e, 0xbf, 0xf3, 0x31, 0xff, 0x73,
	0xe6, 0x64, 0xe0, 0x75, 0x5c, 0x16, 0x51, 0x48, 0x0a, 0x3e, 0xd9, 0xf1, 0x84, 0xab, 0xdf, 0x64,
	0x57, 0xe6, 0x84, 0x46, 0x44, 0xc8, 0x49, 0xca, 0x84, 0x20, 0x31, 0x9b, 0xf0, 0x74, 0x92, 0xe5,
	0x92, 0xef, 0x2b, 0xaf, 0x28, 0x73, 0x99, 0xa3, 0xe7, 0x4d, 0xac, 0x77, 0x8a, 0xf5, 0xea, 0x58,
	0x8f, 0xa7, 0x4f, 0xaf, 0xe2, 0x3c, 0x8f, 0x13, 0x36, 0xd1, 0xc1, 0xbb, 0xe3, 0x7e, 0xc2, 0xd2,
	0x42, 0xd6, 0xb9, 0xe3, 0x3f, 0x2d, 0xb0, 0xd7, 0xba, 0x58, 0x20, 0x0a, 0x34, 0x84, 0xd6, 0x91,
	0x53, 0x6c, 0x8d, 0x2c, 0xb7, 0x1d, 0xa8, 0x4f, 0x45, 0xa2, 0x94, 0xe2, 0x87, 0x86, 0x44, 0x29,
	0x45, 0x18, 0xba, 0x05, 0xa9, 0x92, 0x9c, 0x50, 0xdc, 0x1a, 0x59, 0x6e, 0x3f, 0x68, 0x4c, 0xf4,
	0x13, 0xf4, 0xeb, 0xcf, 0x50, 0x56, 0x05, 0xc3, 0xed, 0x91, 0xe5, 0x5e, 0x4e, 0x5f, 0x7a, 0xff,
	0x29, 0xcf, 0xbb, 0x5d, 0xde, 0x55, 0x05, 0x0b, 0x9c, 0x3a, 0x55, 0x19, 0xe3, 0x3f, 0xda, 0xd0,
	0x5a, 0x89, 0x18, 0x3d, 0x07, 0x10, 0x2c, 0xa3, 0xac, 0x0c, 0xcf, 0xb2, 0x6c, 0x43, 0xee, 0x39,
	0x45, 0x5f, 0xc3, 0xa0, 0x64, 0x11, 0xe3, 0x1f, 0x58, 0x69, 0x4e, 0x54, 0x32, 0x2f, 0x82, 0x7e,
	0x03, 0x55, 0x2d, 0xf4, 0x02, 0x9c, 0x53, 0x10, 0x37, 0x9a, 0xdb, 0x01, 0x34, 0xc8, 0xa7, 0xe8,
	0x19, 0x40, 0x94, 0xf0, 0x30, 0x15, 0xb1, 0xf2, 0xb7, 0xb5, 0xbf, 0x17, 0x25, 0x7c, 0x25, 0x62,
	0x9f, 0xa2, 0x2f, 0xa1, 0xa7, 0x3c, 0xba, 0xfc, 0x85, 0x2e, 0xdf, 0x4d, 0x45, 0xac, 0x2b, 0x63,
	0xe8, 0x46, 0x79, 0x26, 0x59, 0x26, 0x71, 0x67, 0x64, 0xb9, 0x76, 0xd0, 0x98, 0xe8, 0x0a, 0x6c,
	0x95, 0x24, 0xd8, 0xfb, 0x2c, 0xc7, 0x5d, 0x53, 0x31, 0x15, 0xf1, 0x56, 0xd9, 0xe8, 0x19, 0xd8,
	0x92, 0xa7, 0x4c, 0x48, 0x92, 0x16, 0xb8, 0x67, 0x7a, 0x3a, 0x01, 0xf4, 0x05, 0x74, 0x89, 0x54,
	0xed, 0x0a, 0x6c, 0x8f, 0x5a, 0x6e, 0x3b, 0xe8, 0x10, 0x79, 0xcf, 0xa9, 0x50, 0xb3, 0x28, 0x59,
	0x64, 0xba, 0x10, 0x18, 0xb4, 0xcf, 0x36, 0xc4, 0xa7, 0x42, 0xe5, 0xa9, 0x23, 0xdf, 0xb1, 0x0a,
	0x3b, 0xba, 0x66, 0x27, 0x15, 0xf1, 0x0d, 0xab, 0x54, 0x9e, 0xd6, 0x22, 0x89, 0x3c, 0x0a, 0xdc,
	0x1f, 0x59, 0xee, 0x20, 0x50, 0xea, 0xb6, 0x1a, 0xe8, 0x11, 0x57, 0x22, 0x8c, 0x48, 0x16, 0xb1,
	0x04, 0x0f, 0x46, 0x96, 0xdb, 0x0b, 0x6c, 0x51, 0x89, 0xb9, 0x06, 0x68, 0x0c, 0x03, 0x2e, 0xc2,
	0xf4, 0x98, 0x48, 0x1e, 0x46, 0x07, 0x22, 0xf1, 0xa5, 0x2e, 0xe0, 0x70, 0xb1, 0x52, 0x6c, 0x7e,
	0x20, 0x12, 0xbd, 0x84, 0xcb, 0x8f, 0x5c, 0x1e, 0x68, 0x49, 0x3e, 0xd6, 0x2d, 0x3f, 0xd2, 0x0a,
	0x06, 0x0d, 0x35, 0x7d, 0xbf, 0x00, 0xc7, 0xac, 0x6d, 0x18, 0xe5, 0x94, 0xe1, 0xa1, 0x1e, 0x19,
	0x18, 0x34, 0xcf, 0x29, 0x3b, 0x29, 0xcd, 0x8f, 0x65, 0xc4, 0xf0, 0xe3, 0xb3, 0x52, 0x0d, 0xc6,
	0x31, 0x80, 0xd9, 0x54, 0x3f, 0xdb, 0xe7, 0xff, 0xb8, 0x17, 0x4b, 0x87, 0x9e, 0xee, 0xe5, 0x0a,
	0x6c, 0x49, 0x92, 0x77, 0xe6, 0xbe, 0xcd, 0xe6, 0xf6, 0x0c, 0xf0, 0x29, 0xfa, 0x0a, 0xfa, 0x82,
	0x09, 0xc1, 0xf3, 0xcc, 0xe4, 0xb6, 0x4c, 0x3f, 0x35, 0xd3, 0xdb, 0xf7, 0x97, 0x05, 0x8f, 0x02,
	0xf6, 0x7e, 0xcb, 0xca, 0x0f, 0xac, 0x34, 0x47, 0xaa, 0x55, 0x4b, 0x88, 0x90, 0x4c, 0xc8, 0xba,
	0x45, 0xb3, 0x8c, 0xfd, 0x1a, 0x9a, 0x0e, 0xe7, 0xe0, 0xf0, 0x4c, 0x48, 0x92, 0x49, 0xb5, 0x4d,
	0xfa, 0x68, 0x67, 0x3a, 0xfe, 0xc4, 0xfe, 0xaf, 0x44, 0x1c, 0x40, 0x9d, 0xa6, 0x76, 0xfe, 0xe7,
	0xd3, 0x98, 0x78, 0xb6, 0xcf, 0xb5, 0x3e, 0x67, 0xfa, 0xcd, 0x27, 0x8a, 0x9c, 0x07, 0xd3, 0x4c,
	0x54, 0x7d, 0xbf, 0x7a, 0x03, 0x1d, 0xf3, 0xf7, 0x42, 0x9f, 0xc3, 0xe3, 0xeb, 0x75, 0x78, 0x3b,
	0x7b, 0xbb, 0xdc, 0xcc, 0x16, 0xe1, 0x7a, 0x13, 0xac, 0x66, 0xcb, 0xe1, 0x83, 0x7f, 0xe1, 0xef,
	0x67, 0xdb, 0xeb, 0x37, 0xdf, 0x0d, 0xad, 0x57, 0xb7, 0x70, 0x31, 0x4f, 0xa9, 0x4f, 0x6b, 0xff,
	0x7c, 0xb5, 0x08, 0xfd, 0x45, 0xe8, 0xaf, 0x7f, 0x9d, 0x2d, 0xfd, 0xc5, 0xf0, 0x01, 0xc2, 0xf0,
	0xd9, 0x19, 0xaf, 0xb6, 0x3f, 0x86, 0xeb, 0xcd, 0x9d, 0xff, 0xc3, 0xdb, 0xa1, 0x85, 0x9e, 0x00,
	0x3a, 0x7b, 0x6e, 0xfc, 0xf9, 0x4d, 0xb8, 0xb9, 0xbf, 0x1b, 0x3e, 0x9c, 0xfe, 0x0e, 0x9d, 0x7a,
	0x92, 0xbf, 0x80, 0xf3, 0x1b, 0x91, 0xd1, 0xa1, 0x36, 0x9f, 0x78, 0xe6, 0x79, 0xf2, 0x9a, 0xe7,
	0xc9, 0xbb, 0x56, 0xcf, 0xd3, 0x53, 0xf7, 0x7f, 0x75, 0x1c, 0x88, 0xe2, 0x5b, 0x6b, 0xd7, 0xd1,
	0xb9, 0xaf, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x99, 0x43, 0xf9, 0x3e, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NotifyClient is the client API for Notify service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotifyClient interface {
	//
	WatchNotify(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Notify_WatchNotifyClient, error)
}

type notifyClient struct {
	cc *grpc.ClientConn
}

func NewNotifyClient(cc *grpc.ClientConn) NotifyClient {
	return &notifyClient{cc}
}

func (c *notifyClient) WatchNotify(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Notify_WatchNotifyClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Notify_serviceDesc.Streams[0], "/bilibili.broadcast.message.im.Notify/WatchNotify", opts...)
	if err != nil {
		return nil, err
	}
	x := &notifyWatchNotifyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Notify_WatchNotifyClient interface {
	Recv() (*NotifyRsp, error)
	grpc.ClientStream
}

type notifyWatchNotifyClient struct {
	grpc.ClientStream
}

func (x *notifyWatchNotifyClient) Recv() (*NotifyRsp, error) {
	m := new(NotifyRsp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NotifyServer is the server API for Notify service.
type NotifyServer interface {
	//
	WatchNotify(*emptypb.Empty, Notify_WatchNotifyServer) error
}

// UnimplementedNotifyServer can be embedded to have forward compatible implementations.
type UnimplementedNotifyServer struct {
}

func (*UnimplementedNotifyServer) WatchNotify(req *emptypb.Empty, srv Notify_WatchNotifyServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchNotify not implemented")
}

func RegisterNotifyServer(s *grpc.Server, srv NotifyServer) {
	s.RegisterService(&_Notify_serviceDesc, srv)
}

func _Notify_WatchNotify_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NotifyServer).WatchNotify(m, &notifyWatchNotifyServer{stream})
}

type Notify_WatchNotifyServer interface {
	Send(*NotifyRsp) error
	grpc.ServerStream
}

type notifyWatchNotifyServer struct {
	grpc.ServerStream
}

func (x *notifyWatchNotifyServer) Send(m *NotifyRsp) error {
	return x.ServerStream.SendMsg(m)
}

var _Notify_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bilibili.broadcast.message.im.Notify",
	HandlerType: (*NotifyServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchNotify",
			Handler:       _Notify_WatchNotify_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc_api/bilibili/broadcast/message/im/notify.proto",
}
