// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_api/bilibili/metadata/parabox/pararbox.proto

package bilibili_metadata_parabox

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
type Exp struct {
	//
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	//
	Bucket               int32    `protobuf:"varint,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Exp) Reset()         { *m = Exp{} }
func (m *Exp) String() string { return proto.CompactTextString(m) }
func (*Exp) ProtoMessage()    {}
func (*Exp) Descriptor() ([]byte, []int) {
	return fileDescriptor_06976fbca015c311, []int{0}
}

func (m *Exp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exp.Unmarshal(m, b)
}
func (m *Exp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exp.Marshal(b, m, deterministic)
}
func (m *Exp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exp.Merge(m, src)
}
func (m *Exp) XXX_Size() int {
	return xxx_messageInfo_Exp.Size(m)
}
func (m *Exp) XXX_DiscardUnknown() {
	xxx_messageInfo_Exp.DiscardUnknown(m)
}

var xxx_messageInfo_Exp proto.InternalMessageInfo

func (m *Exp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Exp) GetBucket() int32 {
	if m != nil {
		return m.Bucket
	}
	return 0
}

//
type Exps struct {
	//
	Exps                 []*Exp   `protobuf:"bytes,1,rep,name=exps,proto3" json:"exps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Exps) Reset()         { *m = Exps{} }
func (m *Exps) String() string { return proto.CompactTextString(m) }
func (*Exps) ProtoMessage()    {}
func (*Exps) Descriptor() ([]byte, []int) {
	return fileDescriptor_06976fbca015c311, []int{1}
}

func (m *Exps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Exps.Unmarshal(m, b)
}
func (m *Exps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Exps.Marshal(b, m, deterministic)
}
func (m *Exps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Exps.Merge(m, src)
}
func (m *Exps) XXX_Size() int {
	return xxx_messageInfo_Exps.Size(m)
}
func (m *Exps) XXX_DiscardUnknown() {
	xxx_messageInfo_Exps.DiscardUnknown(m)
}

var xxx_messageInfo_Exps proto.InternalMessageInfo

func (m *Exps) GetExps() []*Exp {
	if m != nil {
		return m.Exps
	}
	return nil
}

func init() {
	proto.RegisterType((*Exp)(nil), "bilibili.metadata.parabox.Exp")
	proto.RegisterType((*Exps)(nil), "bilibili.metadata.parabox.Exps")
}

func init() {
	proto.RegisterFile("grpc_api/bilibili/metadata/parabox/pararbox.proto", fileDescriptor_06976fbca015c311)
}

var fileDescriptor_06976fbca015c311 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4c, 0x2f, 0x2a, 0x48,
	0x8e, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xca, 0xcc, 0xc9, 0x04, 0x61, 0xfd, 0xdc, 0xd4, 0x92, 0xc4,
	0x94, 0xc4, 0x92, 0x44, 0xfd, 0x82, 0xc4, 0xa2, 0xc4, 0xa4, 0xfc, 0x0a, 0x30, 0x5d, 0x94, 0x94,
	0x5f, 0xa1, 0x57, 0x50, 0x94, 0x5f, 0x92, 0x2f, 0x24, 0x09, 0x53, 0xa9, 0x07, 0x53, 0xa9, 0x07,
	0x55, 0xa9, 0xa4, 0xcb, 0xc5, 0xec, 0x5a, 0x51, 0x20, 0xc4, 0xc7, 0xc5, 0x94, 0x99, 0x22, 0xc1,
	0xa8, 0xc0, 0xa8, 0xc1, 0x1c, 0xc4, 0x94, 0x99, 0x22, 0x24, 0xc6, 0xc5, 0x96, 0x54, 0x9a, 0x9c,
	0x9d, 0x5a, 0x22, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0xe5, 0x29, 0x59, 0x71, 0xb1, 0xb8,
	0x56, 0x14, 0x14, 0x0b, 0x19, 0x71, 0xb1, 0xa4, 0x56, 0x14, 0x14, 0x4b, 0x30, 0x2a, 0x30, 0x6b,
	0x70, 0x1b, 0xc9, 0xe9, 0xe1, 0xb4, 0x40, 0xcf, 0xb5, 0xa2, 0x20, 0x08, 0xac, 0x36, 0x89, 0x0d,
	0xec, 0x18, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x99, 0x28, 0x54, 0x75, 0xc1, 0x00, 0x00,
	0x00,
}
