// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_api/bilibili/live/app/room/v1/room.proto

package bilibili_live_app_room_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
type GetStudioListReq struct {
	//
	RoomId               int64    `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStudioListReq) Reset()         { *m = GetStudioListReq{} }
func (m *GetStudioListReq) String() string { return proto.CompactTextString(m) }
func (*GetStudioListReq) ProtoMessage()    {}
func (*GetStudioListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d17727d0273f9c28, []int{0}
}

func (m *GetStudioListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStudioListReq.Unmarshal(m, b)
}
func (m *GetStudioListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStudioListReq.Marshal(b, m, deterministic)
}
func (m *GetStudioListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudioListReq.Merge(m, src)
}
func (m *GetStudioListReq) XXX_Size() int {
	return xxx_messageInfo_GetStudioListReq.Size(m)
}
func (m *GetStudioListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudioListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudioListReq proto.InternalMessageInfo

func (m *GetStudioListReq) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

//
type GetStudioListResp struct {
	//
	Status int64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	//
	MasterList           []*GetStudioListResp_StudioMaster `protobuf:"bytes,2,rep,name=master_list,json=masterList,proto3" json:"master_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *GetStudioListResp) Reset()         { *m = GetStudioListResp{} }
func (m *GetStudioListResp) String() string { return proto.CompactTextString(m) }
func (*GetStudioListResp) ProtoMessage()    {}
func (*GetStudioListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_d17727d0273f9c28, []int{1}
}

func (m *GetStudioListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStudioListResp.Unmarshal(m, b)
}
func (m *GetStudioListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStudioListResp.Marshal(b, m, deterministic)
}
func (m *GetStudioListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudioListResp.Merge(m, src)
}
func (m *GetStudioListResp) XXX_Size() int {
	return xxx_messageInfo_GetStudioListResp.Size(m)
}
func (m *GetStudioListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudioListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudioListResp proto.InternalMessageInfo

func (m *GetStudioListResp) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetStudioListResp) GetMasterList() []*GetStudioListResp_StudioMaster {
	if m != nil {
		return m.MasterList
	}
	return nil
}

//
type GetStudioListResp_Pendants struct {
	//
	Frame *GetStudioListResp_Pendant `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"`
	//
	Badge                *GetStudioListResp_Pendant `protobuf:"bytes,2,opt,name=badge,proto3" json:"badge,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *GetStudioListResp_Pendants) Reset()         { *m = GetStudioListResp_Pendants{} }
func (m *GetStudioListResp_Pendants) String() string { return proto.CompactTextString(m) }
func (*GetStudioListResp_Pendants) ProtoMessage()    {}
func (*GetStudioListResp_Pendants) Descriptor() ([]byte, []int) {
	return fileDescriptor_d17727d0273f9c28, []int{1, 0}
}

func (m *GetStudioListResp_Pendants) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStudioListResp_Pendants.Unmarshal(m, b)
}
func (m *GetStudioListResp_Pendants) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStudioListResp_Pendants.Marshal(b, m, deterministic)
}
func (m *GetStudioListResp_Pendants) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudioListResp_Pendants.Merge(m, src)
}
func (m *GetStudioListResp_Pendants) XXX_Size() int {
	return xxx_messageInfo_GetStudioListResp_Pendants.Size(m)
}
func (m *GetStudioListResp_Pendants) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudioListResp_Pendants.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudioListResp_Pendants proto.InternalMessageInfo

func (m *GetStudioListResp_Pendants) GetFrame() *GetStudioListResp_Pendant {
	if m != nil {
		return m.Frame
	}
	return nil
}

func (m *GetStudioListResp_Pendants) GetBadge() *GetStudioListResp_Pendant {
	if m != nil {
		return m.Badge
	}
	return nil
}

//
type GetStudioListResp_Pendant struct {
	//
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//
	Position int64 `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	//
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	//
	Desc                 string   `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStudioListResp_Pendant) Reset()         { *m = GetStudioListResp_Pendant{} }
func (m *GetStudioListResp_Pendant) String() string { return proto.CompactTextString(m) }
func (*GetStudioListResp_Pendant) ProtoMessage()    {}
func (*GetStudioListResp_Pendant) Descriptor() ([]byte, []int) {
	return fileDescriptor_d17727d0273f9c28, []int{1, 1}
}

func (m *GetStudioListResp_Pendant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStudioListResp_Pendant.Unmarshal(m, b)
}
func (m *GetStudioListResp_Pendant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStudioListResp_Pendant.Marshal(b, m, deterministic)
}
func (m *GetStudioListResp_Pendant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudioListResp_Pendant.Merge(m, src)
}
func (m *GetStudioListResp_Pendant) XXX_Size() int {
	return xxx_messageInfo_GetStudioListResp_Pendant.Size(m)
}
func (m *GetStudioListResp_Pendant) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudioListResp_Pendant.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudioListResp_Pendant proto.InternalMessageInfo

func (m *GetStudioListResp_Pendant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetStudioListResp_Pendant) GetPosition() int64 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *GetStudioListResp_Pendant) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *GetStudioListResp_Pendant) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

//
type GetStudioListResp_StudioMaster struct {
	//
	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	//
	RoomId int64 `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	//
	Uname string `protobuf:"bytes,3,opt,name=uname,proto3" json:"uname,omitempty"`
	//
	Face string `protobuf:"bytes,4,opt,name=face,proto3" json:"face,omitempty"`
	//
	Pendants *GetStudioListResp_Pendants `protobuf:"bytes,5,opt,name=pendants,proto3" json:"pendants,omitempty"`
	//
	Tag string `protobuf:"bytes,6,opt,name=tag,proto3" json:"tag,omitempty"`
	//
	TagType              int64    `protobuf:"varint,7,opt,name=tag_type,json=tagType,proto3" json:"tag_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStudioListResp_StudioMaster) Reset()         { *m = GetStudioListResp_StudioMaster{} }
func (m *GetStudioListResp_StudioMaster) String() string { return proto.CompactTextString(m) }
func (*GetStudioListResp_StudioMaster) ProtoMessage()    {}
func (*GetStudioListResp_StudioMaster) Descriptor() ([]byte, []int) {
	return fileDescriptor_d17727d0273f9c28, []int{1, 2}
}

func (m *GetStudioListResp_StudioMaster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStudioListResp_StudioMaster.Unmarshal(m, b)
}
func (m *GetStudioListResp_StudioMaster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStudioListResp_StudioMaster.Marshal(b, m, deterministic)
}
func (m *GetStudioListResp_StudioMaster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudioListResp_StudioMaster.Merge(m, src)
}
func (m *GetStudioListResp_StudioMaster) XXX_Size() int {
	return xxx_messageInfo_GetStudioListResp_StudioMaster.Size(m)
}
func (m *GetStudioListResp_StudioMaster) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudioListResp_StudioMaster.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudioListResp_StudioMaster proto.InternalMessageInfo

func (m *GetStudioListResp_StudioMaster) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GetStudioListResp_StudioMaster) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *GetStudioListResp_StudioMaster) GetUname() string {
	if m != nil {
		return m.Uname
	}
	return ""
}

func (m *GetStudioListResp_StudioMaster) GetFace() string {
	if m != nil {
		return m.Face
	}
	return ""
}

func (m *GetStudioListResp_StudioMaster) GetPendants() *GetStudioListResp_Pendants {
	if m != nil {
		return m.Pendants
	}
	return nil
}

func (m *GetStudioListResp_StudioMaster) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *GetStudioListResp_StudioMaster) GetTagType() int64 {
	if m != nil {
		return m.TagType
	}
	return 0
}

func init() {
	proto.RegisterType((*GetStudioListReq)(nil), "bilibili.live.app.room.v1.GetStudioListReq")
	proto.RegisterType((*GetStudioListResp)(nil), "bilibili.live.app.room.v1.GetStudioListResp")
	proto.RegisterType((*GetStudioListResp_Pendants)(nil), "bilibili.live.app.room.v1.GetStudioListResp.Pendants")
	proto.RegisterType((*GetStudioListResp_Pendant)(nil), "bilibili.live.app.room.v1.GetStudioListResp.Pendant")
	proto.RegisterType((*GetStudioListResp_StudioMaster)(nil), "bilibili.live.app.room.v1.GetStudioListResp.StudioMaster")
}

func init() {
	proto.RegisterFile("grpc_api/bilibili/live/app/room/v1/room.proto", fileDescriptor_d17727d0273f9c28)
}

var fileDescriptor_d17727d0273f9c28 = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xc1, 0x4e, 0xab, 0x40,
	0x14, 0x86, 0x43, 0x69, 0x81, 0x7b, 0x7a, 0x17, 0xbd, 0x93, 0x9b, 0x7b, 0xa7, 0xac, 0x9a, 0xae,
	0x9a, 0x18, 0x21, 0xad, 0xba, 0xf0, 0x09, 0x8c, 0x46, 0x13, 0x45, 0x57, 0x6e, 0xc8, 0x14, 0xa6,
	0x64, 0x12, 0x0a, 0x23, 0x33, 0x90, 0xf4, 0x75, 0x7c, 0x35, 0x1f, 0xc2, 0xad, 0x99, 0x03, 0x34,
	0x8d, 0xc6, 0x85, 0xba, 0x68, 0x7a, 0x7e, 0xce, 0xe1, 0xfb, 0xff, 0x9c, 0x03, 0x1c, 0x67, 0x95,
	0x4c, 0x62, 0x26, 0x45, 0xb8, 0x16, 0xb9, 0x30, 0xbf, 0x30, 0x17, 0x0d, 0x0f, 0x99, 0x94, 0x61,
	0x55, 0x96, 0xdb, 0xb0, 0x59, 0xe2, 0x7f, 0x20, 0xab, 0x52, 0x97, 0x64, 0xda, 0x4f, 0x05, 0x66,
	0x2a, 0x60, 0x52, 0x06, 0xd8, 0x6d, 0x96, 0xf3, 0x23, 0x98, 0x5c, 0x70, 0x7d, 0xaf, 0xeb, 0x54,
	0x94, 0xd7, 0x42, 0xe9, 0x88, 0x3f, 0x91, 0xff, 0xe0, 0x9a, 0x76, 0x2c, 0x52, 0x6a, 0xcd, 0xac,
	0x85, 0x1d, 0x39, 0x46, 0x5e, 0xa6, 0xf3, 0xd7, 0x21, 0xfc, 0x79, 0x37, 0xad, 0x24, 0xf9, 0x07,
	0x8e, 0xd2, 0x4c, 0xd7, 0xaa, 0x9f, 0x6e, 0x15, 0x79, 0x84, 0xf1, 0x96, 0x29, 0xcd, 0xab, 0x38,
	0x17, 0x4a, 0xd3, 0xc1, 0xcc, 0x5e, 0x8c, 0x57, 0xe7, 0xc1, 0xa7, 0x59, 0x82, 0x0f, 0xe8, 0xa0,
	0x95, 0x37, 0x48, 0x89, 0xa0, 0xa5, 0x99, 0xa6, 0xff, 0x6c, 0x81, 0x77, 0xcb, 0x8b, 0x94, 0x15,
	0x5a, 0x91, 0x2b, 0x18, 0x6d, 0x2a, 0xb6, 0xe5, 0xe8, 0x3f, 0x5e, 0x9d, 0x7e, 0xc9, 0xa2, 0xa3,
	0x44, 0x2d, 0xc2, 0xb0, 0xd6, 0x2c, 0xcd, 0x38, 0x1d, 0xfc, 0x84, 0x85, 0x08, 0x3f, 0x01, 0xb7,
	0x7b, 0x42, 0x08, 0x0c, 0x8b, 0x3e, 0xe1, 0xaf, 0x08, 0x6b, 0xe2, 0x83, 0x27, 0x4b, 0x25, 0xb4,
	0x28, 0x0b, 0x74, 0xb3, 0xa3, 0xbd, 0x26, 0x7f, 0x61, 0xd4, 0xb0, 0xbc, 0xe6, 0xd4, 0xc6, 0x17,
	0x5a, 0x61, 0x28, 0x29, 0x57, 0x09, 0x1d, 0xb6, 0x14, 0x53, 0xfb, 0x2f, 0x16, 0xfc, 0x3e, 0x5c,
	0x13, 0x99, 0x80, 0x5d, 0xef, 0x2f, 0x67, 0xca, 0xc3, 0x7b, 0x0e, 0x0e, 0xef, 0x69, 0x5c, 0x6a,
	0x8c, 0xd5, 0xb9, 0xa0, 0x30, 0x2e, 0x1b, 0x96, 0xf0, 0xde, 0xc5, 0xd4, 0xe4, 0x0e, 0x3c, 0xd9,
	0xad, 0x9b, 0x8e, 0x70, 0x33, 0x67, 0xdf, 0xd9, 0x8c, 0x8a, 0xf6, 0x18, 0x93, 0x53, 0xb3, 0x8c,
	0x3a, 0xe8, 0x62, 0x4a, 0x32, 0x05, 0x4f, 0xb3, 0x2c, 0xd6, 0x3b, 0xc9, 0xa9, 0x8b, 0x41, 0x5d,
	0xcd, 0xb2, 0x87, 0x9d, 0xe4, 0x6b, 0x07, 0x3f, 0xe4, 0x93, 0xb7, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xa8, 0xda, 0xa7, 0x85, 0xf9, 0x02, 0x00, 0x00,
}
