// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_api/bilibili/broadcast/message/note/sync.proto

package bilibili_broadcast_message_note

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
type Sync struct {
	// 笔记id
	NoteId int64 `protobuf:"varint,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	// 唯一标示
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sync) Reset()         { *m = Sync{} }
func (m *Sync) String() string { return proto.CompactTextString(m) }
func (*Sync) ProtoMessage()    {}
func (*Sync) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e3bc8e159269ac0, []int{0}
}

func (m *Sync) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sync.Unmarshal(m, b)
}
func (m *Sync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sync.Marshal(b, m, deterministic)
}
func (m *Sync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sync.Merge(m, src)
}
func (m *Sync) XXX_Size() int {
	return xxx_messageInfo_Sync.Size(m)
}
func (m *Sync) XXX_DiscardUnknown() {
	xxx_messageInfo_Sync.DiscardUnknown(m)
}

var xxx_messageInfo_Sync proto.InternalMessageInfo

func (m *Sync) GetNoteId() int64 {
	if m != nil {
		return m.NoteId
	}
	return 0
}

func (m *Sync) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*Sync)(nil), "bilibili.broadcast.message.note.Sync")
}

func init() {
	proto.RegisterFile("grpc_api/bilibili/broadcast/message/note/sync.proto", fileDescriptor_2e3bc8e159269ac0)
}

var fileDescriptor_2e3bc8e159269ac0 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4e, 0x2f, 0x2a, 0x48,
	0x8e, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xca, 0xcc, 0xc9, 0x04, 0x61, 0xfd, 0xa4, 0xa2, 0xfc, 0xc4,
	0x94, 0xe4, 0xc4, 0xe2, 0x12, 0xfd, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0xfd, 0xbc, 0xfc,
	0x92, 0x54, 0xfd, 0xe2, 0xca, 0xbc, 0x64, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x21, 0x79, 0x98,
	0x5a, 0x3d, 0xb8, 0x5a, 0x3d, 0xa8, 0x5a, 0x3d, 0x90, 0x5a, 0x25, 0x63, 0x2e, 0x96, 0xe0, 0xca,
	0xbc, 0x64, 0x21, 0x71, 0x2e, 0x76, 0x10, 0x3f, 0x3e, 0x33, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83,
	0x39, 0x88, 0x0d, 0xc4, 0xf5, 0x4c, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x48, 0x2c, 0xce, 0x90, 0x60,
	0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x93, 0xd8, 0xc0, 0x86, 0x1b, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xcb, 0xe5, 0xc1, 0x05, 0x93, 0x00, 0x00, 0x00,
}
