// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_api/bilibili/broadcast/message/ogv/freya.proto

package bilibili_broadcast_message_ogv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 播放状态
type PlayStatus int32

const (
	// 暂停
	PlayStatus_Pause PlayStatus = 0
	// 播放
	PlayStatus_Play PlayStatus = 1
	// 终止
	PlayStatus_End PlayStatus = 2
)

var PlayStatus_name = map[int32]string{
	0: "Pause",
	1: "Play",
	2: "End",
}

var PlayStatus_value = map[string]int32{
	"Pause": 0,
	"Play":  1,
	"End":   2,
}

func (x PlayStatus) String() string {
	return proto.EnumName(PlayStatus_name, int32(x))
}

func (PlayStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_321c7424dfbc9d9f, []int{0}
}

// 房间类型
type RoomType int32

const (
	// 私密
	RoomType_Private RoomType = 0
	// 公开
	RoomType_Open RoomType = 1
)

var RoomType_name = map[int32]string{
	0: "Private",
	1: "Open",
}

var RoomType_value = map[string]int32{
	"Private": 0,
	"Open":    1,
}

func (x RoomType) String() string {
	return proto.EnumName(RoomType_name, int32(x))
}

func (RoomType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_321c7424dfbc9d9f, []int{1}
}

// 信息通知发送领域
type MessageDomain int32

const (
	// 默认
	MessageDomain_DefaultDomain MessageDomain = 0
	// 房间用户
	MessageDomain_RoomMid MessageDomain = 1
	// 系统通知
	MessageDomain_SystemInfo MessageDomain = 2
)

var MessageDomain_name = map[int32]string{
	0: "DefaultDomain",
	1: "RoomMid",
	2: "SystemInfo",
}

var MessageDomain_value = map[string]int32{
	"DefaultDomain": 0,
	"RoomMid":       1,
	"SystemInfo":    2,
}

func (x MessageDomain) String() string {
	return proto.EnumName(MessageDomain_name, int32(x))
}

func (MessageDomain) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_321c7424dfbc9d9f, []int{2}
}

// 通知信息类型
type MessageType int32

const (
	// 默认
	MessageType_DefaultType MessageType = 0
	// 房间用户
	MessageType_ChatMessage MessageType = 1
	// 系统通知
	MessageType_SystemMessage MessageType = 2
)

var MessageType_name = map[int32]string{
	0: "DefaultType",
	1: "ChatMessage",
	2: "SystemMessage",
}

var MessageType_value = map[string]int32{
	"DefaultType":   0,
	"ChatMessage":   1,
	"SystemMessage": 2,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_321c7424dfbc9d9f, []int{3}
}

// 触发通知类型
type TriggerType int32

const (
	// 默认
	TriggerType_DefaultTrigger TriggerType = 0
	// 关注、取消关注
	TriggerType_Relation TriggerType = 1
)

var TriggerType_name = map[int32]string{
	0: "DefaultTrigger",
	1: "Relation",
}

var TriggerType_value = map[string]int32{
	"DefaultTrigger": 0,
	"Relation":       1,
}

func (x TriggerType) String() string {
	return proto.EnumName(TriggerType_name, int32(x))
}

func (TriggerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_321c7424dfbc9d9f, []int{4}
}

// 房间人员变更事件
type RoomMemberChangeEvent struct {
	// 房间id
	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// 房主id
	OwnerId int64 `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// 房间成员列表
	Members []*UserInfoProto `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	// 提示信息
	Message              *MessageProto `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RoomMemberChangeEvent) Reset()         { *m = RoomMemberChangeEvent{} }
func (m *RoomMemberChangeEvent) String() string { return proto.CompactTextString(m) }
func (*RoomMemberChangeEvent) ProtoMessage()    {}
func (*RoomMemberChangeEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_321c7424dfbc9d9f, []int{0}
}

func (m *RoomMemberChangeEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomMemberChangeEvent.Unmarshal(m, b)
}
func (m *RoomMemberChangeEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomMemberChangeEvent.Marshal(b, m, deterministic)
}
func (m *RoomMemberChangeEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomMemberChangeEvent.Merge(m, src)
}
func (m *RoomMemberChangeEvent) XXX_Size() int {
	return xxx_messageInfo_RoomMemberChangeEvent.Size(m)
}
func (m *RoomMemberChangeEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomMemberChangeEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RoomMemberChangeEvent proto.InternalMessageInfo

func (m *RoomMemberChangeEvent) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RoomMemberChangeEvent) GetOwnerId() int64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *RoomMemberChangeEvent) GetMembers() []*UserInfoProto {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *RoomMemberChangeEvent) GetMessage() *MessageProto {
	if m != nil {
		return m.Message
	}
	return nil
}

// 播放进度同步事件
type ProgressSyncEvent struct {
	// 房间id
	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// 播放中的season_id
	SeasonId int64 `protobuf:"varint,2,opt,name=season_id,json=seasonId,proto3" json:"season_id,omitempty"`
	// 播放中的episode_id
	EpisodeId int64 `protobuf:"varint,3,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	// 播放状态
	Status PlayStatus `protobuf:"varint,4,opt,name=status,proto3,enum=bilibili.broadcast.message.ogv.PlayStatus" json:"status,omitempty"`
	// 房主播放进度
	Progress int64 `protobuf:"varint,5,opt,name=progress,proto3" json:"progress,omitempty"`
	// 提示信息
	Message              *MessageProto `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ProgressSyncEvent) Reset()         { *m = ProgressSyncEvent{} }
func (m *ProgressSyncEvent) String() string { return proto.CompactTextString(m) }
func (*ProgressSyncEvent) ProtoMessage()    {}
func (*ProgressSyncEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_321c7424dfbc9d9f, []int{1}
}

func (m *ProgressSyncEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProgressSyncEvent.Unmarshal(m, b)
}
func (m *ProgressSyncEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProgressSyncEvent.Marshal(b, m, deterministic)
}
func (m *ProgressSyncEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProgressSyncEvent.Merge(m, src)
}
func (m *ProgressSyncEvent) XXX_Size() int {
	return xxx_messageInfo_ProgressSyncEvent.Size(m)
}
func (m *ProgressSyncEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ProgressSyncEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ProgressSyncEvent proto.InternalMessageInfo

func (m *ProgressSyncEvent) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *ProgressSyncEvent) GetSeasonId() int64 {
	if m != nil {
		return m.SeasonId
	}
	return 0
}

func (m *ProgressSyncEvent) GetEpisodeId() int64 {
	if m != nil {
		return m.EpisodeId
	}
	return 0
}

func (m *ProgressSyncEvent) GetStatus() PlayStatus {
	if m != nil {
		return m.Status
	}
	return PlayStatus_Pause
}

func (m *ProgressSyncEvent) GetProgress() int64 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *ProgressSyncEvent) GetMessage() *MessageProto {
	if m != nil {
		return m.Message
	}
	return nil
}

// 房间状态更新
type RoomUpdateEvent struct {
	// 房间id
	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// 房间变更状态
	Type RoomType `protobuf:"varint,2,opt,name=type,proto3,enum=bilibili.broadcast.message.ogv.RoomType" json:"type,omitempty"`
	// 提示信息
	Message              *MessageProto `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RoomUpdateEvent) Reset()         { *m = RoomUpdateEvent{} }
func (m *RoomUpdateEvent) String() string { return proto.CompactTextString(m) }
func (*RoomUpdateEvent) ProtoMessage()    {}
func (*RoomUpdateEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_321c7424dfbc9d9f, []int{2}
}

func (m *RoomUpdateEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomUpdateEvent.Unmarshal(m, b)
}
func (m *RoomUpdateEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomUpdateEvent.Marshal(b, m, deterministic)
}
func (m *RoomUpdateEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomUpdateEvent.Merge(m, src)
}
func (m *RoomUpdateEvent) XXX_Size() int {
	return xxx_messageInfo_RoomUpdateEvent.Size(m)
}
func (m *RoomUpdateEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomUpdateEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RoomUpdateEvent proto.InternalMessageInfo

func (m *RoomUpdateEvent) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RoomUpdateEvent) GetType() RoomType {
	if m != nil {
		return m.Type
	}
	return RoomType_Private
}

func (m *RoomUpdateEvent) GetMessage() *MessageProto {
	if m != nil {
		return m.Message
	}
	return nil
}

// 房间销毁通知
type RoomDestroyEvent struct {
	// 房间id
	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// 提示信息
	Message              *MessageProto `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RoomDestroyEvent) Reset()         { *m = RoomDestroyEvent{} }
func (m *RoomDestroyEvent) String() string { return proto.CompactTextString(m) }
func (*RoomDestroyEvent) ProtoMessage()    {}
func (*RoomDestroyEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_321c7424dfbc9d9f, []int{3}
}

func (m *RoomDestroyEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomDestroyEvent.Unmarshal(m, b)
}
func (m *RoomDestroyEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomDestroyEvent.Marshal(b, m, deterministic)
}
func (m *RoomDestroyEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomDestroyEvent.Merge(m, src)
}
func (m *RoomDestroyEvent) XXX_Size() int {
	return xxx_messageInfo_RoomDestroyEvent.Size(m)
}
func (m *RoomDestroyEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomDestroyEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RoomDestroyEvent proto.InternalMessageInfo

func (m *RoomDestroyEvent) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RoomDestroyEvent) GetMessage() *MessageProto {
	if m != nil {
		return m.Message
	}
	return nil
}

// 房间触发通知
type RoomTriggerEvent struct {
	// 操作人
	Mid int64 `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	// 提示信息
	Message *MessageProto `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 触发类型
	Trigger              TriggerType `protobuf:"varint,3,opt,name=trigger,proto3,enum=bilibili.broadcast.message.ogv.TriggerType" json:"trigger,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RoomTriggerEvent) Reset()         { *m = RoomTriggerEvent{} }
func (m *RoomTriggerEvent) String() string { return proto.CompactTextString(m) }
func (*RoomTriggerEvent) ProtoMessage()    {}
func (*RoomTriggerEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_321c7424dfbc9d9f, []int{4}
}

func (m *RoomTriggerEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomTriggerEvent.Unmarshal(m, b)
}
func (m *RoomTriggerEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomTriggerEvent.Marshal(b, m, deterministic)
}
func (m *RoomTriggerEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomTriggerEvent.Merge(m, src)
}
func (m *RoomTriggerEvent) XXX_Size() int {
	return xxx_messageInfo_RoomTriggerEvent.Size(m)
}
func (m *RoomTriggerEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomTriggerEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RoomTriggerEvent proto.InternalMessageInfo

func (m *RoomTriggerEvent) GetMid() int64 {
	if m != nil {
		return m.Mid
	}
	return 0
}

func (m *RoomTriggerEvent) GetMessage() *MessageProto {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *RoomTriggerEvent) GetTrigger() TriggerType {
	if m != nil {
		return m.Trigger
	}
	return TriggerType_DefaultTrigger
}

//用户信息
type UserInfoProto struct {
	// 用户id
	Mid int64 `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	// 用户头像url
	Face string `protobuf:"bytes,2,opt,name=face,proto3" json:"face,omitempty"`
	// 昵称
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 等级
	Level int32 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	// 签名
	Sign string `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
	// 大会员信息
	Vip *VipProto `protobuf:"bytes,6,opt,name=vip,proto3" json:"vip,omitempty"`
	// 身份认证信息
	Official *OfficialProto `protobuf:"bytes,7,opt,name=official,proto3" json:"official,omitempty"`
	// 挂件信息
	Pendant *PendantProto `protobuf:"bytes,8,opt,name=pendant,proto3" json:"pendant,omitempty"`
	// 设备buvid
	Buvid                string   `protobuf:"bytes,9,opt,name=buvid,proto3" json:"buvid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoProto) Reset()         { *m = UserInfoProto{} }
func (m *UserInfoProto) String() string { return proto.CompactTextString(m) }
func (*UserInfoProto) ProtoMessage()    {}
func (*UserInfoProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_321c7424dfbc9d9f, []int{5}
}

func (m *UserInfoProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoProto.Unmarshal(m, b)
}
func (m *UserInfoProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoProto.Marshal(b, m, deterministic)
}
func (m *UserInfoProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoProto.Merge(m, src)
}
func (m *UserInfoProto) XXX_Size() int {
	return xxx_messageInfo_UserInfoProto.Size(m)
}
func (m *UserInfoProto) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoProto.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoProto proto.InternalMessageInfo

func (m *UserInfoProto) GetMid() int64 {
	if m != nil {
		return m.Mid
	}
	return 0
}

func (m *UserInfoProto) GetFace() string {
	if m != nil {
		return m.Face
	}
	return ""
}

func (m *UserInfoProto) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfoProto) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *UserInfoProto) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *UserInfoProto) GetVip() *VipProto {
	if m != nil {
		return m.Vip
	}
	return nil
}

func (m *UserInfoProto) GetOfficial() *OfficialProto {
	if m != nil {
		return m.Official
	}
	return nil
}

func (m *UserInfoProto) GetPendant() *PendantProto {
	if m != nil {
		return m.Pendant
	}
	return nil
}

func (m *UserInfoProto) GetBuvid() string {
	if m != nil {
		return m.Buvid
	}
	return ""
}

//通知信息
type MessageProto struct {
	// 可带占位符匹配的消息体 ep "还没有其他小伙伴，[去邀请>]<https://big.bilibili.com/mobile/giftIndex?mid=123>"
	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// 消息体类型
	// 0:json格式的文本消息 1:支持全文本可点(破冰)
	ContentType          int32    `protobuf:"varint,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageProto) Reset()         { *m = MessageProto{} }
func (m *MessageProto) String() string { return proto.CompactTextString(m) }
func (*MessageProto) ProtoMessage()    {}
func (*MessageProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_321c7424dfbc9d9f, []int{6}
}

func (m *MessageProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageProto.Unmarshal(m, b)
}
func (m *MessageProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageProto.Marshal(b, m, deterministic)
}
func (m *MessageProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageProto.Merge(m, src)
}
func (m *MessageProto) XXX_Size() int {
	return xxx_messageInfo_MessageProto.Size(m)
}
func (m *MessageProto) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageProto.DiscardUnknown(m)
}

var xxx_messageInfo_MessageProto proto.InternalMessageInfo

func (m *MessageProto) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MessageProto) GetContentType() int32 {
	if m != nil {
		return m.ContentType
	}
	return 0
}

//大会员信息
type VipProto struct {
	Type       int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Status     int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	DueDate    int64 `protobuf:"varint,3,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	VipPayType int32 `protobuf:"varint,4,opt,name=vip_pay_type,json=vipPayType,proto3" json:"vip_pay_type,omitempty"`
	ThemeType  int32 `protobuf:"varint,5,opt,name=theme_type,json=themeType,proto3" json:"theme_type,omitempty"`
	// 大会员角标
	// 0:无角标 1:粉色大会员角标 2:绿色小会员角标
	AvatarSubscript int32 `protobuf:"varint,6,opt,name=avatar_subscript,json=avatarSubscript,proto3" json:"avatar_subscript,omitempty"`
	// 昵称色值，可能为空，色值示例：#FFFB9E60
	NicknameColor        string   `protobuf:"bytes,7,opt,name=nickname_color,json=nicknameColor,proto3" json:"nickname_color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VipProto) Reset()         { *m = VipProto{} }
func (m *VipProto) String() string { return proto.CompactTextString(m) }
func (*VipProto) ProtoMessage()    {}
func (*VipProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_321c7424dfbc9d9f, []int{7}
}

func (m *VipProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VipProto.Unmarshal(m, b)
}
func (m *VipProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VipProto.Marshal(b, m, deterministic)
}
func (m *VipProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VipProto.Merge(m, src)
}
func (m *VipProto) XXX_Size() int {
	return xxx_messageInfo_VipProto.Size(m)
}
func (m *VipProto) XXX_DiscardUnknown() {
	xxx_messageInfo_VipProto.DiscardUnknown(m)
}

var xxx_messageInfo_VipProto proto.InternalMessageInfo

func (m *VipProto) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *VipProto) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *VipProto) GetDueDate() int64 {
	if m != nil {
		return m.DueDate
	}
	return 0
}

func (m *VipProto) GetVipPayType() int32 {
	if m != nil {
		return m.VipPayType
	}
	return 0
}

func (m *VipProto) GetThemeType() int32 {
	if m != nil {
		return m.ThemeType
	}
	return 0
}

func (m *VipProto) GetAvatarSubscript() int32 {
	if m != nil {
		return m.AvatarSubscript
	}
	return 0
}

func (m *VipProto) GetNicknameColor() string {
	if m != nil {
		return m.NicknameColor
	}
	return ""
}

//认证信息
type OfficialProto struct {
	Role                 int32    `protobuf:"varint,1,opt,name=role,proto3" json:"role,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Desc                 string   `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Type                 int32    `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfficialProto) Reset()         { *m = OfficialProto{} }
func (m *OfficialProto) String() string { return proto.CompactTextString(m) }
func (*OfficialProto) ProtoMessage()    {}
func (*OfficialProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_321c7424dfbc9d9f, []int{8}
}

func (m *OfficialProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfficialProto.Unmarshal(m, b)
}
func (m *OfficialProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfficialProto.Marshal(b, m, deterministic)
}
func (m *OfficialProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfficialProto.Merge(m, src)
}
func (m *OfficialProto) XXX_Size() int {
	return xxx_messageInfo_OfficialProto.Size(m)
}
func (m *OfficialProto) XXX_DiscardUnknown() {
	xxx_messageInfo_OfficialProto.DiscardUnknown(m)
}

var xxx_messageInfo_OfficialProto proto.InternalMessageInfo

func (m *OfficialProto) GetRole() int32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *OfficialProto) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *OfficialProto) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *OfficialProto) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

//挂件信息
type PendantProto struct {
	Pid                  int32    `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image                string   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Expire               int64    `protobuf:"varint,4,opt,name=expire,proto3" json:"expire,omitempty"`
	ImageEnhance         string   `protobuf:"bytes,5,opt,name=image_enhance,json=imageEnhance,proto3" json:"image_enhance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PendantProto) Reset()         { *m = PendantProto{} }
func (m *PendantProto) String() string { return proto.CompactTextString(m) }
func (*PendantProto) ProtoMessage()    {}
func (*PendantProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_321c7424dfbc9d9f, []int{9}
}

func (m *PendantProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendantProto.Unmarshal(m, b)
}
func (m *PendantProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendantProto.Marshal(b, m, deterministic)
}
func (m *PendantProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendantProto.Merge(m, src)
}
func (m *PendantProto) XXX_Size() int {
	return xxx_messageInfo_PendantProto.Size(m)
}
func (m *PendantProto) XXX_DiscardUnknown() {
	xxx_messageInfo_PendantProto.DiscardUnknown(m)
}

var xxx_messageInfo_PendantProto proto.InternalMessageInfo

func (m *PendantProto) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *PendantProto) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PendantProto) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *PendantProto) GetExpire() int64 {
	if m != nil {
		return m.Expire
	}
	return 0
}

func (m *PendantProto) GetImageEnhance() string {
	if m != nil {
		return m.ImageEnhance
	}
	return ""
}

// 通用信息通知
type MessageEvent struct {
	// 房间id
	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// 消息id
	MsgId int64 `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	// 消息发送服务端时间 时间戳 单位秒
	Ts int64 `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	// 信息通知发送主体id
	Oid int64 `protobuf:"varint,4,opt,name=oid,proto3" json:"oid,omitempty"`
	// 信息通知发送领域
	Domain MessageDomain `protobuf:"varint,5,opt,name=domain,proto3,enum=bilibili.broadcast.message.ogv.MessageDomain" json:"domain,omitempty"`
	// 通知信息类型
	Type MessageType `protobuf:"varint,6,opt,name=type,proto3,enum=bilibili.broadcast.message.ogv.MessageType" json:"type,omitempty"`
	// 提示信息
	Message *MessageProto `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	// 消息发送用户信息
	User *UserInfoProto `protobuf:"bytes,8,opt,name=user,proto3" json:"user,omitempty"`
	// 消息id str类型
	MsgId2               string   `protobuf:"bytes,9,opt,name=msg_id2,json=msgId2,proto3" json:"msg_id2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageEvent) Reset()         { *m = MessageEvent{} }
func (m *MessageEvent) String() string { return proto.CompactTextString(m) }
func (*MessageEvent) ProtoMessage()    {}
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_321c7424dfbc9d9f, []int{10}
}

func (m *MessageEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageEvent.Unmarshal(m, b)
}
func (m *MessageEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageEvent.Marshal(b, m, deterministic)
}
func (m *MessageEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageEvent.Merge(m, src)
}
func (m *MessageEvent) XXX_Size() int {
	return xxx_messageInfo_MessageEvent.Size(m)
}
func (m *MessageEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageEvent.DiscardUnknown(m)
}

var xxx_messageInfo_MessageEvent proto.InternalMessageInfo

func (m *MessageEvent) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *MessageEvent) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *MessageEvent) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *MessageEvent) GetOid() int64 {
	if m != nil {
		return m.Oid
	}
	return 0
}

func (m *MessageEvent) GetDomain() MessageDomain {
	if m != nil {
		return m.Domain
	}
	return MessageDomain_DefaultDomain
}

func (m *MessageEvent) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_DefaultType
}

func (m *MessageEvent) GetMessage() *MessageProto {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *MessageEvent) GetUser() *UserInfoProto {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *MessageEvent) GetMsgId2() string {
	if m != nil {
		return m.MsgId2
	}
	return ""
}

// 聊天信息清除通知
type RemoveChatEvent struct {
	// 房间id
	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// 撤回的聊天信息id
	MsgId int64 `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	// 提示信息
	Message              *MessageProto `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RemoveChatEvent) Reset()         { *m = RemoveChatEvent{} }
func (m *RemoveChatEvent) String() string { return proto.CompactTextString(m) }
func (*RemoveChatEvent) ProtoMessage()    {}
func (*RemoveChatEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_321c7424dfbc9d9f, []int{11}
}

func (m *RemoveChatEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveChatEvent.Unmarshal(m, b)
}
func (m *RemoveChatEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveChatEvent.Marshal(b, m, deterministic)
}
func (m *RemoveChatEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveChatEvent.Merge(m, src)
}
func (m *RemoveChatEvent) XXX_Size() int {
	return xxx_messageInfo_RemoveChatEvent.Size(m)
}
func (m *RemoveChatEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveChatEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveChatEvent proto.InternalMessageInfo

func (m *RemoveChatEvent) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RemoveChatEvent) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *RemoveChatEvent) GetMessage() *MessageProto {
	if m != nil {
		return m.Message
	}
	return nil
}

// "一起看"房间事件
type FreyaEventBody struct {
	// 房间id
	RoomId int64 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// 接收事件消息的白名单用户
	WhiteMid []int64 `protobuf:"varint,2,rep,packed,name=white_mid,json=whiteMid,proto3" json:"white_mid,omitempty"`
	// 不处理信息的黑名单用户 优先级低于白名单 当白名单有数据时 忽略黑名单
	IgnoreMid []int64 `protobuf:"varint,3,rep,packed,name=ignore_mid,json=ignoreMid,proto3" json:"ignore_mid,omitempty"`
	//命令类型
	//
	// Types that are valid to be assigned to Event:
	//	*FreyaEventBody_MemberChange
	//	*FreyaEventBody_Progress
	//	*FreyaEventBody_RoomUpdate
	//	*FreyaEventBody_Message
	//	*FreyaEventBody_RemoveChat
	//	*FreyaEventBody_RoomDestroy
	//	*FreyaEventBody_RoomTrigger
	Event isFreyaEventBody_Event `protobuf_oneof:"event"`
	// 消息序列号
	SequenceId           int64    `protobuf:"varint,100,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FreyaEventBody) Reset()         { *m = FreyaEventBody{} }
func (m *FreyaEventBody) String() string { return proto.CompactTextString(m) }
func (*FreyaEventBody) ProtoMessage()    {}
func (*FreyaEventBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_321c7424dfbc9d9f, []int{12}
}

func (m *FreyaEventBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FreyaEventBody.Unmarshal(m, b)
}
func (m *FreyaEventBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FreyaEventBody.Marshal(b, m, deterministic)
}
func (m *FreyaEventBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FreyaEventBody.Merge(m, src)
}
func (m *FreyaEventBody) XXX_Size() int {
	return xxx_messageInfo_FreyaEventBody.Size(m)
}
func (m *FreyaEventBody) XXX_DiscardUnknown() {
	xxx_messageInfo_FreyaEventBody.DiscardUnknown(m)
}

var xxx_messageInfo_FreyaEventBody proto.InternalMessageInfo

func (m *FreyaEventBody) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *FreyaEventBody) GetWhiteMid() []int64 {
	if m != nil {
		return m.WhiteMid
	}
	return nil
}

func (m *FreyaEventBody) GetIgnoreMid() []int64 {
	if m != nil {
		return m.IgnoreMid
	}
	return nil
}

type isFreyaEventBody_Event interface {
	isFreyaEventBody_Event()
}

type FreyaEventBody_MemberChange struct {
	MemberChange *RoomMemberChangeEvent `protobuf:"bytes,4,opt,name=member_change,json=memberChange,proto3,oneof"`
}

type FreyaEventBody_Progress struct {
	Progress *ProgressSyncEvent `protobuf:"bytes,5,opt,name=progress,proto3,oneof"`
}

type FreyaEventBody_RoomUpdate struct {
	RoomUpdate *RoomUpdateEvent `protobuf:"bytes,6,opt,name=room_update,json=roomUpdate,proto3,oneof"`
}

type FreyaEventBody_Message struct {
	Message *MessageEvent `protobuf:"bytes,7,opt,name=message,proto3,oneof"`
}

type FreyaEventBody_RemoveChat struct {
	RemoveChat *RemoveChatEvent `protobuf:"bytes,8,opt,name=remove_chat,json=removeChat,proto3,oneof"`
}

type FreyaEventBody_RoomDestroy struct {
	RoomDestroy *RoomDestroyEvent `protobuf:"bytes,9,opt,name=room_destroy,json=roomDestroy,proto3,oneof"`
}

type FreyaEventBody_RoomTrigger struct {
	RoomTrigger *RoomTriggerEvent `protobuf:"bytes,10,opt,name=room_trigger,json=roomTrigger,proto3,oneof"`
}

func (*FreyaEventBody_MemberChange) isFreyaEventBody_Event() {}

func (*FreyaEventBody_Progress) isFreyaEventBody_Event() {}

func (*FreyaEventBody_RoomUpdate) isFreyaEventBody_Event() {}

func (*FreyaEventBody_Message) isFreyaEventBody_Event() {}

func (*FreyaEventBody_RemoveChat) isFreyaEventBody_Event() {}

func (*FreyaEventBody_RoomDestroy) isFreyaEventBody_Event() {}

func (*FreyaEventBody_RoomTrigger) isFreyaEventBody_Event() {}

func (m *FreyaEventBody) GetEvent() isFreyaEventBody_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *FreyaEventBody) GetMemberChange() *RoomMemberChangeEvent {
	if x, ok := m.GetEvent().(*FreyaEventBody_MemberChange); ok {
		return x.MemberChange
	}
	return nil
}

func (m *FreyaEventBody) GetProgress() *ProgressSyncEvent {
	if x, ok := m.GetEvent().(*FreyaEventBody_Progress); ok {
		return x.Progress
	}
	return nil
}

func (m *FreyaEventBody) GetRoomUpdate() *RoomUpdateEvent {
	if x, ok := m.GetEvent().(*FreyaEventBody_RoomUpdate); ok {
		return x.RoomUpdate
	}
	return nil
}

func (m *FreyaEventBody) GetMessage() *MessageEvent {
	if x, ok := m.GetEvent().(*FreyaEventBody_Message); ok {
		return x.Message
	}
	return nil
}

func (m *FreyaEventBody) GetRemoveChat() *RemoveChatEvent {
	if x, ok := m.GetEvent().(*FreyaEventBody_RemoveChat); ok {
		return x.RemoveChat
	}
	return nil
}

func (m *FreyaEventBody) GetRoomDestroy() *RoomDestroyEvent {
	if x, ok := m.GetEvent().(*FreyaEventBody_RoomDestroy); ok {
		return x.RoomDestroy
	}
	return nil
}

func (m *FreyaEventBody) GetRoomTrigger() *RoomTriggerEvent {
	if x, ok := m.GetEvent().(*FreyaEventBody_RoomTrigger); ok {
		return x.RoomTrigger
	}
	return nil
}

func (m *FreyaEventBody) GetSequenceId() int64 {
	if m != nil {
		return m.SequenceId
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FreyaEventBody) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FreyaEventBody_MemberChange)(nil),
		(*FreyaEventBody_Progress)(nil),
		(*FreyaEventBody_RoomUpdate)(nil),
		(*FreyaEventBody_Message)(nil),
		(*FreyaEventBody_RemoveChat)(nil),
		(*FreyaEventBody_RoomDestroy)(nil),
		(*FreyaEventBody_RoomTrigger)(nil),
	}
}

func init() {
	proto.RegisterEnum("bilibili.broadcast.message.ogv.PlayStatus", PlayStatus_name, PlayStatus_value)
	proto.RegisterEnum("bilibili.broadcast.message.ogv.RoomType", RoomType_name, RoomType_value)
	proto.RegisterEnum("bilibili.broadcast.message.ogv.MessageDomain", MessageDomain_name, MessageDomain_value)
	proto.RegisterEnum("bilibili.broadcast.message.ogv.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("bilibili.broadcast.message.ogv.TriggerType", TriggerType_name, TriggerType_value)
	proto.RegisterType((*RoomMemberChangeEvent)(nil), "bilibili.broadcast.message.ogv.RoomMemberChangeEvent")
	proto.RegisterType((*ProgressSyncEvent)(nil), "bilibili.broadcast.message.ogv.ProgressSyncEvent")
	proto.RegisterType((*RoomUpdateEvent)(nil), "bilibili.broadcast.message.ogv.RoomUpdateEvent")
	proto.RegisterType((*RoomDestroyEvent)(nil), "bilibili.broadcast.message.ogv.RoomDestroyEvent")
	proto.RegisterType((*RoomTriggerEvent)(nil), "bilibili.broadcast.message.ogv.RoomTriggerEvent")
	proto.RegisterType((*UserInfoProto)(nil), "bilibili.broadcast.message.ogv.UserInfoProto")
	proto.RegisterType((*MessageProto)(nil), "bilibili.broadcast.message.ogv.MessageProto")
	proto.RegisterType((*VipProto)(nil), "bilibili.broadcast.message.ogv.VipProto")
	proto.RegisterType((*OfficialProto)(nil), "bilibili.broadcast.message.ogv.OfficialProto")
	proto.RegisterType((*PendantProto)(nil), "bilibili.broadcast.message.ogv.PendantProto")
	proto.RegisterType((*MessageEvent)(nil), "bilibili.broadcast.message.ogv.MessageEvent")
	proto.RegisterType((*RemoveChatEvent)(nil), "bilibili.broadcast.message.ogv.RemoveChatEvent")
	proto.RegisterType((*FreyaEventBody)(nil), "bilibili.broadcast.message.ogv.FreyaEventBody")
}

func init() {
	proto.RegisterFile("grpc_api/bilibili/broadcast/message/ogv/freya.proto", fileDescriptor_321c7424dfbc9d9f)
}

var fileDescriptor_321c7424dfbc9d9f = []byte{
	// 1227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0xf7, 0xf9, 0xe2, 0x3f, 0x37, 0xfe, 0xd3, 0xeb, 0x8a, 0x82, 0x0b, 0x02, 0x52, 0x23, 0xa4,
	0x60, 0x20, 0x06, 0x57, 0xbc, 0x20, 0xa4, 0x8a, 0x34, 0x29, 0xb1, 0x50, 0x55, 0xeb, 0xd2, 0xf0,
	0x84, 0x64, 0x6d, 0xee, 0x36, 0x97, 0x15, 0xbe, 0xdb, 0xe3, 0x76, 0xed, 0xe2, 0x4f, 0x80, 0x90,
	0x78, 0xe0, 0xa3, 0x20, 0xf1, 0x75, 0x10, 0xe2, 0x81, 0x0f, 0x82, 0x76, 0x76, 0xef, 0x72, 0x29,
	0x55, 0x2f, 0x34, 0x7d, 0xb0, 0xb4, 0xf3, 0x7f, 0x76, 0xe6, 0xb7, 0x73, 0x63, 0xb8, 0x1f, 0xe7,
	0x59, 0xb8, 0xa4, 0x19, 0x9f, 0x9e, 0xf1, 0x15, 0xd7, 0xbf, 0xe9, 0x59, 0x2e, 0x68, 0x14, 0x52,
	0xa9, 0xa6, 0x09, 0x93, 0x92, 0xc6, 0x6c, 0x2a, 0xe2, 0xcd, 0xf4, 0x3c, 0x67, 0x5b, 0xba, 0x9f,
	0xe5, 0x42, 0x09, 0xf2, 0x5e, 0xa1, 0xbb, 0x5f, 0xea, 0xee, 0x5b, 0xdd, 0x7d, 0x11, 0x6f, 0xc6,
	0x7f, 0x3a, 0x70, 0x27, 0x10, 0x22, 0x79, 0xcc, 0x92, 0x33, 0x96, 0x3f, 0xbc, 0xa0, 0x69, 0xcc,
	0x8e, 0x36, 0x2c, 0x55, 0xe4, 0x2d, 0xe8, 0xe4, 0x42, 0x24, 0x4b, 0x1e, 0x8d, 0x9c, 0x5d, 0x67,
	0xcf, 0x0d, 0xda, 0x9a, 0x9c, 0x47, 0xe4, 0x2e, 0x74, 0xc5, 0xb3, 0x94, 0xe5, 0x5a, 0xd2, 0x44,
	0x49, 0x07, 0xe9, 0x79, 0x44, 0xbe, 0x81, 0x4e, 0x82, 0x8e, 0xe4, 0xc8, 0xdd, 0x75, 0xf7, 0x7a,
	0xb3, 0x4f, 0xf7, 0x5f, 0x1e, 0x7f, 0xff, 0x54, 0xb2, 0x7c, 0x9e, 0x9e, 0x8b, 0x85, 0xce, 0x36,
	0x28, 0xac, 0xc9, 0x23, 0xed, 0x08, 0xb5, 0x46, 0x3b, 0xbb, 0xce, 0x5e, 0x6f, 0xf6, 0x49, 0x9d,
	0xa3, 0xc7, 0xe6, 0x5c, 0xfa, 0x41, 0x6a, 0xfc, 0x5b, 0x13, 0x6e, 0x2f, 0x72, 0x11, 0xe7, 0x4c,
	0xca, 0x93, 0x6d, 0x1a, 0xd6, 0x5c, 0xed, 0x1d, 0xf0, 0x24, 0xa3, 0x52, 0xa4, 0x97, 0x77, 0xeb,
	0x1a, 0xc6, 0x3c, 0x22, 0xef, 0x02, 0xb0, 0x8c, 0x4b, 0x11, 0x31, 0x2d, 0x75, 0x51, 0xea, 0x59,
	0xce, 0x3c, 0x22, 0x07, 0xd0, 0x96, 0x8a, 0xaa, 0xb5, 0xc4, 0x8c, 0x87, 0xb3, 0x49, 0x5d, 0xc6,
	0x8b, 0x15, 0xdd, 0x9e, 0xa0, 0x45, 0x60, 0x2d, 0xc9, 0xdb, 0xd0, 0xcd, 0x6c, 0xb6, 0xa3, 0x96,
	0x09, 0x5f, 0xd0, 0xd5, 0x92, 0xb4, 0x6f, 0x52, 0x92, 0xdf, 0x1d, 0xb8, 0xa5, 0x3b, 0x7e, 0x9a,
	0x45, 0x54, 0xd5, 0xf5, 0xfa, 0x2b, 0xd8, 0x51, 0xdb, 0x8c, 0x61, 0x2d, 0x86, 0xb3, 0xbd, 0xba,
	0x88, 0xda, 0xef, 0xd3, 0x6d, 0xc6, 0x02, 0xb4, 0xaa, 0xa6, 0xec, 0xde, 0x24, 0x65, 0x09, 0xbe,
	0xf6, 0x7c, 0xc8, 0xa4, 0xca, 0xc5, 0xb6, 0x26, 0xe5, 0xd7, 0x05, 0x9d, 0x3f, 0x1c, 0x13, 0xf5,
	0x69, 0xce, 0xe3, 0x98, 0xe5, 0x26, 0xaa, 0x0f, 0x6e, 0x52, 0x46, 0xd4, 0xc7, 0x6a, 0xb8, 0xe6,
	0x0d, 0xc2, 0x91, 0x23, 0xe8, 0x28, 0x13, 0x09, 0x6b, 0x35, 0x9c, 0x7d, 0x5c, 0xe7, 0xc7, 0x26,
	0x86, 0xf5, 0x2e, 0x6c, 0xc7, 0x7f, 0x37, 0x61, 0x70, 0xe5, 0x4d, 0xbd, 0x20, 0x65, 0x02, 0x3b,
	0xe7, 0x34, 0x34, 0xf9, 0x7a, 0x01, 0x9e, 0x35, 0xf2, 0x52, 0x1e, 0xfe, 0x90, 0xd2, 0xc4, 0xf4,
	0xca, 0x0b, 0x4a, 0x9a, 0xbc, 0x01, 0xad, 0x15, 0xdb, 0xb0, 0x15, 0xd6, 0xb3, 0x15, 0x18, 0x42,
	0x7b, 0x91, 0x3c, 0x4e, 0x11, 0xa7, 0x5e, 0x80, 0x67, 0xf2, 0x25, 0xb8, 0x1b, 0x9e, 0x59, 0x7c,
	0xd6, 0xa2, 0xe5, 0x3b, 0x9e, 0x99, 0x22, 0x68, 0x23, 0x32, 0x87, 0xae, 0x38, 0x3f, 0xe7, 0x21,
	0xa7, 0xab, 0x51, 0x07, 0x1d, 0xd4, 0x0e, 0x8f, 0x27, 0x56, 0xdf, 0x78, 0x29, 0xcd, 0x75, 0x4f,
	0x32, 0x96, 0x46, 0x34, 0x55, 0xa3, 0xee, 0xf5, 0x7a, 0xb2, 0x30, 0xea, 0xb6, 0x27, 0xd6, 0x58,
	0x5f, 0xfc, 0x6c, 0xbd, 0xe1, 0xd1, 0xc8, 0xc3, 0x3b, 0x1a, 0x62, 0xfc, 0x2d, 0xf4, 0xab, 0x2d,
	0x24, 0x23, 0xe8, 0x84, 0x22, 0x55, 0x2c, 0x55, 0x58, 0x64, 0x2f, 0x28, 0x48, 0x72, 0x0f, 0xfa,
	0xf6, 0xb8, 0x2c, 0x5f, 0x51, 0x2b, 0xe8, 0x59, 0x9e, 0x6e, 0xdc, 0xf8, 0x1f, 0x07, 0xba, 0x45,
	0x1d, 0x74, 0x49, 0x51, 0xcf, 0x41, 0x3d, 0xf3, 0x86, 0xde, 0x2c, 0xc7, 0x8a, 0xb1, 0x2e, 0x46,
	0xc5, 0x5d, 0xe8, 0x46, 0x6b, 0xb6, 0xd4, 0x6f, 0xd8, 0xce, 0xa2, 0x4e, 0xb4, 0x66, 0x87, 0x54,
	0x31, 0xb2, 0x0b, 0xfd, 0x0d, 0xcf, 0x96, 0x19, 0xdd, 0x9a, 0xb0, 0xa6, 0x6d, 0xb0, 0xe1, 0xd9,
	0x82, 0x6e, 0x75, 0x54, 0x3d, 0xca, 0xd4, 0x05, 0x4b, 0x98, 0x91, 0xb7, 0x50, 0xee, 0x21, 0x07,
	0xc5, 0x1f, 0x81, 0x4f, 0x37, 0x54, 0xd1, 0x7c, 0x29, 0xd7, 0x67, 0x32, 0xcc, 0x79, 0xa6, 0xb0,
	0xa7, 0xad, 0xe0, 0x96, 0xe1, 0x9f, 0x14, 0x6c, 0xf2, 0x21, 0x0c, 0x0b, 0x9c, 0x2c, 0x43, 0xb1,
	0x12, 0x39, 0xf6, 0xce, 0x0b, 0x06, 0x05, 0xf7, 0xa1, 0x66, 0x8e, 0x29, 0x0c, 0xae, 0x34, 0x4b,
	0x5f, 0x35, 0x17, 0xab, 0xf2, 0xaa, 0xfa, 0xac, 0xcb, 0xad, 0xb8, 0x5a, 0x15, 0xc0, 0x34, 0x84,
	0xd6, 0x8c, 0x98, 0x0c, 0x2d, 0x2a, 0xf1, 0x5c, 0x16, 0x6a, 0xe7, 0xb2, 0x50, 0xe3, 0x9f, 0x1d,
	0xe8, 0x57, 0xdb, 0xa8, 0x81, 0x9f, 0x59, 0xe0, 0xb7, 0x02, 0x7d, 0xd4, 0x66, 0x08, 0x70, 0x0b,
	0xfc, 0x02, 0xdc, 0x3c, 0x29, 0x26, 0x94, 0x17, 0x18, 0x42, 0x57, 0x9d, 0xfd, 0x94, 0xf1, 0xdc,
	0x84, 0x70, 0x03, 0x4b, 0x91, 0x0f, 0x60, 0x80, 0x0a, 0x4b, 0x96, 0x5e, 0xd0, 0x34, 0x64, 0x16,
	0xfd, 0x7d, 0x64, 0x1e, 0x19, 0xde, 0xf8, 0x57, 0xb7, 0x44, 0x48, 0xcd, 0xac, 0xba, 0x03, 0xed,
	0x44, 0xc6, 0x97, 0x1f, 0x9b, 0x56, 0x22, 0xe3, 0x79, 0x44, 0x86, 0xd0, 0x54, 0xd2, 0x76, 0xb5,
	0xa9, 0xa4, 0xbe, 0x89, 0xe0, 0x91, 0x4d, 0x45, 0x1f, 0xc9, 0x11, 0xb4, 0x23, 0x91, 0x50, 0x6e,
	0x9e, 0xdf, 0xb0, 0xfe, 0xa9, 0xd8, 0x7c, 0x0e, 0xd1, 0x28, 0xb0, 0xc6, 0xe4, 0x81, 0xad, 0x63,
	0xfb, 0x7a, 0x13, 0xc7, 0x3a, 0x79, 0xf1, 0x84, 0xef, 0xdc, 0x64, 0xfa, 0x7d, 0x0d, 0x3b, 0x6b,
	0xc9, 0x72, 0xfb, 0x5c, 0xff, 0xe7, 0xd6, 0x80, 0xa6, 0xba, 0xc8, 0xa6, 0x96, 0x33, 0xfb, 0x5c,
	0xdb, 0x58, 0xcc, 0xd9, 0xf8, 0x17, 0xfd, 0xc1, 0x63, 0x89, 0xd8, 0xb0, 0x87, 0x17, 0x54, 0xbd,
	0x5a, 0x47, 0x5e, 0xd7, 0x97, 0xec, 0xaf, 0x16, 0x0c, 0x1f, 0xe9, 0xf5, 0x0c, 0xd3, 0x38, 0x10,
	0xd1, 0xf6, 0xa5, 0xcb, 0xc8, 0xb3, 0x0b, 0xae, 0xd8, 0x32, 0xc1, 0x6c, 0x5c, 0xbd, 0x0d, 0x20,
	0xe3, 0x31, 0xc7, 0x65, 0x84, 0xc7, 0xa9, 0xc8, 0x8d, 0xd4, 0x45, 0xa9, 0x67, 0x38, 0x5a, 0xfc,
	0x3d, 0x0c, 0xcc, 0x2a, 0xb5, 0x0c, 0x71, 0xa5, 0xb3, 0x9f, 0xc2, 0x2f, 0xae, 0xf3, 0x01, 0xff,
	0xcf, 0x2a, 0x78, 0xdc, 0x08, 0xfa, 0x49, 0x85, 0x49, 0x9e, 0x3c, 0xb7, 0xa6, 0xf4, 0x66, 0x9f,
	0xd7, 0x0e, 0xd8, 0xe7, 0x97, 0xb0, 0xe3, 0x46, 0x65, 0xb7, 0x09, 0xa0, 0x87, 0x35, 0x58, 0xe3,
	0x4e, 0x62, 0xbf, 0x1f, 0xd3, 0xeb, 0x24, 0x5b, 0xd9, 0x62, 0x8e, 0x1b, 0x01, 0xe4, 0x25, 0x8b,
	0x1c, 0xbf, 0x2a, 0x34, 0x0b, 0x67, 0x25, 0x38, 0x75, 0x76, 0x88, 0x1f, 0x5d, 0xcc, 0xe2, 0x93,
	0x52, 0x9f, 0xdd, 0x55, 0xc8, 0x61, 0x76, 0x25, 0x8b, 0x9c, 0x42, 0x1f, 0x6f, 0x1c, 0x99, 0x9d,
	0x06, 0x21, 0xdb, 0x9b, 0x7d, 0x76, 0x9d, 0x2b, 0x57, 0xd7, 0xa0, 0xe3, 0x46, 0x80, 0x95, 0xb3,
	0xbc, 0xd2, 0x6d, 0xb1, 0x4a, 0xc0, 0xf5, 0xdd, 0x56, 0xf7, 0x9c, 0xc2, 0xad, 0xe5, 0x91, 0xf7,
	0xa1, 0x27, 0xd9, 0x8f, 0x6b, 0x96, 0x86, 0xb8, 0xfb, 0x46, 0x88, 0x53, 0x28, 0x58, 0xf3, 0xe8,
	0xa0, 0x03, 0x2d, 0xa6, 0x0d, 0x27, 0x13, 0x80, 0xcb, 0xbd, 0x96, 0x78, 0xd0, 0x5a, 0xd0, 0xb5,
	0x64, 0x7e, 0x83, 0x74, 0x61, 0x47, 0x0b, 0x7c, 0x87, 0x74, 0xc0, 0x3d, 0x4a, 0x23, 0xbf, 0x39,
	0xb9, 0x07, 0xdd, 0x62, 0x61, 0x24, 0x3d, 0xe8, 0x2c, 0x72, 0xbe, 0xa1, 0xca, 0xea, 0x3e, 0xc9,
	0x58, 0xea, 0x3b, 0x93, 0x07, 0x30, 0xb8, 0x32, 0xb9, 0xc8, 0x6d, 0x18, 0x1c, 0xb2, 0x73, 0xba,
	0x5e, 0x29, 0xc3, 0xf0, 0x1b, 0xda, 0x14, 0x61, 0xcb, 0x23, 0xdf, 0x21, 0x43, 0x80, 0x93, 0xad,
	0x54, 0x2c, 0xd1, 0xe3, 0xc1, 0x6f, 0x4e, 0x0e, 0xa0, 0x57, 0x99, 0x5a, 0xe4, 0x16, 0xf4, 0xac,
	0xb9, 0x26, 0xfd, 0x86, 0x66, 0xe8, 0x7e, 0x58, 0x1d, 0xdf, 0xd1, 0x01, 0x8c, 0x83, 0x82, 0xd5,
	0x9c, 0x4c, 0xa1, 0x57, 0xd9, 0xb5, 0x08, 0x81, 0x61, 0xe1, 0xc3, 0x70, 0xfd, 0x06, 0xe9, 0x43,
	0x37, 0x60, 0x2b, 0xaa, 0xb8, 0x48, 0x7d, 0xe7, 0xac, 0x8d, 0xff, 0xbd, 0xee, 0xff, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0xd4, 0x4f, 0x67, 0x80, 0xb2, 0x0d, 0x00, 0x00,
}
