// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_api/bilibili/rpc/status.proto

package bilibili_rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	anypb "google.golang.org/protobuf/types/known/anypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 响应gRPC Status
// 当status code是[UNKNOWN = 2]时，details为业务详细的错误信息，进行proto any转换成业务码结构体
type Status struct {
	// 业务错误码
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 业务错误信息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 扩展信息嵌套(相当于该messasge的套娃)
	Details              []*anypb.Any `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfbd0c673e768442, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Status) GetDetails() []*anypb.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

func init() {
	proto.RegisterType((*Status)(nil), "bilibili.rpc.Status")
}

func init() {
	proto.RegisterFile("grpc_api/bilibili/rpc/status.proto", fileDescriptor_dfbd0c673e768442)
}

var fileDescriptor_dfbd0c673e768442 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4a, 0x2f, 0x2a, 0x48,
	0x8e, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xca, 0xcc, 0xc9, 0x04, 0x61, 0xfd, 0xa2, 0x82, 0x64, 0xfd,
	0xe2, 0x92, 0xc4, 0x92, 0xd2, 0x62, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x21, 0x1e, 0x98, 0x94,
	0x5e, 0x51, 0x41, 0xb2, 0x94, 0x64, 0x7a, 0x7e, 0x7e, 0x7a, 0x4e, 0xaa, 0x3e, 0x58, 0x2e, 0xa9,
	0x34, 0x4d, 0x3f, 0x31, 0xaf, 0x12, 0xa2, 0x50, 0x29, 0x8d, 0x8b, 0x2d, 0x18, 0xac, 0x51, 0x48,
	0x88, 0x8b, 0x25, 0x39, 0x3f, 0x25, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x35, 0x08, 0xcc, 0x16,
	0x92, 0xe0, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0,
	0x0c, 0x82, 0x71, 0x85, 0xf4, 0xb8, 0xd8, 0x53, 0x52, 0x4b, 0x12, 0x33, 0x73, 0x8a, 0x25, 0x98,
	0x15, 0x98, 0x35, 0xb8, 0x8d, 0x44, 0xf4, 0x20, 0x96, 0xe8, 0xc1, 0x2c, 0xd1, 0x73, 0xcc, 0xab,
	0x0c, 0x82, 0x29, 0x4a, 0x62, 0x03, 0x0b, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x2e, 0xff,
	0x40, 0xf0, 0xbd, 0x00, 0x00, 0x00,
}
