// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_api/bilibili/broadcast/message/main/dm.proto

package bilibili_broadcast_message_main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 实时弹幕事件
type DanmukuEvent struct {
	// 弹幕列表
	Elems                []*DanmakuElem `protobuf:"bytes,1,rep,name=elems,proto3" json:"elems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DanmukuEvent) Reset()         { *m = DanmukuEvent{} }
func (m *DanmukuEvent) String() string { return proto.CompactTextString(m) }
func (*DanmukuEvent) ProtoMessage()    {}
func (*DanmukuEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_acce12eb9ec46f04, []int{0}
}

func (m *DanmukuEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DanmukuEvent.Unmarshal(m, b)
}
func (m *DanmukuEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DanmukuEvent.Marshal(b, m, deterministic)
}
func (m *DanmukuEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DanmukuEvent.Merge(m, src)
}
func (m *DanmukuEvent) XXX_Size() int {
	return xxx_messageInfo_DanmukuEvent.Size(m)
}
func (m *DanmukuEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_DanmukuEvent.DiscardUnknown(m)
}

var xxx_messageInfo_DanmukuEvent proto.InternalMessageInfo

func (m *DanmukuEvent) GetElems() []*DanmakuElem {
	if m != nil {
		return m.Elems
	}
	return nil
}

// 弹幕条目
type DanmakuElem struct {
	// 弹幕dmid
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 弹幕出现位置(单位为ms)
	Progress int32 `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	// 弹幕类型
	Mode int32 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	// 弹幕字号
	Fontsize int32 `protobuf:"varint,4,opt,name=fontsize,proto3" json:"fontsize,omitempty"`
	// 弹幕颜色
	Color uint32 `protobuf:"varint,5,opt,name=color,proto3" json:"color,omitempty"`
	// 发送着mid hash
	MidHash string `protobuf:"bytes,6,opt,name=mid_hash,json=midHash,proto3" json:"mid_hash,omitempty"`
	// 弹幕正文
	Content string `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	// 发送时间
	Ctime int64 `protobuf:"varint,8,opt,name=ctime,proto3" json:"ctime,omitempty"`
	// 弹幕动作
	Action string `protobuf:"bytes,9,opt,name=action,proto3" json:"action,omitempty"`
	// 弹幕池
	Pool int32 `protobuf:"varint,10,opt,name=pool,proto3" json:"pool,omitempty"`
	// 弹幕id str
	IdStr                string   `protobuf:"bytes,11,opt,name=id_str,json=idStr,proto3" json:"id_str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DanmakuElem) Reset()         { *m = DanmakuElem{} }
func (m *DanmakuElem) String() string { return proto.CompactTextString(m) }
func (*DanmakuElem) ProtoMessage()    {}
func (*DanmakuElem) Descriptor() ([]byte, []int) {
	return fileDescriptor_acce12eb9ec46f04, []int{1}
}

func (m *DanmakuElem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DanmakuElem.Unmarshal(m, b)
}
func (m *DanmakuElem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DanmakuElem.Marshal(b, m, deterministic)
}
func (m *DanmakuElem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DanmakuElem.Merge(m, src)
}
func (m *DanmakuElem) XXX_Size() int {
	return xxx_messageInfo_DanmakuElem.Size(m)
}
func (m *DanmakuElem) XXX_DiscardUnknown() {
	xxx_messageInfo_DanmakuElem.DiscardUnknown(m)
}

var xxx_messageInfo_DanmakuElem proto.InternalMessageInfo

func (m *DanmakuElem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DanmakuElem) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *DanmakuElem) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *DanmakuElem) GetFontsize() int32 {
	if m != nil {
		return m.Fontsize
	}
	return 0
}

func (m *DanmakuElem) GetColor() uint32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *DanmakuElem) GetMidHash() string {
	if m != nil {
		return m.MidHash
	}
	return ""
}

func (m *DanmakuElem) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *DanmakuElem) GetCtime() int64 {
	if m != nil {
		return m.Ctime
	}
	return 0
}

func (m *DanmakuElem) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *DanmakuElem) GetPool() int32 {
	if m != nil {
		return m.Pool
	}
	return 0
}

func (m *DanmakuElem) GetIdStr() string {
	if m != nil {
		return m.IdStr
	}
	return ""
}

// 互动弹幕
type CommandDm struct {
	// 弹幕id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 对象视频cid
	Oid int64 `protobuf:"varint,2,opt,name=oid,proto3" json:"oid,omitempty"`
	// 发送者mid
	Mid int64 `protobuf:"varint,3,opt,name=mid,proto3" json:"mid,omitempty"`
	//
	Type int32 `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	// 互动弹幕指令
	Command string `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	// 互动弹幕正文
	Content string `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	// 弹幕状态
	State int32 `protobuf:"varint,7,opt,name=state,proto3" json:"state,omitempty"`
	// 出现时间
	Progress int32 `protobuf:"varint,8,opt,name=progress,proto3" json:"progress,omitempty"`
	// 创建时间
	Ctime string `protobuf:"bytes,9,opt,name=ctime,proto3" json:"ctime,omitempty"`
	// 发布时间
	Mtime string `protobuf:"bytes,10,opt,name=mtime,proto3" json:"mtime,omitempty"`
	// 扩展json数据
	Extra string `protobuf:"bytes,11,opt,name=extra,proto3" json:"extra,omitempty"`
	// 弹幕id str类型
	IdStr                string   `protobuf:"bytes,12,opt,name=idStr,proto3" json:"idStr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandDm) Reset()         { *m = CommandDm{} }
func (m *CommandDm) String() string { return proto.CompactTextString(m) }
func (*CommandDm) ProtoMessage()    {}
func (*CommandDm) Descriptor() ([]byte, []int) {
	return fileDescriptor_acce12eb9ec46f04, []int{2}
}

func (m *CommandDm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandDm.Unmarshal(m, b)
}
func (m *CommandDm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandDm.Marshal(b, m, deterministic)
}
func (m *CommandDm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandDm.Merge(m, src)
}
func (m *CommandDm) XXX_Size() int {
	return xxx_messageInfo_CommandDm.Size(m)
}
func (m *CommandDm) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandDm.DiscardUnknown(m)
}

var xxx_messageInfo_CommandDm proto.InternalMessageInfo

func (m *CommandDm) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CommandDm) GetOid() int64 {
	if m != nil {
		return m.Oid
	}
	return 0
}

func (m *CommandDm) GetMid() int64 {
	if m != nil {
		return m.Mid
	}
	return 0
}

func (m *CommandDm) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *CommandDm) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *CommandDm) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CommandDm) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *CommandDm) GetProgress() int32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *CommandDm) GetCtime() string {
	if m != nil {
		return m.Ctime
	}
	return ""
}

func (m *CommandDm) GetMtime() string {
	if m != nil {
		return m.Mtime
	}
	return ""
}

func (m *CommandDm) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func (m *CommandDm) GetIdStr() string {
	if m != nil {
		return m.IdStr
	}
	return ""
}

func init() {
	proto.RegisterType((*DanmukuEvent)(nil), "bilibili.broadcast.message.main.DanmukuEvent")
	proto.RegisterType((*DanmakuElem)(nil), "bilibili.broadcast.message.main.DanmakuElem")
	proto.RegisterType((*CommandDm)(nil), "bilibili.broadcast.message.main.CommandDm")
}

func init() {
	proto.RegisterFile("grpc_api/bilibili/broadcast/message/main/dm.proto", fileDescriptor_acce12eb9ec46f04)
}

var fileDescriptor_acce12eb9ec46f04 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xc1, 0x8e, 0xd3, 0x30,
	0x14, 0x54, 0x92, 0x4d, 0x9a, 0xbe, 0x2e, 0x08, 0x59, 0x0b, 0x32, 0x5c, 0x88, 0x7a, 0xca, 0x01,
	0x25, 0x02, 0xfe, 0x00, 0x76, 0x25, 0xce, 0xe6, 0x03, 0x2a, 0x37, 0x36, 0xad, 0xb5, 0xb1, 0x1d,
	0xd9, 0x2e, 0x02, 0xfe, 0x81, 0x03, 0x7f, 0x8c, 0xfc, 0x9c, 0x54, 0x85, 0x1e, 0xf6, 0x10, 0x69,
	0x66, 0x32, 0x7e, 0x79, 0x33, 0x0e, 0xbc, 0x3f, 0xb8, 0x69, 0xd8, 0xf1, 0x49, 0xf5, 0x7b, 0x35,
	0xaa, 0xf8, 0xf4, 0x7b, 0x67, 0xb9, 0x18, 0xb8, 0x0f, 0xbd, 0x96, 0xde, 0xf3, 0x83, 0xec, 0x35,
	0x57, 0xa6, 0x17, 0xba, 0x9b, 0x9c, 0x0d, 0x96, 0xbc, 0x5d, 0x9c, 0xdd, 0xd9, 0xd9, 0xcd, 0xce,
	0x2e, 0x3a, 0xb7, 0x0c, 0x6e, 0xef, 0xb9, 0xd1, 0xa7, 0xc7, 0xd3, 0xc3, 0x77, 0x69, 0x02, 0xf9,
	0x04, 0xa5, 0x1c, 0xa5, 0xf6, 0x34, 0x6b, 0x8a, 0x76, 0xf3, 0xe1, 0x5d, 0xf7, 0xc4, 0x80, 0x2e,
	0x9e, 0xe6, 0x8f, 0xa7, 0x87, 0x51, 0x6a, 0x96, 0x8e, 0x6e, 0x7f, 0xe7, 0xb0, 0xb9, 0x90, 0xc9,
	0x73, 0xc8, 0x95, 0xa0, 0x59, 0x93, 0xb5, 0x05, 0xcb, 0x95, 0x20, 0x6f, 0xa0, 0x9e, 0x9c, 0x3d,
	0x38, 0xe9, 0x3d, 0xcd, 0x9b, 0xac, 0x2d, 0xd9, 0x99, 0x13, 0x02, 0x37, 0xda, 0x0a, 0x49, 0x0b,
	0xd4, 0x11, 0x47, 0xff, 0x37, 0x6b, 0x82, 0x57, 0xbf, 0x24, 0xbd, 0x49, 0xfe, 0x85, 0x93, 0x3b,
	0x28, 0x07, 0x3b, 0x5a, 0x47, 0xcb, 0x26, 0x6b, 0x9f, 0xb1, 0x44, 0xc8, 0x6b, 0xa8, 0xb5, 0x12,
	0xbb, 0x23, 0xf7, 0x47, 0x5a, 0x35, 0x59, 0xbb, 0x66, 0x2b, 0xad, 0xc4, 0x17, 0xee, 0x8f, 0x84,
	0xc2, 0x6a, 0xb0, 0x26, 0x48, 0x13, 0xe8, 0x2a, 0xbd, 0x99, 0x29, 0x8e, 0x0a, 0x4a, 0x4b, 0x5a,
	0xe3, 0xa6, 0x89, 0x90, 0x57, 0x50, 0xf1, 0x21, 0x28, 0x6b, 0xe8, 0x1a, 0xed, 0x33, 0x8b, 0x8b,
	0x4e, 0xd6, 0x8e, 0x14, 0xd2, 0xa2, 0x11, 0x93, 0x97, 0x50, 0x29, 0xb1, 0xf3, 0xc1, 0xd1, 0x0d,
	0x7a, 0x4b, 0x25, 0xbe, 0x06, 0xb7, 0xfd, 0x93, 0xc3, 0xfa, 0xb3, 0xd5, 0x9a, 0x1b, 0x71, 0x7f,
	0xdd, 0xc6, 0x0b, 0x28, 0xac, 0x12, 0x58, 0x44, 0xc1, 0x22, 0x8c, 0x8a, 0x56, 0x02, 0x2b, 0x28,
	0x58, 0x84, 0xf1, 0x63, 0xe1, 0xe7, 0xb4, 0xa4, 0x47, 0x9c, 0x82, 0xe0, 0x50, 0xcc, 0x8e, 0x41,
	0x90, 0x5e, 0x46, 0xac, 0xae, 0x22, 0xfa, 0xc0, 0x83, 0xc4, 0xe8, 0x25, 0x4b, 0xe4, 0x9f, 0xfb,
	0xa8, 0xff, 0xbb, 0x8f, 0x73, 0x29, 0x29, 0xfd, 0x5c, 0xca, 0x1d, 0x94, 0x1a, 0x55, 0x48, 0xaa,
	0x5e, 0x54, 0xf9, 0x23, 0x38, 0xbe, 0xa4, 0x47, 0x12, 0x55, 0xac, 0x81, 0xde, 0x5e, 0x74, 0xb2,
	0xaf, 0xf0, 0xff, 0xfc, 0xf8, 0x37, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x49, 0x02, 0x05, 0xd4, 0x02,
	0x00, 0x00,
}
