// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_api/bilibili/app/archive/middleware/v1/preload.proto

package bilibili_app_archive_middleware_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 视频秒开参数
type PlayerArgs struct {
	// 清晰度
	Qn int64 `protobuf:"varint,1,opt,name=qn,proto3" json:"qn,omitempty"`
	// 流版本
	Fnver int64 `protobuf:"varint,2,opt,name=fnver,proto3" json:"fnver,omitempty"`
	// 流类型
	Fnval int64 `protobuf:"varint,3,opt,name=fnval,proto3" json:"fnval,omitempty"`
	// 返回url是否强制使用域名
	// 0:不强制使用域名 1:http域名 2:https域名
	ForceHost            int64    `protobuf:"varint,4,opt,name=force_host,json=forceHost,proto3" json:"force_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerArgs) Reset()         { *m = PlayerArgs{} }
func (m *PlayerArgs) String() string { return proto.CompactTextString(m) }
func (*PlayerArgs) ProtoMessage()    {}
func (*PlayerArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f2b964113a86d06, []int{0}
}

func (m *PlayerArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerArgs.Unmarshal(m, b)
}
func (m *PlayerArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerArgs.Marshal(b, m, deterministic)
}
func (m *PlayerArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerArgs.Merge(m, src)
}
func (m *PlayerArgs) XXX_Size() int {
	return xxx_messageInfo_PlayerArgs.Size(m)
}
func (m *PlayerArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerArgs.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerArgs proto.InternalMessageInfo

func (m *PlayerArgs) GetQn() int64 {
	if m != nil {
		return m.Qn
	}
	return 0
}

func (m *PlayerArgs) GetFnver() int64 {
	if m != nil {
		return m.Fnver
	}
	return 0
}

func (m *PlayerArgs) GetFnval() int64 {
	if m != nil {
		return m.Fnval
	}
	return 0
}

func (m *PlayerArgs) GetForceHost() int64 {
	if m != nil {
		return m.ForceHost
	}
	return 0
}

func init() {
	proto.RegisterType((*PlayerArgs)(nil), "bilibili.app.archive.middleware.v1.PlayerArgs")
}

func init() {
	proto.RegisterFile("grpc_api/bilibili/app/archive/middleware/v1/preload.proto", fileDescriptor_4f2b964113a86d06)
}

var fileDescriptor_4f2b964113a86d06 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xce, 0x31, 0xab, 0xc2, 0x30,
	0x10, 0xc0, 0x71, 0xda, 0xbe, 0xf7, 0xe0, 0x65, 0x70, 0x08, 0x0e, 0x59, 0x04, 0xe9, 0xe4, 0x94,
	0x50, 0x9c, 0x1c, 0xdd, 0x1c, 0xc5, 0x2f, 0x50, 0xae, 0xed, 0xb5, 0x0d, 0xc4, 0xe6, 0x7a, 0x2d,
	0x11, 0xbf, 0xbd, 0x18, 0xab, 0x0e, 0x37, 0xdc, 0xef, 0xf8, 0xc3, 0x89, 0x43, 0xc7, 0x54, 0x97,
	0x40, 0xd6, 0x54, 0xd6, 0xd9, 0xe7, 0x18, 0x20, 0x32, 0xc0, 0x75, 0x6f, 0x03, 0x9a, 0xab, 0x6d,
	0x1a, 0x87, 0x37, 0x60, 0x34, 0xa1, 0x30, 0xc4, 0xe8, 0x3c, 0x34, 0x9a, 0xd8, 0xcf, 0x5e, 0xe6,
	0xef, 0x42, 0x03, 0x91, 0x5e, 0x0a, 0xfd, 0x2d, 0x74, 0x28, 0xf2, 0x4e, 0x88, 0xb3, 0x83, 0x3b,
	0xf2, 0x91, 0xbb, 0x49, 0xae, 0x44, 0x3a, 0x0e, 0x2a, 0xd9, 0x26, 0xbb, 0xec, 0x92, 0x8e, 0x83,
	0x5c, 0x8b, 0xdf, 0x76, 0x08, 0xc8, 0x2a, 0x8d, 0xf4, 0x5a, 0x16, 0x05, 0xa7, 0xb2, 0x8f, 0x82,
	0x93, 0x1b, 0x21, 0x5a, 0xcf, 0x35, 0x96, 0xbd, 0x9f, 0x66, 0xf5, 0x13, 0x4f, 0xff, 0x51, 0x4e,
	0x7e, 0x9a, 0xab, 0xbf, 0xf8, 0xd3, 0xfe, 0x11, 0x00, 0x00, 0xff, 0xff, 0x07, 0x85, 0xb5, 0x83,
	0xd0, 0x00, 0x00, 0x00,
}
