// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_api/bilibili/app/wall/v1/wall.proto

package bilibili_app_wall_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 免流规则信息
type RuleInfo struct {
	// 是否支持免流
	Tf bool `protobuf:"varint,1,opt,name=tf,proto3" json:"tf,omitempty"`
	// 操作模式
	// break:无 replace:替换 proxy:代理
	M string `protobuf:"bytes,2,opt,name=m,proto3" json:"m,omitempty"`
	// 操作参数
	A string `protobuf:"bytes,3,opt,name=a,proto3" json:"a,omitempty"`
	// 匹配目标正则
	P string `protobuf:"bytes,4,opt,name=p,proto3" json:"p,omitempty"`
	//
	ABackup              []string `protobuf:"bytes,5,rep,name=a_backup,json=aBackup,proto3" json:"a_backup,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RuleInfo) Reset()         { *m = RuleInfo{} }
func (m *RuleInfo) String() string { return proto.CompactTextString(m) }
func (*RuleInfo) ProtoMessage()    {}
func (*RuleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_912ced6ea1e62d28, []int{0}
}

func (m *RuleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuleInfo.Unmarshal(m, b)
}
func (m *RuleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuleInfo.Marshal(b, m, deterministic)
}
func (m *RuleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuleInfo.Merge(m, src)
}
func (m *RuleInfo) XXX_Size() int {
	return xxx_messageInfo_RuleInfo.Size(m)
}
func (m *RuleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RuleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RuleInfo proto.InternalMessageInfo

func (m *RuleInfo) GetTf() bool {
	if m != nil {
		return m.Tf
	}
	return false
}

func (m *RuleInfo) GetM() string {
	if m != nil {
		return m.M
	}
	return ""
}

func (m *RuleInfo) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

func (m *RuleInfo) GetP() string {
	if m != nil {
		return m.P
	}
	return ""
}

func (m *RuleInfo) GetABackup() []string {
	if m != nil {
		return m.ABackup
	}
	return nil
}

// 获取免流规则信息-请求
type RuleRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RuleRequest) Reset()         { *m = RuleRequest{} }
func (m *RuleRequest) String() string { return proto.CompactTextString(m) }
func (*RuleRequest) ProtoMessage()    {}
func (*RuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_912ced6ea1e62d28, []int{1}
}

func (m *RuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RuleRequest.Unmarshal(m, b)
}
func (m *RuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RuleRequest.Marshal(b, m, deterministic)
}
func (m *RuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RuleRequest.Merge(m, src)
}
func (m *RuleRequest) XXX_Size() int {
	return xxx_messageInfo_RuleRequest.Size(m)
}
func (m *RuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RuleRequest proto.InternalMessageInfo

// 免流规则信息组
type RulesInfo struct {
	// 免流规则信息
	RulesInfo            []*RuleInfo `protobuf:"bytes,1,rep,name=rulesInfo,proto3" json:"rulesInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RulesInfo) Reset()         { *m = RulesInfo{} }
func (m *RulesInfo) String() string { return proto.CompactTextString(m) }
func (*RulesInfo) ProtoMessage()    {}
func (*RulesInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_912ced6ea1e62d28, []int{2}
}

func (m *RulesInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RulesInfo.Unmarshal(m, b)
}
func (m *RulesInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RulesInfo.Marshal(b, m, deterministic)
}
func (m *RulesInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RulesInfo.Merge(m, src)
}
func (m *RulesInfo) XXX_Size() int {
	return xxx_messageInfo_RulesInfo.Size(m)
}
func (m *RulesInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RulesInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RulesInfo proto.InternalMessageInfo

func (m *RulesInfo) GetRulesInfo() []*RuleInfo {
	if m != nil {
		return m.RulesInfo
	}
	return nil
}

// 获取免流规则信息-响应
type RulesReply struct {
	// 各ISP的免流规则信息组
	// ISP如: cu ct cm
	RulesInfo map[string]*RulesInfo `protobuf:"bytes,1,rep,name=rulesInfo,proto3" json:"rulesInfo,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	//
	HashValue            string   `protobuf:"bytes,2,opt,name=hash_value,json=hashValue,proto3" json:"hash_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RulesReply) Reset()         { *m = RulesReply{} }
func (m *RulesReply) String() string { return proto.CompactTextString(m) }
func (*RulesReply) ProtoMessage()    {}
func (*RulesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_912ced6ea1e62d28, []int{3}
}

func (m *RulesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RulesReply.Unmarshal(m, b)
}
func (m *RulesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RulesReply.Marshal(b, m, deterministic)
}
func (m *RulesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RulesReply.Merge(m, src)
}
func (m *RulesReply) XXX_Size() int {
	return xxx_messageInfo_RulesReply.Size(m)
}
func (m *RulesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RulesReply.DiscardUnknown(m)
}

var xxx_messageInfo_RulesReply proto.InternalMessageInfo

func (m *RulesReply) GetRulesInfo() map[string]*RulesInfo {
	if m != nil {
		return m.RulesInfo
	}
	return nil
}

func (m *RulesReply) GetHashValue() string {
	if m != nil {
		return m.HashValue
	}
	return ""
}

func init() {
	proto.RegisterType((*RuleInfo)(nil), "bilibili.app.wall.v1.RuleInfo")
	proto.RegisterType((*RuleRequest)(nil), "bilibili.app.wall.v1.RuleRequest")
	proto.RegisterType((*RulesInfo)(nil), "bilibili.app.wall.v1.RulesInfo")
	proto.RegisterType((*RulesReply)(nil), "bilibili.app.wall.v1.RulesReply")
	proto.RegisterMapType((map[string]*RulesInfo)(nil), "bilibili.app.wall.v1.RulesReply.RulesInfoEntry")
}

func init() {
	proto.RegisterFile("grpc_api/bilibili/app/wall/v1/wall.proto", fileDescriptor_912ced6ea1e62d28)
}

var fileDescriptor_912ced6ea1e62d28 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x41, 0x4b, 0x33, 0x31,
	0x10, 0x25, 0xbb, 0xed, 0xf7, 0x35, 0x53, 0x2d, 0x12, 0x3c, 0xc4, 0x82, 0xba, 0xee, 0x69, 0x4f,
	0x59, 0x5a, 0x11, 0x44, 0x3c, 0x09, 0x1e, 0x7a, 0x10, 0x21, 0x07, 0x7b, 0x92, 0x65, 0x5a, 0x52,
	0x5b, 0x9a, 0xb6, 0x71, 0xbb, 0xbb, 0xb2, 0x3f, 0xd5, 0x7f, 0x23, 0xc9, 0x76, 0x6d, 0x45, 0xab,
	0x87, 0x90, 0xbc, 0xc9, 0xbc, 0x37, 0x6f, 0x26, 0x81, 0xe8, 0x25, 0x35, 0xe3, 0x04, 0xcd, 0x2c,
	0x1e, 0xcd, 0xf4, 0xcc, 0xae, 0x18, 0x8d, 0x89, 0xdf, 0x50, 0xeb, 0xb8, 0xe8, 0xb9, 0x5d, 0x98,
	0x74, 0x95, 0xad, 0xd8, 0x71, 0x9d, 0x20, 0xd0, 0x18, 0xe1, 0x2e, 0x8a, 0x5e, 0x98, 0x40, 0x4b,
	0xe6, 0x5a, 0x0d, 0x96, 0x93, 0x15, 0xeb, 0x80, 0x97, 0x4d, 0x38, 0x09, 0x48, 0xd4, 0x92, 0x5e,
	0x36, 0x61, 0x07, 0x40, 0x16, 0xdc, 0x0b, 0x48, 0x44, 0x25, 0x59, 0x58, 0x84, 0xdc, 0xaf, 0x10,
	0x5a, 0x64, 0x78, 0xa3, 0x42, 0x86, 0x9d, 0x40, 0x0b, 0x93, 0x11, 0x8e, 0xe7, 0xb9, 0xe1, 0xcd,
	0xc0, 0x8f, 0xa8, 0xfc, 0x8f, 0x77, 0x0e, 0x86, 0x87, 0xd0, 0xb6, 0x05, 0xa4, 0x7a, 0xcd, 0xd5,
	0x3a, 0x0b, 0x07, 0x40, 0x2d, 0x5c, 0xbb, 0x82, 0xb7, 0x40, 0xd3, 0x1a, 0x70, 0x12, 0xf8, 0x51,
	0xbb, 0x7f, 0x26, 0x7e, 0xb2, 0x29, 0x6a, 0x8f, 0x72, 0x4b, 0x08, 0xdf, 0x09, 0x80, 0xd3, 0x92,
	0xca, 0xe8, 0x92, 0x3d, 0x7c, 0x17, 0x8b, 0xf7, 0x8b, 0x55, 0x24, 0xf1, 0xe9, 0xe5, 0x7e, 0x99,
	0xa5, 0xe5, 0x8e, 0x3a, 0x3b, 0x05, 0x98, 0xe2, 0x7a, 0x9a, 0x14, 0xa8, 0x73, 0xb5, 0x99, 0x02,
	0xb5, 0x91, 0x27, 0x1b, 0xe8, 0x3e, 0x43, 0xe7, 0x2b, 0x97, 0x1d, 0x81, 0x3f, 0x57, 0xa5, 0x1b,
	0x1f, 0x95, 0xf6, 0xc8, 0xae, 0xa0, 0xb9, 0x65, 0xb7, 0xfb, 0xe7, 0xbf, 0xb8, 0x71, 0xbd, 0x55,
	0xd9, 0x37, 0xde, 0x35, 0xe9, 0x0f, 0xa1, 0x31, 0x44, 0xad, 0xd9, 0xe3, 0xce, 0xf3, 0x5c, 0xec,
	0xe7, 0x6f, 0xa6, 0xdb, 0x0d, 0xfe, 0x6a, 0x78, 0xf4, 0xcf, 0x7d, 0x86, 0xcb, 0x8f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xbc, 0x71, 0xe7, 0x2e, 0x38, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WallClient is the client API for Wall service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WallClient interface {
	// 获取免流规则信息
	RuleInfo(ctx context.Context, in *RuleRequest, opts ...grpc.CallOption) (*RulesReply, error)
}

type wallClient struct {
	cc *grpc.ClientConn
}

func NewWallClient(cc *grpc.ClientConn) WallClient {
	return &wallClient{cc}
}

func (c *wallClient) RuleInfo(ctx context.Context, in *RuleRequest, opts ...grpc.CallOption) (*RulesReply, error) {
	out := new(RulesReply)
	err := c.cc.Invoke(ctx, "/bilibili.app.wall.v1.Wall/RuleInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WallServer is the server API for Wall service.
type WallServer interface {
	// 获取免流规则信息
	RuleInfo(context.Context, *RuleRequest) (*RulesReply, error)
}

// UnimplementedWallServer can be embedded to have forward compatible implementations.
type UnimplementedWallServer struct {
}

func (*UnimplementedWallServer) RuleInfo(ctx context.Context, req *RuleRequest) (*RulesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RuleInfo not implemented")
}

func RegisterWallServer(s *grpc.Server, srv WallServer) {
	s.RegisterService(&_Wall_serviceDesc, srv)
}

func _Wall_RuleInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WallServer).RuleInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bilibili.app.wall.v1.Wall/RuleInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WallServer).RuleInfo(ctx, req.(*RuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wall_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bilibili.app.wall.v1.Wall",
	HandlerType: (*WallServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RuleInfo",
			Handler:    _Wall_RuleInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_api/bilibili/app/wall/v1/wall.proto",
}
