// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_api/bilibili/metadata/restriction/restriction.proto

package bilibili_metadata_restriction

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 模式类型
type ModeType int32

const (
	ModeType_NORMAL    ModeType = 0
	ModeType_TEENAGERS ModeType = 1
	ModeType_LESSONS   ModeType = 2
)

var ModeType_name = map[int32]string{
	0: "NORMAL",
	1: "TEENAGERS",
	2: "LESSONS",
}

var ModeType_value = map[string]int32{
	"NORMAL":    0,
	"TEENAGERS": 1,
	"LESSONS":   2,
}

func (x ModeType) String() string {
	return proto.EnumName(ModeType_name, int32(x))
}

func (ModeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_db6e2e3acb52997d, []int{0}
}

// 限制条件
type Restriction struct {
	// 青少年模式开关状态
	TeenagersMode bool `protobuf:"varint,1,opt,name=teenagers_mode,json=teenagersMode,proto3" json:"teenagers_mode,omitempty"`
	// 课堂模式开关状态
	LessonsMode bool `protobuf:"varint,2,opt,name=lessons_mode,json=lessonsMode,proto3" json:"lessons_mode,omitempty"`
	// 模式类型(旧版)
	Mode ModeType `protobuf:"varint,3,opt,name=mode,proto3,enum=bilibili.metadata.restriction.ModeType" json:"mode,omitempty"`
	// app 审核review状态
	Review bool `protobuf:"varint,4,opt,name=review,proto3" json:"review,omitempty"`
	//
	DisableRcmd          bool     `protobuf:"varint,5,opt,name=disable_rcmd,json=disableRcmd,proto3" json:"disable_rcmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Restriction) Reset()         { *m = Restriction{} }
func (m *Restriction) String() string { return proto.CompactTextString(m) }
func (*Restriction) ProtoMessage()    {}
func (*Restriction) Descriptor() ([]byte, []int) {
	return fileDescriptor_db6e2e3acb52997d, []int{0}
}

func (m *Restriction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Restriction.Unmarshal(m, b)
}
func (m *Restriction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Restriction.Marshal(b, m, deterministic)
}
func (m *Restriction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Restriction.Merge(m, src)
}
func (m *Restriction) XXX_Size() int {
	return xxx_messageInfo_Restriction.Size(m)
}
func (m *Restriction) XXX_DiscardUnknown() {
	xxx_messageInfo_Restriction.DiscardUnknown(m)
}

var xxx_messageInfo_Restriction proto.InternalMessageInfo

func (m *Restriction) GetTeenagersMode() bool {
	if m != nil {
		return m.TeenagersMode
	}
	return false
}

func (m *Restriction) GetLessonsMode() bool {
	if m != nil {
		return m.LessonsMode
	}
	return false
}

func (m *Restriction) GetMode() ModeType {
	if m != nil {
		return m.Mode
	}
	return ModeType_NORMAL
}

func (m *Restriction) GetReview() bool {
	if m != nil {
		return m.Review
	}
	return false
}

func (m *Restriction) GetDisableRcmd() bool {
	if m != nil {
		return m.DisableRcmd
	}
	return false
}

func init() {
	proto.RegisterEnum("bilibili.metadata.restriction.ModeType", ModeType_name, ModeType_value)
	proto.RegisterType((*Restriction)(nil), "bilibili.metadata.restriction.Restriction")
}

func init() {
	proto.RegisterFile("grpc_api/bilibili/metadata/restriction/restriction.proto", fileDescriptor_db6e2e3acb52997d)
}

var fileDescriptor_db6e2e3acb52997d = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xcd, 0x9c, 0x75, 0xbe, 0xba, 0x51, 0x72, 0x90, 0x5e, 0x84, 0x29, 0x88, 0xc3, 0x43,
	0x0a, 0xf3, 0x22, 0x78, 0xda, 0xa1, 0x78, 0xd9, 0x3a, 0x48, 0x77, 0x2f, 0x69, 0xf3, 0x18, 0x81,
	0xb6, 0x29, 0x49, 0x50, 0xfc, 0x94, 0x7e, 0x25, 0x69, 0x6c, 0x75, 0x27, 0x0f, 0x81, 0xbc, 0x7f,
	0x7e, 0xbf, 0xf7, 0xc2, 0x83, 0x97, 0xa3, 0xe9, 0xaa, 0x42, 0x74, 0x2a, 0x29, 0x55, 0xad, 0xfa,
	0x93, 0x34, 0xe8, 0x84, 0x14, 0x4e, 0x24, 0x06, 0xad, 0x33, 0xaa, 0x72, 0x4a, 0xb7, 0xa7, 0x77,
	0xd6, 0x19, 0xed, 0x34, 0xbd, 0x1d, 0x05, 0x36, 0x0a, 0xec, 0x04, 0xba, 0xff, 0x22, 0x10, 0xf2,
	0xbf, 0x9a, 0x3e, 0xc0, 0xc2, 0x21, 0xb6, 0xe2, 0x88, 0xc6, 0x16, 0x8d, 0x96, 0x18, 0x93, 0x25,
	0x59, 0xcd, 0xf8, 0xfc, 0x37, 0xdd, 0x69, 0x89, 0xf4, 0x0e, 0xae, 0x6b, 0xb4, 0x56, 0xb7, 0x03,
	0x34, 0xf1, 0x50, 0x38, 0x64, 0x1e, 0x79, 0x85, 0xa9, 0x7f, 0x3a, 0x5f, 0x92, 0xd5, 0x62, 0xfd,
	0xc8, 0xfe, 0xfd, 0x07, 0xeb, 0x95, 0xc3, 0x67, 0x87, 0xdc, 0x4b, 0xf4, 0x06, 0x02, 0x83, 0xef,
	0x0a, 0x3f, 0xe2, 0xa9, 0xef, 0x3c, 0x54, 0xfd, 0x5c, 0xa9, 0xac, 0x28, 0x6b, 0x2c, 0x4c, 0xd5,
	0xc8, 0xf8, 0xe2, 0x67, 0xee, 0x90, 0xf1, 0xaa, 0x91, 0x4f, 0x6b, 0x98, 0x8d, 0xcd, 0x28, 0x40,
	0x90, 0xed, 0xf9, 0x6e, 0xb3, 0x8d, 0xce, 0xe8, 0x1c, 0xae, 0x0e, 0x69, 0x9a, 0x6d, 0xde, 0x52,
	0x9e, 0x47, 0x84, 0x86, 0x70, 0xb9, 0x4d, 0xf3, 0x7c, 0x9f, 0xe5, 0xd1, 0xa4, 0x0c, 0xfc, 0xae,
	0x9e, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xa8, 0x62, 0xc3, 0x67, 0x01, 0x00, 0x00,
}
