// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_api/bilibili/account/fission/v1/fission.proto

package bilibili_account_fission_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 活动入口-请求
type EntranceReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EntranceReq) Reset()         { *m = EntranceReq{} }
func (m *EntranceReq) String() string { return proto.CompactTextString(m) }
func (*EntranceReq) ProtoMessage()    {}
func (*EntranceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8552b96c997037b0, []int{0}
}

func (m *EntranceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntranceReq.Unmarshal(m, b)
}
func (m *EntranceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntranceReq.Marshal(b, m, deterministic)
}
func (m *EntranceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntranceReq.Merge(m, src)
}
func (m *EntranceReq) XXX_Size() int {
	return xxx_messageInfo_EntranceReq.Size(m)
}
func (m *EntranceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EntranceReq.DiscardUnknown(m)
}

var xxx_messageInfo_EntranceReq proto.InternalMessageInfo

// 活动入口-响应
type EntranceReply struct {
	// 展示图标
	Icon string `protobuf:"bytes,1,opt,name=icon,proto3" json:"icon,omitempty"`
	// 活动名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 活动跳转链接
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// 动画效果
	AnimateIcon          *AnimateIcon `protobuf:"bytes,4,opt,name=animate_icon,json=animateIcon,proto3" json:"animate_icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EntranceReply) Reset()         { *m = EntranceReply{} }
func (m *EntranceReply) String() string { return proto.CompactTextString(m) }
func (*EntranceReply) ProtoMessage()    {}
func (*EntranceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8552b96c997037b0, []int{1}
}

func (m *EntranceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EntranceReply.Unmarshal(m, b)
}
func (m *EntranceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EntranceReply.Marshal(b, m, deterministic)
}
func (m *EntranceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EntranceReply.Merge(m, src)
}
func (m *EntranceReply) XXX_Size() int {
	return xxx_messageInfo_EntranceReply.Size(m)
}
func (m *EntranceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EntranceReply.DiscardUnknown(m)
}

var xxx_messageInfo_EntranceReply proto.InternalMessageInfo

func (m *EntranceReply) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *EntranceReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EntranceReply) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *EntranceReply) GetAnimateIcon() *AnimateIcon {
	if m != nil {
		return m.AnimateIcon
	}
	return nil
}

// 首页弹窗-请求
type WindowReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WindowReq) Reset()         { *m = WindowReq{} }
func (m *WindowReq) String() string { return proto.CompactTextString(m) }
func (*WindowReq) ProtoMessage()    {}
func (*WindowReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8552b96c997037b0, []int{2}
}

func (m *WindowReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WindowReq.Unmarshal(m, b)
}
func (m *WindowReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WindowReq.Marshal(b, m, deterministic)
}
func (m *WindowReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WindowReq.Merge(m, src)
}
func (m *WindowReq) XXX_Size() int {
	return xxx_messageInfo_WindowReq.Size(m)
}
func (m *WindowReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WindowReq.DiscardUnknown(m)
}

var xxx_messageInfo_WindowReq proto.InternalMessageInfo

//首页弹窗-响应
type WindowReply struct {
	// 弹窗类型
	// 0:弹窗 1:普通页面
	Type int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	// 跳转链接
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// 上报数据字段
	ReportData           string   `protobuf:"bytes,3,opt,name=report_data,json=reportData,proto3" json:"report_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WindowReply) Reset()         { *m = WindowReply{} }
func (m *WindowReply) String() string { return proto.CompactTextString(m) }
func (*WindowReply) ProtoMessage()    {}
func (*WindowReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8552b96c997037b0, []int{3}
}

func (m *WindowReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WindowReply.Unmarshal(m, b)
}
func (m *WindowReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WindowReply.Marshal(b, m, deterministic)
}
func (m *WindowReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WindowReply.Merge(m, src)
}
func (m *WindowReply) XXX_Size() int {
	return xxx_messageInfo_WindowReply.Size(m)
}
func (m *WindowReply) XXX_DiscardUnknown() {
	xxx_messageInfo_WindowReply.DiscardUnknown(m)
}

var xxx_messageInfo_WindowReply proto.InternalMessageInfo

func (m *WindowReply) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *WindowReply) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *WindowReply) GetReportData() string {
	if m != nil {
		return m.ReportData
	}
	return ""
}

//动画效果
type AnimateIcon struct {
	// icon文件
	Icon string `protobuf:"bytes,1,opt,name=icon,proto3" json:"icon,omitempty"`
	// 动效json文件
	Json                 string   `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnimateIcon) Reset()         { *m = AnimateIcon{} }
func (m *AnimateIcon) String() string { return proto.CompactTextString(m) }
func (*AnimateIcon) ProtoMessage()    {}
func (*AnimateIcon) Descriptor() ([]byte, []int) {
	return fileDescriptor_8552b96c997037b0, []int{4}
}

func (m *AnimateIcon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimateIcon.Unmarshal(m, b)
}
func (m *AnimateIcon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimateIcon.Marshal(b, m, deterministic)
}
func (m *AnimateIcon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimateIcon.Merge(m, src)
}
func (m *AnimateIcon) XXX_Size() int {
	return xxx_messageInfo_AnimateIcon.Size(m)
}
func (m *AnimateIcon) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimateIcon.DiscardUnknown(m)
}

var xxx_messageInfo_AnimateIcon proto.InternalMessageInfo

func (m *AnimateIcon) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *AnimateIcon) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

func init() {
	proto.RegisterType((*EntranceReq)(nil), "bilibili.account.fission.v1.EntranceReq")
	proto.RegisterType((*EntranceReply)(nil), "bilibili.account.fission.v1.EntranceReply")
	proto.RegisterType((*WindowReq)(nil), "bilibili.account.fission.v1.WindowReq")
	proto.RegisterType((*WindowReply)(nil), "bilibili.account.fission.v1.WindowReply")
	proto.RegisterType((*AnimateIcon)(nil), "bilibili.account.fission.v1.AnimateIcon")
}

func init() {
	proto.RegisterFile("grpc_api/bilibili/account/fission/v1/fission.proto", fileDescriptor_8552b96c997037b0)
}

var fileDescriptor_8552b96c997037b0 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4a, 0xc3, 0x30,
	0x1c, 0xc6, 0xe9, 0x36, 0xa7, 0xfb, 0xc7, 0x81, 0xe4, 0x54, 0xe6, 0xc1, 0xd1, 0x83, 0x14, 0x0f,
	0x2d, 0xab, 0xf8, 0x00, 0x82, 0x0a, 0xe2, 0xad, 0x08, 0x82, 0x97, 0x9a, 0x65, 0x51, 0x22, 0x5d,
	0x12, 0xd3, 0x6c, 0xd2, 0x17, 0xf1, 0x95, 0x7c, 0x2d, 0x49, 0xda, 0xd8, 0x5d, 0x56, 0x76, 0x28,
	0x7c, 0xff, 0xaf, 0x5f, 0xda, 0xdf, 0xf7, 0x27, 0x90, 0x7d, 0x68, 0x45, 0x0b, 0xa2, 0x78, 0xba,
	0xe4, 0x25, 0xb7, 0x4f, 0x4a, 0x28, 0x95, 0x1b, 0x61, 0xd2, 0x77, 0x5e, 0x55, 0x5c, 0x8a, 0x74,
	0xbb, 0xf0, 0x32, 0x51, 0x5a, 0x1a, 0x89, 0xcf, 0x7d, 0x34, 0x69, 0xa3, 0x89, 0x7f, 0xbf, 0x5d,
	0x44, 0x53, 0x40, 0xf7, 0xc2, 0x68, 0x22, 0x28, 0xcb, 0xd9, 0x57, 0xf4, 0x13, 0xc0, 0xb4, 0x9b,
	0x55, 0x59, 0x63, 0x0c, 0x23, 0x4e, 0xa5, 0x08, 0x83, 0x79, 0x10, 0x4f, 0x72, 0xa7, 0xad, 0x27,
	0xc8, 0x9a, 0x85, 0x83, 0xc6, 0xb3, 0x1a, 0x9f, 0xc1, 0x70, 0xa3, 0xcb, 0x70, 0xe8, 0x2c, 0x2b,
	0xf1, 0x13, 0x9c, 0x12, 0xc1, 0xd7, 0xc4, 0xb0, 0xc2, 0x7d, 0x61, 0x34, 0x0f, 0x62, 0x94, 0xc5,
	0x49, 0x0f, 0x4e, 0x72, 0xdb, 0x1c, 0x78, 0xa4, 0x52, 0xe4, 0x88, 0x74, 0x43, 0x84, 0x60, 0xf2,
	0xc2, 0xc5, 0x4a, 0x7e, 0x5b, 0xca, 0x67, 0x40, 0x7e, 0x68, 0x11, 0x4d, 0xad, 0x98, 0x43, 0x3c,
	0xca, 0x9d, 0xf6, 0x38, 0x83, 0x0e, 0xe7, 0x02, 0x90, 0x66, 0x4a, 0x6a, 0x53, 0xac, 0x88, 0x21,
	0x2d, 0x28, 0x34, 0xd6, 0x1d, 0x31, 0x24, 0xba, 0x01, 0xb4, 0xf3, 0xfb, 0x7d, 0xc5, 0x3f, 0x2b,
	0x29, 0x7c, 0x71, 0xab, 0xb3, 0xdf, 0x00, 0x8e, 0x1f, 0x9a, 0x06, 0xf8, 0x0d, 0x4e, 0xfc, 0xf6,
	0x70, 0x7f, 0xd1, 0x9d, 0xa5, 0xcf, 0xae, 0x0e, 0x4c, 0xda, 0xae, 0xaf, 0x30, 0x6e, 0xaa, 0xe3,
	0xcb, 0xde, 0x53, 0xff, 0xcb, 0x9a, 0xc5, 0x07, 0xe5, 0x54, 0x59, 0x2f, 0xc7, 0xee, 0xbe, 0x5c,
	0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x41, 0x3d, 0x65, 0x3d, 0x65, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FissionClient is the client API for Fission service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FissionClient interface {
	// 活动入口
	Entrance(ctx context.Context, in *EntranceReq, opts ...grpc.CallOption) (*EntranceReply, error)
	// 首页弹窗
	Window(ctx context.Context, in *WindowReq, opts ...grpc.CallOption) (*WindowReply, error)
}

type fissionClient struct {
	cc *grpc.ClientConn
}

func NewFissionClient(cc *grpc.ClientConn) FissionClient {
	return &fissionClient{cc}
}

func (c *fissionClient) Entrance(ctx context.Context, in *EntranceReq, opts ...grpc.CallOption) (*EntranceReply, error) {
	out := new(EntranceReply)
	err := c.cc.Invoke(ctx, "/bilibili.account.fission.v1.Fission/Entrance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fissionClient) Window(ctx context.Context, in *WindowReq, opts ...grpc.CallOption) (*WindowReply, error) {
	out := new(WindowReply)
	err := c.cc.Invoke(ctx, "/bilibili.account.fission.v1.Fission/Window", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FissionServer is the server API for Fission service.
type FissionServer interface {
	// 活动入口
	Entrance(context.Context, *EntranceReq) (*EntranceReply, error)
	// 首页弹窗
	Window(context.Context, *WindowReq) (*WindowReply, error)
}

// UnimplementedFissionServer can be embedded to have forward compatible implementations.
type UnimplementedFissionServer struct {
}

func (*UnimplementedFissionServer) Entrance(ctx context.Context, req *EntranceReq) (*EntranceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Entrance not implemented")
}
func (*UnimplementedFissionServer) Window(ctx context.Context, req *WindowReq) (*WindowReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Window not implemented")
}

func RegisterFissionServer(s *grpc.Server, srv FissionServer) {
	s.RegisterService(&_Fission_serviceDesc, srv)
}

func _Fission_Entrance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntranceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FissionServer).Entrance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bilibili.account.fission.v1.Fission/Entrance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FissionServer).Entrance(ctx, req.(*EntranceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fission_Window_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WindowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FissionServer).Window(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bilibili.account.fission.v1.Fission/Window",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FissionServer).Window(ctx, req.(*WindowReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Fission_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bilibili.account.fission.v1.Fission",
	HandlerType: (*FissionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Entrance",
			Handler:    _Fission_Entrance_Handler,
		},
		{
			MethodName: "Window",
			Handler:    _Fission_Window_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_api/bilibili/account/fission/v1/fission.proto",
}
