// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_api/bilibili/app/resource/v1/module.proto

package bilibili_app_resource_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
type CompressType int32

const (
	CompressType_Unzip    CompressType = 0
	CompressType_Original CompressType = 1
)

var CompressType_name = map[int32]string{
	0: "Unzip",
	1: "Original",
}

var CompressType_value = map[string]int32{
	"Unzip":    0,
	"Original": 1,
}

func (x CompressType) String() string {
	return proto.EnumName(CompressType_name, int32(x))
}

func (CompressType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9fef4cdc2d6dcf9e, []int{0}
}

//
type EnvType int32

const (
	EnvType_Unknown EnvType = 0
	EnvType_Release EnvType = 1
	EnvType_Test    EnvType = 2
)

var EnvType_name = map[int32]string{
	0: "Unknown",
	1: "Release",
	2: "Test",
}

var EnvType_value = map[string]int32{
	"Unknown": 0,
	"Release": 1,
	"Test":    2,
}

func (x EnvType) String() string {
	return proto.EnumName(EnvType_name, int32(x))
}

func (EnvType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9fef4cdc2d6dcf9e, []int{1}
}

//
type IncrementType int32

const (
	IncrementType_Total       IncrementType = 0
	IncrementType_Incremental IncrementType = 1
)

var IncrementType_name = map[int32]string{
	0: "Total",
	1: "Incremental",
}

var IncrementType_value = map[string]int32{
	"Total":       0,
	"Incremental": 1,
}

func (x IncrementType) String() string {
	return proto.EnumName(IncrementType_name, int32(x))
}

func (IncrementType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9fef4cdc2d6dcf9e, []int{2}
}

//
type LevelType int32

const (
	LevelType_Undefined LevelType = 0
	LevelType_High      LevelType = 1
	LevelType_Middle    LevelType = 2
	LevelType_Low       LevelType = 3
)

var LevelType_name = map[int32]string{
	0: "Undefined",
	1: "High",
	2: "Middle",
	3: "Low",
}

var LevelType_value = map[string]int32{
	"Undefined": 0,
	"High":      1,
	"Middle":    2,
	"Low":       3,
}

func (x LevelType) String() string {
	return proto.EnumName(LevelType_name, int32(x))
}

func (LevelType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9fef4cdc2d6dcf9e, []int{3}
}

type ListReply struct {
	//
	Env string `protobuf:"bytes,1,opt,name=env,proto3" json:"env,omitempty"`
	//
	Pools []*PoolReply `protobuf:"bytes,2,rep,name=pools,proto3" json:"pools,omitempty"`
	//
	ListVersion          int64    `protobuf:"varint,3,opt,name=list_version,json=listVersion,proto3" json:"list_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReply) Reset()         { *m = ListReply{} }
func (m *ListReply) String() string { return proto.CompactTextString(m) }
func (*ListReply) ProtoMessage()    {}
func (*ListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fef4cdc2d6dcf9e, []int{0}
}

func (m *ListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReply.Unmarshal(m, b)
}
func (m *ListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReply.Marshal(b, m, deterministic)
}
func (m *ListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReply.Merge(m, src)
}
func (m *ListReply) XXX_Size() int {
	return xxx_messageInfo_ListReply.Size(m)
}
func (m *ListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListReply proto.InternalMessageInfo

func (m *ListReply) GetEnv() string {
	if m != nil {
		return m.Env
	}
	return ""
}

func (m *ListReply) GetPools() []*PoolReply {
	if m != nil {
		return m.Pools
	}
	return nil
}

func (m *ListReply) GetListVersion() int64 {
	if m != nil {
		return m.ListVersion
	}
	return 0
}

//
type ListReq struct {
	//
	PoolName string `protobuf:"bytes,1,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	//
	ModuleName string `protobuf:"bytes,2,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	//
	VersionList []*VersionListReq `protobuf:"bytes,3,rep,name=version_list,json=versionList,proto3" json:"version_list,omitempty"`
	//
	Env EnvType `protobuf:"varint,4,opt,name=env,proto3,enum=bilibili.app.resource.v1.EnvType" json:"env,omitempty"`
	//
	SysVer int32 `protobuf:"varint,5,opt,name=sys_ver,json=sysVer,proto3" json:"sys_ver,omitempty"`
	//
	Scale int32 `protobuf:"varint,6,opt,name=scale,proto3" json:"scale,omitempty"`
	//
	Arch int32 `protobuf:"varint,7,opt,name=arch,proto3" json:"arch,omitempty"`
	//
	ListVersion          int64    `protobuf:"varint,8,opt,name=list_version,json=listVersion,proto3" json:"list_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReq) Reset()         { *m = ListReq{} }
func (m *ListReq) String() string { return proto.CompactTextString(m) }
func (*ListReq) ProtoMessage()    {}
func (*ListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fef4cdc2d6dcf9e, []int{1}
}

func (m *ListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReq.Unmarshal(m, b)
}
func (m *ListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReq.Marshal(b, m, deterministic)
}
func (m *ListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReq.Merge(m, src)
}
func (m *ListReq) XXX_Size() int {
	return xxx_messageInfo_ListReq.Size(m)
}
func (m *ListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListReq proto.InternalMessageInfo

func (m *ListReq) GetPoolName() string {
	if m != nil {
		return m.PoolName
	}
	return ""
}

func (m *ListReq) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

func (m *ListReq) GetVersionList() []*VersionListReq {
	if m != nil {
		return m.VersionList
	}
	return nil
}

func (m *ListReq) GetEnv() EnvType {
	if m != nil {
		return m.Env
	}
	return EnvType_Unknown
}

func (m *ListReq) GetSysVer() int32 {
	if m != nil {
		return m.SysVer
	}
	return 0
}

func (m *ListReq) GetScale() int32 {
	if m != nil {
		return m.Scale
	}
	return 0
}

func (m *ListReq) GetArch() int32 {
	if m != nil {
		return m.Arch
	}
	return 0
}

func (m *ListReq) GetListVersion() int64 {
	if m != nil {
		return m.ListVersion
	}
	return 0
}

//
type ModuleReply struct {
	//
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//
	Version int64 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	//
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	//
	Md5 string `protobuf:"bytes,4,opt,name=md5,proto3" json:"md5,omitempty"`
	//
	TotalMd5 string `protobuf:"bytes,5,opt,name=total_md5,json=totalMd5,proto3" json:"total_md5,omitempty"`
	//
	Increment IncrementType `protobuf:"varint,6,opt,name=increment,proto3,enum=bilibili.app.resource.v1.IncrementType" json:"increment,omitempty"`
	//
	IsWifi bool `protobuf:"varint,7,opt,name=is_wifi,json=isWifi,proto3" json:"is_wifi,omitempty"`
	//
	Level LevelType `protobuf:"varint,8,opt,name=level,proto3,enum=bilibili.app.resource.v1.LevelType" json:"level,omitempty"`
	//
	Filename string `protobuf:"bytes,9,opt,name=filename,proto3" json:"filename,omitempty"`
	//
	FileType string `protobuf:"bytes,10,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	//
	FileSize int64 `protobuf:"varint,11,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	//
	Compress CompressType `protobuf:"varint,12,opt,name=compress,proto3,enum=bilibili.app.resource.v1.CompressType" json:"compress,omitempty"`
	//
	PublishTime int64 `protobuf:"varint,13,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
	// 上报使用
	PoolId int64 `protobuf:"varint,14,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	//
	ModuleId int64 `protobuf:"varint,15,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	//
	VersionId int64 `protobuf:"varint,16,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	//
	FileId int64 `protobuf:"varint,17,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	//
	ZipCheck             bool     `protobuf:"varint,18,opt,name=zip_check,json=zipCheck,proto3" json:"zip_check,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleReply) Reset()         { *m = ModuleReply{} }
func (m *ModuleReply) String() string { return proto.CompactTextString(m) }
func (*ModuleReply) ProtoMessage()    {}
func (*ModuleReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fef4cdc2d6dcf9e, []int{2}
}

func (m *ModuleReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleReply.Unmarshal(m, b)
}
func (m *ModuleReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleReply.Marshal(b, m, deterministic)
}
func (m *ModuleReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleReply.Merge(m, src)
}
func (m *ModuleReply) XXX_Size() int {
	return xxx_messageInfo_ModuleReply.Size(m)
}
func (m *ModuleReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleReply.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleReply proto.InternalMessageInfo

func (m *ModuleReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ModuleReply) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ModuleReply) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ModuleReply) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

func (m *ModuleReply) GetTotalMd5() string {
	if m != nil {
		return m.TotalMd5
	}
	return ""
}

func (m *ModuleReply) GetIncrement() IncrementType {
	if m != nil {
		return m.Increment
	}
	return IncrementType_Total
}

func (m *ModuleReply) GetIsWifi() bool {
	if m != nil {
		return m.IsWifi
	}
	return false
}

func (m *ModuleReply) GetLevel() LevelType {
	if m != nil {
		return m.Level
	}
	return LevelType_Undefined
}

func (m *ModuleReply) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *ModuleReply) GetFileType() string {
	if m != nil {
		return m.FileType
	}
	return ""
}

func (m *ModuleReply) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *ModuleReply) GetCompress() CompressType {
	if m != nil {
		return m.Compress
	}
	return CompressType_Unzip
}

func (m *ModuleReply) GetPublishTime() int64 {
	if m != nil {
		return m.PublishTime
	}
	return 0
}

func (m *ModuleReply) GetPoolId() int64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *ModuleReply) GetModuleId() int64 {
	if m != nil {
		return m.ModuleId
	}
	return 0
}

func (m *ModuleReply) GetVersionId() int64 {
	if m != nil {
		return m.VersionId
	}
	return 0
}

func (m *ModuleReply) GetFileId() int64 {
	if m != nil {
		return m.FileId
	}
	return 0
}

func (m *ModuleReply) GetZipCheck() bool {
	if m != nil {
		return m.ZipCheck
	}
	return false
}

type PoolReply struct {
	//
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//
	Modules              []*ModuleReply `protobuf:"bytes,2,rep,name=modules,proto3" json:"modules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PoolReply) Reset()         { *m = PoolReply{} }
func (m *PoolReply) String() string { return proto.CompactTextString(m) }
func (*PoolReply) ProtoMessage()    {}
func (*PoolReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fef4cdc2d6dcf9e, []int{3}
}

func (m *PoolReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PoolReply.Unmarshal(m, b)
}
func (m *PoolReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PoolReply.Marshal(b, m, deterministic)
}
func (m *PoolReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolReply.Merge(m, src)
}
func (m *PoolReply) XXX_Size() int {
	return xxx_messageInfo_PoolReply.Size(m)
}
func (m *PoolReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolReply.DiscardUnknown(m)
}

var xxx_messageInfo_PoolReply proto.InternalMessageInfo

func (m *PoolReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PoolReply) GetModules() []*ModuleReply {
	if m != nil {
		return m.Modules
	}
	return nil
}

//
type VersionListReq struct {
	//
	PoolName string `protobuf:"bytes,1,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	//
	Versions             []*VersionReq `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *VersionListReq) Reset()         { *m = VersionListReq{} }
func (m *VersionListReq) String() string { return proto.CompactTextString(m) }
func (*VersionListReq) ProtoMessage()    {}
func (*VersionListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fef4cdc2d6dcf9e, []int{4}
}

func (m *VersionListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionListReq.Unmarshal(m, b)
}
func (m *VersionListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionListReq.Marshal(b, m, deterministic)
}
func (m *VersionListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionListReq.Merge(m, src)
}
func (m *VersionListReq) XXX_Size() int {
	return xxx_messageInfo_VersionListReq.Size(m)
}
func (m *VersionListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionListReq.DiscardUnknown(m)
}

var xxx_messageInfo_VersionListReq proto.InternalMessageInfo

func (m *VersionListReq) GetPoolName() string {
	if m != nil {
		return m.PoolName
	}
	return ""
}

func (m *VersionListReq) GetVersions() []*VersionReq {
	if m != nil {
		return m.Versions
	}
	return nil
}

//
type VersionReq struct {
	//
	ModuleName string `protobuf:"bytes,1,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	//
	Version              int64    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionReq) Reset()         { *m = VersionReq{} }
func (m *VersionReq) String() string { return proto.CompactTextString(m) }
func (*VersionReq) ProtoMessage()    {}
func (*VersionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fef4cdc2d6dcf9e, []int{5}
}

func (m *VersionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionReq.Unmarshal(m, b)
}
func (m *VersionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionReq.Marshal(b, m, deterministic)
}
func (m *VersionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionReq.Merge(m, src)
}
func (m *VersionReq) XXX_Size() int {
	return xxx_messageInfo_VersionReq.Size(m)
}
func (m *VersionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionReq.DiscardUnknown(m)
}

var xxx_messageInfo_VersionReq proto.InternalMessageInfo

func (m *VersionReq) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

func (m *VersionReq) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterEnum("bilibili.app.resource.v1.CompressType", CompressType_name, CompressType_value)
	proto.RegisterEnum("bilibili.app.resource.v1.EnvType", EnvType_name, EnvType_value)
	proto.RegisterEnum("bilibili.app.resource.v1.IncrementType", IncrementType_name, IncrementType_value)
	proto.RegisterEnum("bilibili.app.resource.v1.LevelType", LevelType_name, LevelType_value)
	proto.RegisterType((*ListReply)(nil), "bilibili.app.resource.v1.ListReply")
	proto.RegisterType((*ListReq)(nil), "bilibili.app.resource.v1.ListReq")
	proto.RegisterType((*ModuleReply)(nil), "bilibili.app.resource.v1.ModuleReply")
	proto.RegisterType((*PoolReply)(nil), "bilibili.app.resource.v1.PoolReply")
	proto.RegisterType((*VersionListReq)(nil), "bilibili.app.resource.v1.VersionListReq")
	proto.RegisterType((*VersionReq)(nil), "bilibili.app.resource.v1.VersionReq")
}

func init() {
	proto.RegisterFile("grpc_api/bilibili/app/resource/v1/module.proto", fileDescriptor_9fef4cdc2d6dcf9e)
}

var fileDescriptor_9fef4cdc2d6dcf9e = []byte{
	// 784 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0x5f, 0x4f, 0xe3, 0x46,
	0x10, 0x8f, 0xf3, 0xcf, 0xf6, 0x38, 0x04, 0x77, 0x55, 0xa9, 0x2b, 0xaa, 0xaa, 0x21, 0xb4, 0x25,
	0xa2, 0x6a, 0x22, 0x82, 0x78, 0xe0, 0xa9, 0x55, 0x11, 0x6a, 0xa3, 0x03, 0xee, 0xe4, 0x0b, 0xdc,
	0xbd, 0xf9, 0x8c, 0xbd, 0x21, 0x2b, 0xd6, 0xf6, 0x9e, 0xd7, 0x09, 0x4a, 0xee, 0x43, 0xdd, 0x47,
	0xba, 0xaf, 0x72, 0xda, 0x5d, 0x3b, 0x81, 0xe3, 0x02, 0x0f, 0x96, 0x76, 0x7e, 0xf3, 0x67, 0x67,
	0x7e, 0x33, 0xb3, 0x86, 0xfe, 0x6d, 0xc6, 0x43, 0x3f, 0xe0, 0x74, 0x70, 0x43, 0x19, 0x95, 0xdf,
	0x20, 0xe0, 0x7c, 0x90, 0x11, 0x91, 0xce, 0xb2, 0x90, 0x0c, 0xe6, 0x87, 0x83, 0x38, 0x8d, 0x66,
	0x8c, 0xf4, 0x79, 0x96, 0xe6, 0x29, 0xc2, 0xa5, 0x59, 0x3f, 0xe0, 0xbc, 0x5f, 0x9a, 0xf5, 0xe7,
	0x87, 0xdd, 0x4f, 0x60, 0x9f, 0x53, 0x91, 0x7b, 0x84, 0xb3, 0x05, 0x72, 0xa1, 0x46, 0x92, 0x39,
	0x36, 0x3a, 0x46, 0xcf, 0xf6, 0xe4, 0x11, 0x9d, 0x40, 0x83, 0xa7, 0x29, 0x13, 0xb8, 0xda, 0xa9,
	0xf5, 0x9c, 0xe1, 0x5e, 0x7f, 0x53, 0xa0, 0xfe, 0x9b, 0x34, 0x65, 0x2a, 0x8a, 0xa7, 0x3d, 0xd0,
	0x2e, 0xb4, 0x18, 0x15, 0xb9, 0x3f, 0x27, 0x99, 0xa0, 0x69, 0x82, 0x6b, 0x1d, 0xa3, 0x57, 0xf3,
	0x1c, 0x89, 0x5d, 0x6b, 0xa8, 0xfb, 0xb9, 0x0a, 0xa6, 0xbe, 0xfd, 0x23, 0xfa, 0x19, 0x6c, 0xe9,
	0xe7, 0x27, 0x41, 0x4c, 0x8a, 0x0c, 0x2c, 0x09, 0x5c, 0x06, 0x31, 0x41, 0xbf, 0x82, 0xa3, 0xeb,
	0xd1, 0xea, 0xaa, 0x52, 0x83, 0x86, 0x94, 0xc1, 0x2b, 0x68, 0x15, 0xf7, 0xf8, 0xf2, 0x02, 0x5c,
	0x53, 0xe9, 0xf6, 0x36, 0xa7, 0x5b, 0xa4, 0x50, 0xdc, 0xee, 0x39, 0xf3, 0xb5, 0x8c, 0x8e, 0x34,
	0x0d, 0xf5, 0x8e, 0xd1, 0x6b, 0x0f, 0x77, 0x37, 0xc7, 0x38, 0x4b, 0xe6, 0xe3, 0x05, 0x27, 0x9a,
	0xa9, 0x9f, 0xc0, 0x14, 0x0b, 0x21, 0xab, 0xc5, 0x8d, 0x8e, 0xd1, 0x6b, 0x78, 0x4d, 0xb1, 0x10,
	0xd7, 0x24, 0x43, 0x3f, 0x42, 0x43, 0x84, 0x01, 0x23, 0xb8, 0xa9, 0x60, 0x2d, 0x20, 0x04, 0xf5,
	0x20, 0x0b, 0xa7, 0xd8, 0x54, 0xa0, 0x3a, 0x3f, 0x61, 0xcc, 0x7a, 0xca, 0xd8, 0x97, 0x3a, 0x38,
	0x17, 0xaa, 0x6c, 0xdd, 0x31, 0x04, 0xf5, 0x07, 0x84, 0xa9, 0x33, 0xc2, 0x60, 0x96, 0x11, 0xaa,
	0x2a, 0x42, 0x29, 0xca, 0xfe, 0xce, 0x32, 0xa6, 0x3a, 0x61, 0x7b, 0xf2, 0x28, 0x91, 0x38, 0x3a,
	0x56, 0xa5, 0xda, 0x9e, 0x3c, 0xca, 0x3e, 0xe4, 0x69, 0x1e, 0x30, 0x5f, 0xe2, 0x0d, 0xdd, 0x07,
	0x05, 0x5c, 0x44, 0xc7, 0xe8, 0x0c, 0x6c, 0x9a, 0x84, 0x19, 0x89, 0x49, 0x92, 0xab, 0x7a, 0xda,
	0xc3, 0xfd, 0xcd, 0xfc, 0x8c, 0x4a, 0x53, 0xc5, 0xd2, 0xda, 0x53, 0x72, 0x45, 0x85, 0x7f, 0x4f,
	0x27, 0x54, 0xd5, 0x6f, 0x79, 0x4d, 0x2a, 0xde, 0xd1, 0x09, 0x95, 0xe3, 0xc6, 0xc8, 0x9c, 0x30,
	0x55, 0x7a, 0xfb, 0xb9, 0x71, 0x3b, 0x97, 0x66, 0x2a, 0xae, 0xf6, 0x40, 0x3b, 0x60, 0x4d, 0x28,
	0x23, 0x8a, 0x0d, 0x5b, 0xa7, 0x5d, 0xca, 0xb2, 0x26, 0x79, 0xf6, 0xf3, 0x05, 0x27, 0x18, 0xd6,
	0x4a, 0xe9, 0xbf, 0x52, 0x0a, 0xba, 0x24, 0xd8, 0x51, 0x84, 0x29, 0xe5, 0x5b, 0xba, 0x24, 0xe8,
	0x5f, 0xb0, 0xc2, 0x34, 0xe6, 0x19, 0x11, 0x02, 0xb7, 0x54, 0x4e, 0x7f, 0x6c, 0xce, 0xe9, 0xb4,
	0xb0, 0x54, 0x69, 0xad, 0xfc, 0x64, 0x5b, 0xf9, 0xec, 0x86, 0x51, 0x31, 0xf5, 0x73, 0x1a, 0x13,
	0xbc, 0xa5, 0xdb, 0x5a, 0x60, 0x63, 0x1a, 0x13, 0x49, 0x88, 0x1a, 0x7e, 0x1a, 0xe1, 0xb6, 0xd2,
	0x36, 0xa5, 0x38, 0x8a, 0x64, 0x72, 0xc5, 0xe0, 0xd3, 0x08, 0x6f, 0xeb, 0xe4, 0x34, 0x30, 0x8a,
	0xd0, 0x2f, 0x00, 0xe5, 0xd0, 0xd3, 0x08, 0xbb, 0x4a, 0x6b, 0x17, 0xc8, 0x28, 0x92, 0x41, 0x55,
	0x61, 0x34, 0xc2, 0x3f, 0xe8, 0xa0, 0x52, 0xd4, 0x41, 0x97, 0x94, 0xfb, 0xe1, 0x94, 0x84, 0x77,
	0x18, 0xa9, 0x06, 0x58, 0x4b, 0xca, 0x4f, 0xa5, 0xdc, 0xfd, 0x00, 0xf6, 0x6a, 0x95, 0xbf, 0x3b,
	0x5e, 0x7f, 0x83, 0xa9, 0x33, 0x28, 0x1f, 0x85, 0xdf, 0x37, 0x33, 0xf2, 0x60, 0x54, 0xbd, 0xd2,
	0xab, 0x9b, 0x42, 0xfb, 0xf1, 0xf6, 0x3d, 0xbf, 0xfb, 0xff, 0x80, 0x55, 0xd4, 0x54, 0x5e, 0xf8,
	0xdb, 0x8b, 0x6b, 0x2d, 0x57, 0x7a, 0xe5, 0xd5, 0xfd, 0x0f, 0x60, 0x8d, 0x7f, 0xfb, 0x96, 0x18,
	0x4f, 0xde, 0x92, 0x8d, 0xfb, 0x73, 0xb0, 0x0f, 0xad, 0x87, 0x3d, 0x46, 0x36, 0x34, 0xae, 0x92,
	0x25, 0xe5, 0x6e, 0x05, 0xb5, 0xc0, 0x7a, 0x9d, 0xd1, 0x5b, 0x9a, 0x04, 0xcc, 0x35, 0x0e, 0xfe,
	0x02, 0xb3, 0x78, 0x1c, 0x90, 0x03, 0xe6, 0x55, 0x72, 0x97, 0xa4, 0xf7, 0x89, 0x5b, 0x91, 0x82,
	0x47, 0x18, 0x09, 0x04, 0x71, 0x0d, 0x64, 0x41, 0x7d, 0x4c, 0x44, 0xee, 0x56, 0x0f, 0xfe, 0x84,
	0xad, 0x47, 0xbb, 0x22, 0x03, 0x8f, 0xe5, 0xce, 0xb9, 0x15, 0xb4, 0x0d, 0xce, 0x4a, 0xa7, 0x62,
	0x9f, 0x80, 0xbd, 0x1a, 0x7e, 0xb4, 0x05, 0xf6, 0x55, 0x12, 0x91, 0x09, 0x4d, 0x48, 0xe4, 0x56,
	0x64, 0xc8, 0xff, 0xe9, 0xed, 0xd4, 0x35, 0x10, 0x40, 0xf3, 0x82, 0x46, 0x11, 0x23, 0x6e, 0x15,
	0x99, 0x50, 0x3b, 0x4f, 0xef, 0xdd, 0xda, 0xf0, 0x3d, 0x34, 0x75, 0x47, 0xd0, 0x25, 0xd4, 0xd5,
	0x53, 0xf7, 0xcc, 0xeb, 0x56, 0x34, 0x67, 0x67, 0xef, 0x25, 0x13, 0xce, 0x16, 0x37, 0x4d, 0xf5,
	0x9f, 0x39, 0xfa, 0x1a, 0x00, 0x00, 0xff, 0xff, 0xa1, 0xa2, 0x02, 0x14, 0x99, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ModuleClient is the client API for Module service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ModuleClient interface {
	//
	List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListReply, error)
}

type moduleClient struct {
	cc *grpc.ClientConn
}

func NewModuleClient(cc *grpc.ClientConn) ModuleClient {
	return &moduleClient{cc}
}

func (c *moduleClient) List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := c.cc.Invoke(ctx, "/bilibili.app.resource.v1.Module/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModuleServer is the server API for Module service.
type ModuleServer interface {
	//
	List(context.Context, *ListReq) (*ListReply, error)
}

// UnimplementedModuleServer can be embedded to have forward compatible implementations.
type UnimplementedModuleServer struct {
}

func (*UnimplementedModuleServer) List(ctx context.Context, req *ListReq) (*ListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterModuleServer(s *grpc.Server, srv ModuleServer) {
	s.RegisterService(&_Module_serviceDesc, srv)
}

func _Module_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bilibili.app.resource.v1.Module/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServer).List(ctx, req.(*ListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Module_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bilibili.app.resource.v1.Module",
	HandlerType: (*ModuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Module_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc_api/bilibili/app/resource/v1/module.proto",
}
