// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_api/bilibili/broadcast/v1/mod.proto

package bilibili_broadcast_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//
type ModResourceResp struct {
	//
	Atcion int32 `protobuf:"varint,1,opt,name=atcion,proto3" json:"atcion,omitempty"`
	//
	AppKey string `protobuf:"bytes,2,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	//
	PoolName string `protobuf:"bytes,3,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	//
	ModuleName string `protobuf:"bytes,4,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	//
	ModuleVersion int64 `protobuf:"varint,5,opt,name=module_version,json=moduleVersion,proto3" json:"module_version,omitempty"`
	//
	ListVersion          int64    `protobuf:"varint,6,opt,name=list_version,json=listVersion,proto3" json:"list_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModResourceResp) Reset()         { *m = ModResourceResp{} }
func (m *ModResourceResp) String() string { return proto.CompactTextString(m) }
func (*ModResourceResp) ProtoMessage()    {}
func (*ModResourceResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3742323f0a0419a7, []int{0}
}

func (m *ModResourceResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModResourceResp.Unmarshal(m, b)
}
func (m *ModResourceResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModResourceResp.Marshal(b, m, deterministic)
}
func (m *ModResourceResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModResourceResp.Merge(m, src)
}
func (m *ModResourceResp) XXX_Size() int {
	return xxx_messageInfo_ModResourceResp.Size(m)
}
func (m *ModResourceResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ModResourceResp.DiscardUnknown(m)
}

var xxx_messageInfo_ModResourceResp proto.InternalMessageInfo

func (m *ModResourceResp) GetAtcion() int32 {
	if m != nil {
		return m.Atcion
	}
	return 0
}

func (m *ModResourceResp) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *ModResourceResp) GetPoolName() string {
	if m != nil {
		return m.PoolName
	}
	return ""
}

func (m *ModResourceResp) GetModuleName() string {
	if m != nil {
		return m.ModuleName
	}
	return ""
}

func (m *ModResourceResp) GetModuleVersion() int64 {
	if m != nil {
		return m.ModuleVersion
	}
	return 0
}

func (m *ModResourceResp) GetListVersion() int64 {
	if m != nil {
		return m.ListVersion
	}
	return 0
}

func init() {
	proto.RegisterType((*ModResourceResp)(nil), "bilibili.broadcast.v1.ModResourceResp")
}

func init() {
	proto.RegisterFile("grpc_api/bilibili/broadcast/v1/mod.proto", fileDescriptor_3742323f0a0419a7)
}

var fileDescriptor_3742323f0a0419a7 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0x80, 0x89, 0x73, 0xd5, 0xbd, 0x39, 0x85, 0x80, 0x73, 0x6c, 0x07, 0xa7, 0xa0, 0xf4, 0x94,
	0x38, 0xfd, 0x0d, 0x9e, 0x64, 0x82, 0x3d, 0xe8, 0xb1, 0xa4, 0xed, 0xb3, 0x16, 0xdb, 0xbd, 0x90,
	0x66, 0x85, 0xfe, 0x45, 0x7f, 0x95, 0x34, 0x69, 0x77, 0x10, 0x0f, 0x39, 0xe4, 0x7b, 0xdf, 0x23,
	0xe4, 0x83, 0x30, 0x37, 0x3a, 0x8d, 0x95, 0x2e, 0x64, 0x52, 0x94, 0x45, 0x77, 0x64, 0x62, 0x48,
	0x65, 0xa9, 0xaa, 0xad, 0x6c, 0x36, 0xb2, 0xa2, 0x4c, 0x68, 0x43, 0x96, 0xf8, 0xe5, 0x20, 0x88,
	0x83, 0x20, 0x9a, 0xcd, 0x72, 0x95, 0x13, 0xe5, 0x25, 0x4a, 0x27, 0x25, 0xfb, 0x4f, 0x89, 0x95,
	0xb6, 0xad, 0xdf, 0xb9, 0xfd, 0x61, 0x70, 0xb1, 0xa5, 0x2c, 0xc2, 0x9a, 0xf6, 0x26, 0xc5, 0x08,
	0x6b, 0xcd, 0xe7, 0x10, 0x28, 0x9b, 0x16, 0xb4, 0x5b, 0xb0, 0x35, 0x0b, 0xc7, 0x51, 0x7f, 0xe3,
	0x57, 0x70, 0xa2, 0xb4, 0x8e, 0xbf, 0xb1, 0x5d, 0x1c, 0xad, 0x59, 0x38, 0x89, 0x02, 0xa5, 0xf5,
	0x0b, 0xb6, 0x7c, 0x05, 0x13, 0x4d, 0x54, 0xc6, 0x3b, 0x55, 0xe1, 0x62, 0xe4, 0x46, 0xa7, 0x1d,
	0x78, 0x55, 0x15, 0xf2, 0x6b, 0x98, 0x56, 0x94, 0xed, 0x4b, 0xf4, 0xe3, 0x63, 0x37, 0x06, 0x8f,
	0x9c, 0x70, 0x07, 0xe7, 0xbd, 0xd0, 0xa0, 0xa9, 0xbb, 0x67, 0xc7, 0x6b, 0x16, 0x8e, 0xa2, 0x99,
	0xa7, 0xef, 0x1e, 0xf2, 0x1b, 0x38, 0x2b, 0x8b, 0xda, 0x1e, 0xa4, 0xc0, 0x49, 0xd3, 0x8e, 0xf5,
	0xca, 0x63, 0x0c, 0xb0, 0xa5, 0x6c, 0xab, 0x76, 0x2a, 0x47, 0xc3, 0xdf, 0x60, 0xf6, 0xa1, 0x6c,
	0xfa, 0x35, 0xfc, 0x8d, 0xcf, 0x85, 0x2f, 0x21, 0x86, 0x12, 0xe2, 0xb9, 0x2b, 0xb1, 0xbc, 0x17,
	0xff, 0x86, 0x13, 0x7f, 0xba, 0x3c, 0xb0, 0x24, 0x70, 0x9b, 0x4f, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xf3, 0x46, 0x77, 0x10, 0x94, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ModManagerClient is the client API for ModManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ModManagerClient interface {
	//
	WatchResource(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (ModManager_WatchResourceClient, error)
}

type modManagerClient struct {
	cc *grpc.ClientConn
}

func NewModManagerClient(cc *grpc.ClientConn) ModManagerClient {
	return &modManagerClient{cc}
}

func (c *modManagerClient) WatchResource(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (ModManager_WatchResourceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ModManager_serviceDesc.Streams[0], "/bilibili.broadcast.v1.ModManager/WatchResource", opts...)
	if err != nil {
		return nil, err
	}
	x := &modManagerWatchResourceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ModManager_WatchResourceClient interface {
	Recv() (*ModResourceResp, error)
	grpc.ClientStream
}

type modManagerWatchResourceClient struct {
	grpc.ClientStream
}

func (x *modManagerWatchResourceClient) Recv() (*ModResourceResp, error) {
	m := new(ModResourceResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ModManagerServer is the server API for ModManager service.
type ModManagerServer interface {
	//
	WatchResource(*emptypb.Empty, ModManager_WatchResourceServer) error
}

// UnimplementedModManagerServer can be embedded to have forward compatible implementations.
type UnimplementedModManagerServer struct {
}

func (*UnimplementedModManagerServer) WatchResource(req *emptypb.Empty, srv ModManager_WatchResourceServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchResource not implemented")
}

func RegisterModManagerServer(s *grpc.Server, srv ModManagerServer) {
	s.RegisterService(&_ModManager_serviceDesc, srv)
}

func _ModManager_WatchResource_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModManagerServer).WatchResource(m, &modManagerWatchResourceServer{stream})
}

type ModManager_WatchResourceServer interface {
	Send(*ModResourceResp) error
	grpc.ServerStream
}

type modManagerWatchResourceServer struct {
	grpc.ServerStream
}

func (x *modManagerWatchResourceServer) Send(m *ModResourceResp) error {
	return x.ServerStream.SendMsg(m)
}

var _ModManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bilibili.broadcast.v1.ModManager",
	HandlerType: (*ModManagerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchResource",
			Handler:       _ModManager_WatchResource_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc_api/bilibili/broadcast/v1/mod.proto",
}
