// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_api/bilibili/metadata/network/network.proto

package bilibili_metadata_network

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 网络类型
type NetworkType int32

const (
	NetworkType_NT_UNKNOWN NetworkType = 0
	NetworkType_WIFI       NetworkType = 1
	NetworkType_CELLULAR   NetworkType = 2
	NetworkType_OFFLINE    NetworkType = 3
	NetworkType_OTHERNET   NetworkType = 4
	NetworkType_ETHERNET   NetworkType = 5
)

var NetworkType_name = map[int32]string{
	0: "NT_UNKNOWN",
	1: "WIFI",
	2: "CELLULAR",
	3: "OFFLINE",
	4: "OTHERNET",
	5: "ETHERNET",
}

var NetworkType_value = map[string]int32{
	"NT_UNKNOWN": 0,
	"WIFI":       1,
	"CELLULAR":   2,
	"OFFLINE":    3,
	"OTHERNET":   4,
	"ETHERNET":   5,
}

func (x NetworkType) String() string {
	return proto.EnumName(NetworkType_name, int32(x))
}

func (NetworkType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_478332a01d59073c, []int{0}
}

// 免流类型
type TFType int32

const (
	TFType_TF_UNKNOWN TFType = 0
	TFType_U_CARD     TFType = 1
	TFType_U_PKG      TFType = 2
	TFType_C_CARD     TFType = 3
	TFType_C_PKG      TFType = 4
	TFType_T_CARD     TFType = 5
	TFType_T_PKG      TFType = 6
)

var TFType_name = map[int32]string{
	0: "TF_UNKNOWN",
	1: "U_CARD",
	2: "U_PKG",
	3: "C_CARD",
	4: "C_PKG",
	5: "T_CARD",
	6: "T_PKG",
}

var TFType_value = map[string]int32{
	"TF_UNKNOWN": 0,
	"U_CARD":     1,
	"U_PKG":      2,
	"C_CARD":     3,
	"C_PKG":      4,
	"T_CARD":     5,
	"T_PKG":      6,
}

func (x TFType) String() string {
	return proto.EnumName(TFType_name, int32(x))
}

func (TFType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_478332a01d59073c, []int{1}
}

// 网络类型标识
// gRPC头部:x-bili-network-bin
type Network struct {
	// 网络类型
	Type NetworkType `protobuf:"varint,1,opt,name=type,proto3,enum=bilibili.metadata.network.NetworkType" json:"type,omitempty"`
	// 免流类型
	Tf TFType `protobuf:"varint,2,opt,name=tf,proto3,enum=bilibili.metadata.network.TFType" json:"tf,omitempty"`
	// 运营商
	Oid                  string   `protobuf:"bytes,3,opt,name=oid,proto3" json:"oid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Network) Reset()         { *m = Network{} }
func (m *Network) String() string { return proto.CompactTextString(m) }
func (*Network) ProtoMessage()    {}
func (*Network) Descriptor() ([]byte, []int) {
	return fileDescriptor_478332a01d59073c, []int{0}
}

func (m *Network) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Network.Unmarshal(m, b)
}
func (m *Network) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Network.Marshal(b, m, deterministic)
}
func (m *Network) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Network.Merge(m, src)
}
func (m *Network) XXX_Size() int {
	return xxx_messageInfo_Network.Size(m)
}
func (m *Network) XXX_DiscardUnknown() {
	xxx_messageInfo_Network.DiscardUnknown(m)
}

var xxx_messageInfo_Network proto.InternalMessageInfo

func (m *Network) GetType() NetworkType {
	if m != nil {
		return m.Type
	}
	return NetworkType_NT_UNKNOWN
}

func (m *Network) GetTf() TFType {
	if m != nil {
		return m.Tf
	}
	return TFType_TF_UNKNOWN
}

func (m *Network) GetOid() string {
	if m != nil {
		return m.Oid
	}
	return ""
}

func init() {
	proto.RegisterEnum("bilibili.metadata.network.NetworkType", NetworkType_name, NetworkType_value)
	proto.RegisterEnum("bilibili.metadata.network.TFType", TFType_name, TFType_value)
	proto.RegisterType((*Network)(nil), "bilibili.metadata.network.Network")
}

func init() {
	proto.RegisterFile("grpc_api/bilibili/metadata/network/network.proto", fileDescriptor_478332a01d59073c)
}

var fileDescriptor_478332a01d59073c = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x4d, 0x4b, 0xc3, 0x30,
	0x18, 0xc7, 0x4d, 0xdb, 0x75, 0xdb, 0x33, 0x19, 0x21, 0xa7, 0x7a, 0x9b, 0x1e, 0x64, 0xec, 0xd0,
	0xfa, 0x72, 0xf3, 0x36, 0x6a, 0xa2, 0x65, 0x25, 0x95, 0x90, 0xb2, 0x93, 0x96, 0xce, 0x75, 0x52,
	0x7c, 0x69, 0x28, 0x01, 0xd9, 0x57, 0xf0, 0x53, 0x4b, 0xd2, 0x15, 0x76, 0xd1, 0x43, 0xe9, 0xf3,
	0xfc, 0xf2, 0xff, 0xfd, 0x03, 0x81, 0xab, 0xb7, 0x56, 0xbd, 0x16, 0xa5, 0xaa, 0xa3, 0x4d, 0xfd,
	0x51, 0x9b, 0x2f, 0xfa, 0xac, 0x74, 0xb9, 0x2d, 0x75, 0x19, 0x7d, 0x55, 0xfa, 0xbb, 0x69, 0xdf,
	0xfb, 0x7f, 0xa8, 0xda, 0x46, 0x37, 0xe4, 0xac, 0x0f, 0x86, 0x7d, 0x30, 0x3c, 0x04, 0x2e, 0x7e,
	0x10, 0x0c, 0x79, 0x37, 0x93, 0x3b, 0xf0, 0xf4, 0x5e, 0x55, 0x01, 0x9a, 0xa1, 0xf9, 0xf4, 0xe6,
	0x32, 0xfc, 0xd3, 0x0a, 0x0f, 0x86, 0xdc, 0xab, 0x4a, 0x58, 0x87, 0x5c, 0x83, 0xa3, 0x77, 0x81,
	0x63, 0xcd, 0xf3, 0x7f, 0x4c, 0xc9, 0xac, 0xe4, 0xe8, 0x1d, 0xc1, 0xe0, 0x36, 0xf5, 0x36, 0x70,
	0x67, 0x68, 0x3e, 0x16, 0x66, 0x5c, 0xbc, 0xc0, 0xe4, 0xa8, 0x99, 0x4c, 0x01, 0xb8, 0x2c, 0x72,
	0xbe, 0xe2, 0xd9, 0x9a, 0xe3, 0x13, 0x32, 0x02, 0x6f, 0x9d, 0xb0, 0x04, 0x23, 0x72, 0x0a, 0xa3,
	0x98, 0xa6, 0x69, 0x9e, 0x2e, 0x05, 0x76, 0xc8, 0x04, 0x86, 0x19, 0x63, 0x69, 0xc2, 0x29, 0x76,
	0xcd, 0x51, 0x26, 0x1f, 0xa9, 0xe0, 0x54, 0x62, 0xcf, 0x6c, 0xb4, 0xdf, 0x06, 0x8b, 0x67, 0xf0,
	0xbb, 0xfb, 0x4d, 0xb5, 0x64, 0x47, 0xd5, 0x00, 0x7e, 0x5e, 0xc4, 0x4b, 0x71, 0x8f, 0x11, 0x19,
	0xc3, 0x20, 0x2f, 0x9e, 0x56, 0x0f, 0xd8, 0x31, 0x38, 0xee, 0xb0, 0x6b, 0x70, 0x6c, 0xb1, 0x67,
	0xb0, 0xec, 0xf0, 0xc0, 0x60, 0x69, 0xb1, 0xbf, 0xf1, 0xed, 0x6b, 0xdf, 0xfe, 0x06, 0x00, 0x00,
	0xff, 0xff, 0xbf, 0x64, 0x94, 0x35, 0xa1, 0x01, 0x00, 0x00,
}
